coreos/fedora-coreos-pipeline

- kubernetes-jenkins-plugin/README.md
- kubernetes-jenkins-plugin/kube-fcos-pipeline.yaml
- trigger on buildconfig change
- trigger on imagestream change
- trigger on GitHub webhook
- trigger on Generic webhook (for fedmsg triggered actions)
> kube-fcos-pipeline: add triggers for builds

- Jenkinsfile
This helps us better support the local dev use case.
> Jenkinsfile: make duffy key and rsyncing optional

- HACKING.md
- TROUBLESHOOTING.md
Also clean up HACKING.md a bit and reference the troubleshooting
sections from HACKING.md.
> Add a troubleshooting section

- HACKING.md
- Jenkinsfile
- manifests/bc.yaml
- sleep.yaml
This is obviously better than using the one from my namespace.
> use container for coreos-assembler quay org

- HACKING.md
- manifests/simple-httpd.yaml
This is useful for the local dev case. See `HACKING.md`.
> Add simple-httpd helper app for browsing PV

- HACKING.md
Guide users through the `oc cluster up` workflow and getting the
pipeline set up.
Closes: #3
> HACKING.md: add instructions for local development

- Jenkinsfile
Add a helper to execute shell commands in a consistent environment with
the traditional `set -xeuo pipefail` and always starting in the `/srv`
dir. I initially played with `workingDir: /srv`, but the Kubernetes
plugin tries to be smart and interprets it as a mountpoint to mount into
the container. Which we don't want here since we already have an `/srv`
mountpoint.
I also removed the `| tee` since I don't think it's helping. I think the
issue there is that the `rpm-ostree` running inside supermin thinks it's
got a tty, so we'd have to hack this directly in the init script.
> pipeline: add helper shwrap() function

- HACKING.md
Notes I'm making while going through `HACKING.md` - some may be useful.
Requires: #21
>  HACKING.md: add OKD setup info + notes on IP address

- Jenkinsfile
Since we are now building two raw images and ISOs let's prune a
little more aggressively until we get more space.
> pipeline: prune slightly more aggressively

- Jenkinsfile
Lets produce vmware ova artifacts now that coreos-assembler has the
ability to do it.
> Jenkinsfile: produce vmware ova artifact

- manifests/pipeline.yaml
- manifests/simple-httpd.yaml
Minor patches to get the local dev workflow working again. Includes cherry-pick of #32.
> Small fixes

- manifests/pipeline.yaml
> Bump Jenkins to v2.150.2

- Jenkinsfile
Building metal images is now a separate step since:
https://github.com/coreos/coreos-assembler/pull/510
> pipeline: adapt for split metal building

- HACKING.md
Make it clear that developer pipelines are to be run on existing
clusters/deployments. Also add more context and notes about defaults
and existing behavior.
> HACKING: clear up notes around development pipelines

- Jenkinsfile
- manifests/pipeline.yaml
- streams.groovy
> Prep patches for multi-streams

- Jenkinsfile
So then devel pipelines can have incremental versions and test the logic
around no-ops too.
> pipeline: buildprep from PVC for devel builds

- Jenkinsfile
As discussed in https://github.com/coreos/coreos-assembler/issues/445.
> pipeline: switch to xz compression

- README.md
> README.md: Link to Jenkins

- README.md
Something we can point contributors to.
> README.md: add info on how to gain access to project

- Jenkinsfile
Also added some tweaks to make iterating on `testing-devel` faster.
> Various pipeline fixes

- Jenkinsfile
Otherwise, it'll be referencing uncompressed artifacts.
> Jenkinsfile: create release.json after compressing

- Jenkinsfile.release
Some extra remnants from a copy-paste gone wrong.
> Jenkinsfile.release: drop unused code

- Jenkinsfile
Being able to just launch the latest official `testing-devel` build in
AWS is super useful. For now at least, let's just "release" all the
non-production stream builds we do.
This way we also exercise the release code on the `testing-devel`
stream. I also think it'd be cool if we had Cincinnati also monitor
`testing-devel`, and just apply a dumb policy to allow us to exercise
automatic updates. This would be a prereq for that.
> Jenkinsfile: auto-release non-production stream builds

- Jenkinsfile
Initial work, currently does not store the artifacts and is only running against the QEMU image.
My current plan is to add those features (artifact storage & running against different platforms) in later PRs.
Supersedes #31
> Jenkinsfile: add kola run before building other stages

- Jenkinsfile
First, we were using `du` on the symlink, which always returned 0, so we
never actually nuked the cache. (This is a regression from when we
switched to using the PVC for caching the qcow2s only). Moving it to the
`Init` stage means we can directly use the real filename instead.
Second, we would (try to) nuke the cache after a build, but really we
want to handle this situation *before* a build. This code predates cosa
learning to regenerate the qcow2 at build time instead of only at `init`
time.
Finally, be slightly more conservative and knock the limit down to 7G.
The disk is 10G; so even if we just have 3G left, that should be plenty
for composing into (we should still probably implement some pkgcache
cleaning heuristics in rpm-ostree itself to make this less awkward
thought).
> Jenkinsfile: fix cache nuking logic

- Jenkinsfile
- Jenkinsfile.mechanical
See individual commit messages for details.
> Various pipeline tweaks

- COPYING
- LICENSE
This is the same one as fedora-coreos-config (MIT).
Closes: #122
> Add license

- Jenkinsfile
Turns out we need the metadata uploaded to s3 so we can fetch it
in the Jenkinsfile.kola.aws.
Reverts 13ff6d3.
> Move the Kola AWS run back below Archive stage

- manifests/pipeline.yaml
> Bump Jenkins to v2.176.3

- Jenkinsfile
This is prep for signing, where we'll want to
`cosa sign robosignatory --ostree` in between those two steps.
> Split out OSTree compose from building qemu

- Jenkinsfile
- manifests/pod.yaml
Just hardcode this into the pipeline for now. As mentioned in the
comments, I don't think it warrants making it a full-blown template
parameter yet, but we can revisit if needed.
> Jenkinsfile: use smaller memory request for developers

- Jenkinsfile
This was added recently in COSA. Let's try to build it at least for the
next release.
> pipeline: start building live ISO

- Jenkinsfile
We don't upload anything yet:
https://github.com/coreos/fedora-coreos-tracker/issues/276#issuecomment-543300490
But at least the artifacts are available.
> Jenkinsfile: build aliyun images

- Jenkinsfile
Otherwise, we'll always request signing even if it's a no-op.
> Jenkinsfile: only sign if there's a new build

- HACKING.md
> HACKING.md: Document S3 bucket

- README.md
Gives more visibility on what we actually output.
> README.md: link to download page and build browser

- Jenkinsfile
In the same spirit as:
https://github.com/coreos/coreos-assembler/pull/884
Half wanting to just fold this into `cosa kola` and auto-detect a
reasonable value like we do with xz compression. But meh... let's just
do this for now.
> Jenkinsfile: run kola qemu test in parallel

- Jenkinsfile
Add a `COREOS_ASSEMBLER_IMAGE` parameter that allows overriding the
default one to use. This is useful on its own, but it's necessary right
now for purposely building an FCOS image with older cosa.
In the future, I think we should take the cosa image we used when doing
a release and tag it. And e.g. keep it around for the last 5 releases
per stream? (The next level from this would be using lockfiles for cosa
too... would be cool, but way more overhead!)
> Jenkinsfile: allow overriding cosa image to use

- Jenkinsfile
To help with debugging whether the Kubernetes plugin is screwing up or
our Groovy code.
> Jenkinsfile: print podspec just before launching

- Jenkinsfile.release
We don't currently have permissions to query all the regions:
https://github.com/coreos/fedora-coreos-streams/issues/27#issuecomment-558854714
> Jenkinsfile.release: hardcode regions for now

- Jenkinsfile.release
- Revert "Jenkinsfile.release: hardcode regions for now"
- Jenkinsfile.release: make ore run in verbose mode
> Jenkinsfile.release: AWS revert/enhancement

- Jenkinsfile
We don't upload anything yet but at least users can download the image
and upload it themselves.
> build azure images

- Jenkinsfile
- Jenkinsfile.kola.aws
- Jenkinsfile.release
- Jenkinsfile.stream.metadata.generator
> Some Jenkinsfile properties tweaks

- streams.groovy
Add the entry for a stable stream so we can start building it.
---
Hold for now; we need to create the branch first.
> Add stable stream

- Jenkinsfile
This should be fixed in the latest cosa now:
https://github.com/coreos/coreos-assembler/pull/1021
Closes: https://github.com/coreos/fedora-coreos-pipeline/issues/178
> Jenkinsfile: re-enable signing

- Jenkinsfile.release
Now that https://github.com/coreos/mantle/pull/1151 made it into the
latest cosa.
> release: use new --stream switch instead of --channel

- Jenkinsfile
I forgot to commit this apparently, the error was:
`groovy.lang.MissingPropertyException: No such property: utils for class: groovy.lang.Binding`
Which...TBH I don't understand the scoping rules in Groovy.
> pipeline: Fix crash when kola fails

- Jenkinsfile.kola.aws
> Jenkinsfile.kola.aws: hook up creds for upgrade testing

- HACKING.md
- deploy
- jenkins/config/slack.yaml
- jenkins/master/configuration/users/README.md
- jenkins/master/configuration/users/users.xml
- jenkins/master/plugins.txt
- manifests/pipeline.yaml
- utils.groovy
> Prep patches for prep patches for CoreOS CI

- Jenkinsfile
- Jenkinsfile.kola.aws
- Jenkinsfile.release
This saves us some space on each of the invocation lines.
> Jenkinsfiles: use the `cosa` symlink

- Jenkinsfile
For https://github.com/coreos/fedora-coreos-tracker/issues/385.
> pipeline: build metal4k artifact

- streams.groovy
Requires: https://github.com/coreos/fedora-coreos-config/pull/306
> streams: add next-devel development pipeline

- Jenkinsfile.kola.aws
This is useful for testing changes to kola.
> Jenkinsfile.kola.aws: allow overriding cosa image

- streams.groovy
Now that we have next-devel setup, let's add the next stream!
> Add next stream

- Jenkinsfile
* Vultr images can't be uploaded yet, but it would be nice to build them in an automated fashion
* https://github.com/coreos/fedora-coreos-tracker/issues/355
> Jenkinsfile: Add Vultr image build to pipeline

- Jenkinsfile
`kola testiso` knows how to do this now!
https://github.com/coreos/coreos-assembler/pull/1312
> pipeline: also test metal4k installs

- Jenkinsfile
Instead of passing the parent commit directory to cosa, pass the parent
build ID itself. This will allow us to get a diff against the parent
build, which we can then use on the release notes pages.
> pipeline: pass --parent-build to cosa

- Jenkinsfile.kola.gcp
> Jenkinsfile.kola.gcp: fix bad variable substitution

- jobs/bump-lockfile.Jenkinsfile
This would've caught the recent ostree regression[1] before pushing to
the repo.
[1] https://github.com/coreos/fedora-coreos-tracker/issues/589
> bump-lockfile: build metal images and run `testiso`

- HACKING.md
- deploy
- manifests/jenkins.yaml
> Various fixes noticed while migrating to OCP4 cluster

- Jenkinsfile
This should marginally improve the build speed.
> Go Fast: run builds in parallel

- Jenkinsfile
> pipeline: switch testing/testing-devel to modern PXE artifacts

- Jenkinsfile
Switch to the modern artifacts.
> pipeline: disable legacy PXE artifacts on stable

- jobs/sync-stream-metadata.Jenkinsfile
Switching to syncing per-stream in #291 worked, but it broke change
detection using `--dryrun` such that now `aws s3 sync` always uploads
files even if nothing changed. Some bug in using
`--exclude '*' --include a/specific/file` maybe? I also noticed that the
invocation takes much longer, I think because we're syncing at the root
of the bucket and it needs to get a full listing of the files in there
or something?
Anyway, switching to syncing the `streams` and `updates` directories
specifically is much faster and restores the no-change detection, so
let's do that.
I went with Dusty's suggestion in #288 to just do the operation without
`--dryrun` and determine based on that whether to emit a fedmsg.
> jobs/sync-stream-metadata: fix no-change detection

- jobs/sync-stream-metadata.Jenkinsfile
`aws s3 sync` doesn't sync based on file contents, but rather just on
file size and timestamps. And because our git checkout will always be
fresh, it'll always seem newer than the S3 copy and thus we'll always
upload new copies.
There doesn't seem to be a `--checksum` flag like `rsync` supports.
Instead, let's just do this a really basic way:
1. download the S3 version
2. check if there's a diff
3. if so, upload the new version and emit a fedmsg
> jobs/sync-stream-metadata: use `aws s3 cp` instead of `aws s3 sync`

- deploy
Allows specifying the path to `oc`.
> deploy: add --oc-cmd argument

- jobs/kola-aws.Jenkinsfile
- jobs/kola-gcp.Jenkinsfile
- jobs/kola-openstack.Jenkinsfile
Sometimes we just want to rerun some tests only. Add a parameter to make
that easy.
> jobs/kola: add KOLA_TESTS param

- Jenkinsfile
This reverts commit 847ceb10b666df9f259d7691911eed8469382cbd.
> Revert "Jenkinsfile: temporarily don't run upgrade tests"

- HACKING.md
We're using a new token. Document where to find it and what scopes it
needs to have.
> HACKING.md: document GitHub token a bit more

- Jenkinsfile
This is helpful for debugging.
> pipeline: print coreos-assembler-git.json

- Jenkinsfile
Same rationale as b48c25553a12d7ae7752b8eaeb60e20987985720.
> Jenkinsfile: stop archiving ISO on failure

- HACKING.md
- gp.groovy
- jenkins/config/fcos-aarch64-builder.yaml
- jobs/bump-lockfile.Jenkinsfile
- manifests/jenkins.yaml
```
commit 2cb8053bd0e340de7c41e5d5d53f780acb9baba0
Date:   Mon Jul 19 17:36:47 2021 -0400
bump-lockfile: rework to get aarch64 bumping
Takes advantage of new functions in coreos-ci-lib
to execute builds/tests via GangPlank.
commit d470d12dbd154556204719b908f683138c44ff01
Date:   Mon Jul 19 17:31:32 2021 -0400
bump-lockfile: add back in sanity check
This sanity check is valid even in the timestampOnly case. Make
the if condition start later.
```
> bump-lockfile: rework to get aarch64 bumping

- jenkins/config/slack.yaml
That way it's easier to follow.
> slack: move to dedicated channel for notifications

- Jenkinsfile
- Jenkinsfile.release
Add support for an ARCHES parameter that is a space spearated string
of architectures for us to target for the given build ID.
Add a loop over the architecture list where it makes sense.
> Jenkinsfile.release: support ARCHES parameter

- utils.groovy
Right now it tries to guess the name of the buildconfig based on
the name of the job that's being run. With the introduction of the
multi-arch pipeline there is no BuildConfig that backs the job, so
we'd have to do heuristics to find the main pipeline job name.
Instead of doing that let's just assume that there's only one
BuildConfig in the project with the needed information and use that
so that it doesn't matter what jenkins job we're running we can
still find the information we're looking for.
> utils.groovy: update get_annotation() to be job independent

- jobs/multi-arch-pipeline.Jenkinsfile
This adds the metal artifacts as well as the openstack image.
> multi-arch-pipeline: start building other artifacts for aarch64

- jobs/multi-arch-pipeline.Jenkinsfile
This allows us to archive the logs and also check for failures at
the end of the run. Unfortunately this does mean we don't get a quick
failure as the results will only get checked at the very end.
> multi-arch-pipeline: check for failures and archive kola logs

- jobs/kola-aws.Jenkinsfile
- jobs/kola-gcp.Jenkinsfile
- jobs/kola-openstack.Jenkinsfile
```
commit 321deedca986ea31833747a8127185f71692bb0c
Date:   Wed Sep 22 16:32:01 2021 -0400
kola-{aws,gcp,openstack}: send slack message on failure
commit 55df587cdb1682647df8bae94a038d552101278c
Date:   Wed Sep 22 16:27:34 2021 -0400
kola-openstack: fix comment about instance type
Should have been done in 27cab80.
commit aae3dd46e6a6c436d96b9b1a87d46374c6ececc3
Date:   Wed Sep 22 16:17:17 2021 -0400
kola-openstack: add a parameter for architecture
Will allow us to test aarch64 openstack images.
```
> kola-{aws,gcp,openstack}: enhancements

- jobs/kola-aws.Jenkinsfile
- jobs/kola-gcp.Jenkinsfile
- jobs/kola-openstack.Jenkinsfile
The $params.ARCH variable wasn't properly accessed.
> kola-{aws,gcp,openstack}: fix slack message

- Jenkinsfile
- jobs/kola-aws.Jenkinsfile
- jobs/kola-gcp.Jenkinsfile
- jobs/kola-openstack.Jenkinsfile
- jobs/multi-arch-pipeline.Jenkinsfile
Makes it more clear that it's specifically a commit from
https://github.com/coreos/fedora-coreos-config.
> Rename `CONFIG_GIT_COMMIT` parameter to `FCOS_CONFIG_COMMIT`

- Jenkinsfile
To help debug
https://github.com/coreos/fedora-coreos-tracker/issues/1003.
> pipeline: add some debugging info re. umask and permissions

- jobs/multi-arch-pipeline.Jenkinsfile
We currently have a limitation where we aren't building and
pushing multi-arch COSA containers to quay. For multi-arch
we're currently building images once a day on the local
multi-arch builders. See https://github.com/coreos/coreos-assembler/issues/2470
Until `#2470` is resolved let's do the best thing we can do
which is derive the multi-arch container name from the
given x86_64 COSA container. We'll translate
`quay.io/coreos-assembler/coreos-assembler:$tag -> localhost/coreos-assembler:$tag`
This assumes that the desired tagged image has been built
on the multi-arch builder already, which most likely means
someone did it manually.
Fixes https://github.com/coreos/fedora-coreos-pipeline/issues/423
> multi-arch-pipeline: derive the COSA image from params.COREOS_ASSEMBLER_IMAGE

- manifests/pipeline.yaml
> manifest/pipeline: fix local -> Local casing

- Jenkinsfile
- jobs/bump-lockfile.Jenkinsfile
- jobs/multi-arch-pipeline.Jenkinsfile
Reruns have been disabled by default. Lets add the flag to turn
them on in the pipeline.
> Jenkinsfile: add rerun flag

- Jenkinsfile
related to https://github.com/coreos/coreos-assembler/pull/2573
> pipeline: ship Nutanix

- Jenkinsfile
- jobs/multi-arch-pipeline.Jenkinsfile
Otherwise it'll think it's not official.
> [fedora-migration] jobs: consider stg Fedora infra Jenkins as prod

- README.md
Need to find the way to get access and update this PR with that info too.
> README: Update link to the current production CI

- jobs/kola-openstack.Jenkinsfile
This removes the manual steps of parsing the json and uncompressing
the image.
> kola-openstack: use cosa decompress and cosa meta

- manifests/jenkins.yaml
This is already done in-cluster, just reflecting it back in Git.
> manifests/jenkins: bump PVC to 20Gi

- HACKING.md
- README.md
- utils.groovy
> More tweaks and one fix

- jobs/build.Jenkinsfile
Somehow missed this on: https://github.com/coreos/fedora-coreos-pipeline/pull/466
> jobs/build: Update number of logs and artifacts to keep

- jobs/bump-lockfile.Jenkinsfile
Testing a lockfile bump takes time. By the time we're ready to push out
an update, a new commit might've been pushed upstream which we haven't
tested. Detect that case and instead of erroring out, retrigger
ourselves.
See also: https://github.com/coreos/fedora-coreos-pipeline/pull/481
> jobs/bump-lockfile: self-retrigger on races

- jobs/build.Jenkinsfile
We want this knob to work even if the command itself failed and not just
the test.
> jobs/build: strengthen ALLOW_KOLA_UPGRADE_FAILURE

- jobs/release.Jenkinsfile
Fixes 8a1301d17e12 ("jobs: only run release job once per build").
> jobs/release: fix extra locks creation

- jobs/build.Jenkinsfile
> jobs/build: correct variable name for GCP storage bucket info

- jobs/bump-lockfile.Jenkinsfile
It turns out that we were properly updating the aarch64 lockfile
in the fetch but we weren't actually sending that to the remote
builder when doing the build/test pieces. This meant the aarch64
tests in bump-lockfile were essentially always testing what was
in git and not the updated lockfiles. Let's forward the changes
to the remote builder.
I had to use patch here because there isn't an easy way to forward
arbitrary files via gangplank so this was just a way to do it.
Also note that originally I tried a different way to apply the patch
like `git apply <(base64 -d <<< 'abcdefg..')` but that fails to render
properly because `<` and `>` get turned into `&lt `and `&rt `because
we are using html templating on the backend in gangplank.
I also took this as an opportunity to break out and call …
> jobs/bump-lockfile: send lockfile updates to aarch64 builder

- jobs/kola-aws.Jenkinsfile
Fixes: https://github.com/coreos/fedora-coreos-pipeline/issues/530
> kola-aws.Jenkinsfile: add testing for new aws c7 instances

- jobs/bump-lockfile.Jenkinsfile
add steps to the bump-lockfile job for s390x
> bump-lockfile job for s390x

- jobs/bump-lockfile.Jenkinsfile
Let's `git add` the lockfiles earlier so that the patch for the new
architecture gets delivered to that builder too. If we don't do that
then the `cosa fetch --strict` and `cosa build --strict` will fail.
> jobs/bump-lockfile: git add earlier

- jobs/build.Jenkinsfile
- QEMU and QEMU upgrade tests
- keylime hashlist generation and building the qemu image
- Uploading to Clouds (AWS/GCP)
- Kicking off Cloud Provider test jobs
> jobs/build: parallelize some stages

- jobs/build.Jenkinsfile
This allows for in pipeline debugging without worrying about pushing
artifacts over multiple debug runs.
> jobs/build: Add NO_UPLOAD parameter to allow for debugging

- jobs/build.Jenkinsfile
Needed a closing parenthese.
Fixup for 45af871
> jobs/build: fix typo in conditional logic

- jobs/build.Jenkinsfile
Needed another closing parenthese.
Fixup for 45af871
> jobs/build: fix another typo in conditional logic

- jobs/build.Jenkinsfile
Missed it when adding `uploading` condition.
Fixup for 45af871
> jobs/build: add missing && operator

- jobs/build.Jenkinsfile
This allows us to take the (Metal{,4k})->Live ISO serial run and
collapse it into the two runs of parallel builds we were doing for all
the other platforms, which will save us time.
> jobs/build: collapse Metal/Metal4k/Live ISO builds into builds for other platforms

- jobs/build.Jenkinsfile
These two don't depend on one another and don't modify the metadata
files so we should fine running them in parallel.
> jobs/build: use parallel for 'Sign Images' and 'OSTree Import' stages

- jobs/build-arch.Jenkinsfile
We need to take the release lock first before the build lock so that
even if a build for the given stream is pending, we still make sure the
release job waits until we finish.
Add some details about the theoretical race condition that exists while
we're here.
Reported-by: Dusty Mabe <dusty@dustymabe.com>
> jobs/build-arch: take build-specific release lock first

- jobs/bump-lockfile.Jenkinsfile
Also includes a commits to rework the structure to loop more.
```
commit 9f0fdfde7bfed8cbf447954236af83e7484a7c33
Date:   Fri Jul 22 13:59:44 2022 -0400
jobs/bump-lockfile: more deduplication
Put the fetach build and tests into a loop as well. Almost all
of the code is the same except for the testiso bits which I've
added conditional logic to.
commit c309e52620939ae59018f663f79e17999a09bc92
Date:   Fri Jul 22 13:18:20 2022 -0400
jobs/bump-lockfile: use new --find-build-for-arch buildfetch option
Right now the latest build in a stream could have failed the secondary
architectures runs and have missing arches. This causes the `cosa build`
to fail because it tries to read the meta data for the latest build
but …
```
> jobs/bump-lockfile: fix builds when missing architectures

- jobs/bump-lockfile.Jenkinsfile
> jobs/bump-lockfile: fix typo

- jobs/bump-lockfile.Jenkinsfile
> jobs/bump-lockfile: fix more typos

- HACKING.md
- jenkins/config/cosa-push-registry-secret.yaml
- jenkins/config/fcos-x86-64-builder.yaml
- jobs/build-arch.Jenkinsfile
- jobs/build-cosa.Jenkinsfile
- jobs/build-mechanical.Jenkinsfile
- jobs/bump-lockfile.Jenkinsfile
- manifests/jenkins.yaml
- multi-arch-builders/README.md
- multi-arch-builders/builder-common.bu
- multi-arch-builders/fcos-x86_64-builder.bu
- streams.groovy
- utils.groovy
Closes: https://github.com/coreos/fedora-coreos-tracker/issues/1027
> Add build cosa job

- deploy
- manifests/jenkins-agent.yaml
> Add triggers to jenkins-agent BuildConfig and fix disabling S3

- jobs/release.Jenkinsfile
> jobs/release: add JENKINS_AGENT_IMAGE_TAG replacement

- jobs/build-cosa.Jenkinsfile
We need to be able to rebuild the same cosa commit e.g. if a package
changed. (This would be a nice benefit of using lockfiles for cosa too.)
> jobs/build-cosa: add `FORCE` parameter

- jobs/build-arch.Jenkinsfile
- jobs/build.Jenkinsfile
- jobs/bump-lockfile.Jenkinsfile
This function takes a string as the argument, not an Exception object.
> fix calls to error()

- jobs/build-cosa.Jenkinsfile
Was trying to do a test build and this was throwing me off.
> jobs/build-cosa: use git url from parameters

- jobs/bump-lockfile.Jenkinsfile
Let's give the cosaPod more CPUs by default. It changed recently
to limiting the job to just 2 by default and we need more than that
to cut down on flakes.
Also, let's stitch in the separation of reprovision tests so that
they run serially.
> jobs/bump-lockfile: add some updates from build job

- jobs/bump-lockfile.Jenkinsfile
> jobs/bump-lockfile: fix syntax error

- jobs/build-cosa.Jenkinsfile
- streams.groovy
Things should be in place now for this to start working. Let's find
what's broken!
> enable ppc64le in streams.groovy

- manifests/sleep.yaml
> manifests/sleep.yaml: drop AWS secrets from pod, add KVM, and an `/srv` emptyDir

- streams.groovy
Now that F37 has branched from rawhide we'll start building the
branched stream again.
> streams: enable branched stream

- jobs/build-arch.Jenkinsfile
- jobs/build.Jenkinsfile
We want to get some testing on rawhide/branched so let's enable
this. We're working on garbage collection so we'll be cleaning these
up aggressively in the future too.
> enable cloud uploads/tests on mechanical streams

- jobs/bump-lockfile.Jenkinsfile
Sometimes we have flakes. If 3 architectures pass tests and one flakes
we shouldn't need to re-run the 3 passing arches on a re-run of the
job. Allow the operator to selectively skip running tests on
architectures where they know the tests have already passed.
> jobs/bump-lockfile: add option for skipping tests on arches

- jobs/release.Jenkinsfile
This switches to `cosa push-container-manifest`, which is aware of how to find all the ostree containers for the different architectures, create a manifest list out of them and push that up to quay.
> jobs/release: upload the oscontainer for all architectures

- jobs/kola-azure.Jenkinsfile
In the yaml config it's under clouds.azure.test_*.
Fixes e66dec6
> jobs/kola-azure: fix variable reference

- jobs/build.Jenkinsfile
> jobs/build: fix typo in stage definition

- HACKING.md
- deploy
Also remove docs for `deploy --bucket`.
Fixup for e66dec6
> remove `deploy --config`; update HACKING

- jobs/build-arch.Jenkinsfile
- jobs/build.Jenkinsfile
- jobs/kola-aws.Jenkinsfile
- jobs/kola-azure.Jenkinsfile
- jobs/kola-gcp.Jenkinsfile
- jobs/kola-kubernetes.Jenkinsfile
- jobs/kola-openstack.Jenkinsfile
- jobs/release.Jenkinsfile
- utils.groovy
We need the ref override logic everywhere that wants to clone the repo.
> jobs: get source config ref using new helper

- jobs/build-arch.Jenkinsfile
- jobs/build.Jenkinsfile
- jobs/release.Jenkinsfile
- utils.groovy
It was upstreamed in https://github.com/coreos/coreos-ci-lib/pull/117.
> tree: use `tryWithCredentials` from coreos-ci-lib

- utils.groovy
This was added to coreos-ci-lib in
https://github.com/coreos/coreos-ci-lib/pull/119.
> utils: use new substituteStr function for source_config

- config.yaml
- docs/config.yaml
- jobs/build-arch.Jenkinsfile
- jobs/build.Jenkinsfile
- jobs/release.Jenkinsfile
- uploads.groovy
This picks up #672 from @ravanelli and adds in fixups/restructure. Tested in the staging pipeline.
> Add upload_to_clouds function

- jobs/build-arch.Jenkinsfile
- jobs/build.Jenkinsfile
Now if you are hacking on the pipeline you can just edit the config.yaml to comment out whatever you don't want. Let's drop the concept of a minimal run now that it's much more flexible to edit the config.yaml.
> jobs/{build,build-arch}: drop concept of minimal run

- config.yaml
These are additional containers we need to ship in RHCOS. Add them.
Requires: https://github.com/coreos/coreos-assembler/pull/3133
Requires: https://github.com/coreos/fedora-coreos-pipeline/pull/710
> [rhcos] config.yaml: build legacy-oscontainer and extensions-container

- jobs/release.Jenkinsfile
For the Push Container stage we need to have all of those artifacts
actually fethed to the local pod. Because of the way buildfetch works
(stomping on meta.json) we need to run the fetch of the artifacts before
any stages that modify/update the meta.json file. Let's add a new stage
that will handle this for us before any of the later stages that modify
meta.json.
> jobs/release: add Fetch Artifacts stage

- HACKING.md
- deploy
- docs/config.yaml
- jobs/build-arch.Jenkinsfile
- jobs/build-cosa.Jenkinsfile
- jobs/build-fcos-buildroot.Jenkinsfile
- jobs/build.Jenkinsfile
- jobs/bump-lockfile.Jenkinsfile
- jobs/kola-aws.Jenkinsfile
- jobs/kola-azure.Jenkinsfile
- jobs/kola-gcp.Jenkinsfile
- jobs/kola-kubernetes.Jenkinsfile
- jobs/kola-openstack.Jenkinsfile
- jobs/release.Jenkinsfile
- manifests/pipeline.yaml
- manifests/sleep.yaml
- utils.groovy
> Replace coreos-assembler ImageStream by new knobs in the pipecfg

- jobs/release.Jenkinsfile
On RHCOS 4.11 and older, we will have the legacy oscontainer and the OSTree archive but we only want to push the former. Hack around this by detecting whether the legacy-oscontainer was built and skipping the `ostree` artifact fetch and push.
Fixes fa256df ("jobs/release: put new oscontainer under `oscontainer` key").
Co-authored-by: Dusty Mabe <dusty@dustymabe.com>
> jobs/release: fix legacy-oscontainer handling

- utils.groovy
> utils: remove extraneous bracket for function

- jobs/build-cosa.Jenkinsfile
> jobs/build-cosa: remove extraneous bracket

- jenkins/config/slack.yaml
- jobs/build-arch.Jenkinsfile
- jobs/build-cosa.Jenkinsfile
- jobs/build-fcos-buildroot.Jenkinsfile
- jobs/build.Jenkinsfile
- jobs/bump-lockfile.Jenkinsfile
- jobs/kola-aws.Jenkinsfile
- jobs/kola-azure.Jenkinsfile
- jobs/kola-gcp.Jenkinsfile
- jobs/kola-kubernetes.Jenkinsfile
- jobs/kola-openstack.Jenkinsfile
- jobs/release.Jenkinsfile
- utils.groovy
Requires: https://github.com/coreos/fedora-coreos-pipeline/pull/737
> Drop `official` conditional on `slackSend` and make Slack room more configurable

- HACKING.md
- config.yaml
- deploy
- docs/config.yaml
- jobs/build-arch.Jenkinsfile
- jobs/build.Jenkinsfile
- jobs/cloud-replicate.Jenkinsfile
- jobs/release.Jenkinsfile
- jobs/sync-stream-metadata.Jenkinsfile
- utils.groovy
> Drop `--official` flag, support `ADDITIONAL_ARCHES = none`, and support setting S3 ACL

- docs/config.yaml
- jobs/build-arch.Jenkinsfile
- jobs/build.Jenkinsfile
We're working on unwinding the yumrepos hack but doing it stream by stream. So we need to be able to progressively not apply the workaround as we go.
> Make yumrepos workaround a stream-level hack

- HACKING.md
For some reason, sometimes the token secret isn't in the `oc get sa` output. Instead, we need to do what `oc describe sa` does and filter the list of secrets by type and name and uid to get the list of token secrets we can use.
I know the `jq` command there is a mouthful. There is a shorter `oc describe | grep | cut` version available but I'd like this to also serve as documentation for how a compiled tool could e.g. fetch the list of secrets itself and do the same filtering that we do here with `jq` without resorting to hacky string manipulations.
> HACKING.md: tweak remote triggering instructions

- jobs/build-cosa.Jenkinsfile
This reverts commit 39f69e0 and ad500a8.
We are no longer using/experimenting with the rhcos-4.x-new branches so we don't need this any longer.
> Revert "jobs/build-cosa: add in hack for build COSA against dev 4.X branches

- jobs/release.Jenkinsfile
Use the new exit code added in
https://github.com/coreos/coreos-assembler/pull/3277 to detect the case where some regions are down. If that happens, continue with the release, but issue a warning, which will mark the build as unstable.
> jobs/release: don't block release if some AWS regions are down

- jobs/build.Jenkinsfile
- jobs/release.Jenkinsfile
I.e. https://github.com/coreos/coreos-ci-lib/pull/138.
> jobs: use new `warn()` helper from coreos-ci-lib

- jobs/bump-lockfile.Jenkinsfile
The initial step to moving RHCOS to use lockfiles.
> bump-lockfile: Update base-url to get builds and artifacts from s3 bucket

- jobs/bump-lockfile.Jenkinsfile
For remote builders we need to forward the credential to the remote and have it loaded that way. It turns out we have a helper for this in our utils.groovy library so let's just use it. Fixup for d5db023.
Without this we see an error like the following for the remote builders:
```
[2023-01-24T20:52:22.844Z] botocore.exceptions.NoCredentialsError:
Unable to locate credentials
```
> jobs/bump-lockfile: fix AWS credential usage for remote builders

- config.yaml
> config.yaml: fix whitespace

- jobs/build.Jenkinsfile
In the case that we are re-running a mArch job I'd prefer we "wait" so that if the mArch job fails we don't re-run the release job.
> jobs/build: wait when re-running mArch jobs

- HACKING.md
- jenkins/controller/plugins.txt
- manifests/jenkins.yaml
- Add the splunk plugging needed in order to be compliant with ProdSec
> jenkins: Add splunk plugins

- config.yaml
Ref: https://github.com/coreos/fedora-coreos-tracker/issues/1126#issuecomment-1452628138
> config: Start producing kubevirt artifact for x86_64

- jobs/build-arch.Jenkinsfile
This will test qemu-secex artifact on s390x bulder machine.
> jobs: add kola-secex test

- jobs/build.Jenkinsfile
See: https://github.com/coreos/fedora-coreos-tracker/issues/1185
> jobs/build.Jenkinsfile: Implement koji-tagger delay work around

- config.yaml
Part of https://github.com/coreos/fedora-coreos-tracker/issues/1411
> config: start building hyperv image

- jobs/release.Jenkinsfile
- Validate if  the build was tagged, if not, try to tag it again.
> Update release job to reflect changes done in koji

- config.yaml
As F39 has branched from rawhide, we are building the branched stream again
> config: enable branched stream

- config.yaml
- next-devel/badge.json
- next-devel/status.json
Enabling next-devel for:
https://github.com/coreos/fedora-coreos-tracker/issues/1490
> config: enable next-devel

- jenkins/controller/plugins.txt
This plugin will allow us to interact with fedmsgs in various ways more easily (notably triggering jobs on messages and sending messages).
> plugins: add jms-messaging

- jenkins/controller/plugins.txt
Update all Jenkins plugins to their latest versions.
> jenkins/plugins: update plugins to latest versions

- multi-arch-builders/provisioning/aarch64/README.md
- Add more information in how to create more resources with diferent names.
> multi-arch-builders: Update README

- docs/config.yaml
- jobs/build-arch.Jenkinsfile
- jobs/build.Jenkinsfile
- jobs/bump-lockfile.Jenkinsfile
- jobs/debug-pod.Jenkinsfile
- utils.groovy
Relies on https://github.com/coreos/coreos-ci-lib/pull/157
> support setting pipeline env vars from the config

- config.yaml
Part of https://github.com/coreos/fedora-coreos-tracker/issues/1653
> config: start building using OSBuild in rawhide

- config.yaml
- docs/config.yaml
To help with testing
https://github.com/coreos/fedora-coreos-tracker/issues/1594.
> config.yaml: build `vmware` on aarch64 on rawhide

- HACKING.md
- docs/config.yaml
- jobs/build-arch.Jenkinsfile
- jobs/debug-pod.Jenkinsfile
- jobs/release.Jenkinsfile
- cosa_controller_img_hack
- oscontainer_old
- legacy_oscontainer_old
> drop support for hacks associated with old RHCOS releases

- jobs/build-podman-os.Jenkinsfile
- Ajust the job trigger to run daily instead of repo changes
> build-podman-os: Change trigger to run daily jobs

- jobs/build-podman-os.Jenkinsfile
This changed form with https://github.com/coreos/coreos-assembler/pull/3652
> jobs/build-podman-os: adapt basic kola tests

- jobs/build-kola-containers.Jenkinsfile
The skopeo call to check for changes was running outside of cosa where the binary is not available. This only started to cause issues recently somehow
> jobs/build-kola-containers: Call skopeo from cosa

- jobs/bump-jenkins-plugins.Jenkinsfile
> bump-jenkins-plugins: update git command text

- jobs/bump-jenkins-plugins.Jenkinsfile
To address the issue of local branch and origin/JenkinsPluginsUpdate getting diverged, we updated the Read Plugins.txt stage to read the `plugins.txt` from the `main` branch.
> jobs/bump-jenkins-plugins: read plugins from 'main' branch

- jenkins/controller/plugins.txt
- utils.groovy
See https://github.com/coreos/coreos-ci/pull/55
> utils: add helper to send matrix messages through maubot

- jobs/build-podman-os.Jenkinsfile
- Reflect changes done in https://github.com/coreos/coreos-assembler/pull/3808
> jobs: Reflect changes done in cosa for osbuild

- gc-policy.yaml
- jobs/garbage-collection.Jenkinsfile
- utils.groovy
Added GC job which will be triggered from the release job for a given stream and will perform pruning operations based on `gc-policy.yaml` file
> jobs/garbage-collection: Add Garbage Collection job to the pipeline

- jobs/garbage-collection.Jenkinsfile
Add `acl` argument to the cosa cloud-prune command. Also, update the run's description after completion.
> jobs/garbage-collection: Add `acl` arg and update run description

- HACKING.md
- docs/s3-bucket-versioning.md
Add tutorial with detailed steps for creating and configuring a versioned S3 bucket, including lifecycle rules for managing versions and delete markers.
> Add steps to create and configure a versioned S3 bucket

- jobs/kola-aws.Jenkinsfile
- jobs/kola-openstack.Jenkinsfile
Let's execute GC steps for `kola-aws` and `kola-openstack` runs.
> Add GC step for AWS and Openstack jobs

- gc-policy.yaml
Expand the Garbage Collection to all streams available for FCOS.
> gc-policy: Expand GC to all streams

- jobs/release.Jenkinsfile
- utils.groovy
Refactor `load_gc` function to streamline file path handling and improve error handling, while updating the GC job trigger to check `gc_policy_data` for better clarity and robustness.
> release: Fix GC conditional check

- docs/aws-region-enable.md
The command to view the current value of quota level is added and have also updated the text template.
Also, added the information on creating the DPP ticket in case of RHCOS related requests.
> Update the aws-region ticket details

- utils.groovy
Collect all artifacts in a Set to support the `skip_disk_images` knob. This avoids Jenkins script security errors when using `intersect()`.
> utils: collect artifacts to build as a Set

- jobs/build-node-image.Jenkinsfile
- utils.groovy
Allow specifying a HOTFIX reference and url for
pipecfg.
This will always append the hotfix name to the pushed tags so we don't overwrite anything.
See https://issues.redhat.com/browse/COS-3174
> node-image-build: add HOTFIX parameters

- utils.groovy
Quay.io has periods where it's more flaky than usual when pushing. Let's just automatically retry here to make this less painful.
> utils: retry skopeo copy 5 times

- libcloud.groovy
See https://github.com/coreos/coreos-assembler/pull/4074
> libcloud: use cosa imageupload-<cloud> on newer releases

- jobs/build-node-image.Jenkinsfile
ART needs to be able to, from an x86_64 nightly, derive an s390x version of it. They used to be able to do this before the layering work by looking at the build ID, but now the source of truth is the manifest list, which is a moving target.
Enable this by adding the manifest list tag to all the built images. This feels like a layering violation of course. I think the more appropriate fix for this is to better keep track of the manifest lists used from the start when building arch-specific nightlies, but for now at least let's not break current workflows. And anyway, all this will have to be reworked for Konflux.
> jobs/build-node-image: label images with manifest list tag

- jobs/build-node-image.Jenkinsfile
- utils.groovy
- Add Brew stage in order to upload metadata to Brew.
- It will upload meta.json and extensions.json for the node layer image.
> jobs/build-node-image: Add Brew stage

- utils.groovy
- Update it to reflect changes in the pipeconfig
> utils: Change brew tag location in the pipeconfig

- utils.groovy
> utils: Fix brew tag path in pipeconfig

- config.yaml
https://issues.redhat.com/browse/OCPBUGS-54751
Add the kubevirt artifacts to s390x
> config: update kubevirt pipeline for s390x

- config.yaml
See https://github.com/coreos/fedora-coreos-tracker/issues/1652
> config: add proxmox to list of artifacts to build

- config.yaml
Ref: https://github.com/coreos/fedora-coreos-tracker/issues/1967
> config: add oraclecloud to default artifact list

- config.yaml
We have stabilized rawhide enough now to also do this on branched.
> config.yaml: switch branched to buildah path

- jobs/release.Jenkinsfile
This uses the new `cosa sign --oci` switch to sign our OCI images using the official Fedora GPG keys.
Part of https://github.com/coreos/fedora-coreos-tracker/issues/1969.
I opted for not gating this behind a knob. It's safe to do this even on streams that still use encapsulated commits (it's just files in S3). But the earlier we do it, the more overlap we have in which both signature types (OCI and OSTree) co-exist and that makes migration planning easier.
---
Requires: https://github.com/coreos/coreos-assembler/pull/4301
> jobs/release: sign OCI images

- jobs/release.Jenkinsfile
It appears that jenkins will wait until all the locks are available before taking any locks, which makes sense, but causes the desired outcome of 49e05be to not be achieved. Let's take the toplevel stream based lock first by itself so the kola-upgrade job will actually wait for the release job to finish before kicking off.
> jobs/release: take stream lock first

- libcloud.groovy
Extend `awsReplicateClosure` to accept a `winli` argument (default: false). When set, the closure will pass `--winli` to `cosa aws-replicate` so that only WinLI AMIs are replicated.
Add an additional replicator entry that invokes the closure with `winli = true`, ensuring WinLI replication is handled explicitly and kept separate from standard AMI replication.
> libcloud.groovy: support winli flag in AWS replicate closure
