coreos/fedora-coreos-pipeline

Jenkinsfile

By default, `build` will just reuse the same content it previously
fetched.

pipeline: Actually fetch new content

---

HACKING.md
manifests/bc.yaml

This makes it possible to pass custom git repos and URLs for convenience
when hacking locally.

Convert pipeline into template

---

Jenkinsfile

Otherwise, I've got a bunch of defunct qemu-kvm processes and the final
`qemu-kvm` from `virt-install` just hangs at
`reboot: Restarting system`. Not sure why prod isn't hitting this.

Jenkinsfile: use dumb-init

---

Jenkinsfile
manifests/pod.yaml

Jenkins declarative vs scripted modes are a bit confusing. In the end, I
always find the declarative mode too limiting and verbose. It is not
uncommon for plugins to only offer some features through the more
powerful scripted mode rather than declarative.
Switching over allows us to make a cleaner Jenkinsfile without the yaml
definition of the containers baked in, thus reducing further the number
of nested languages we have to deal with.
We also avoid having to always nest commands inside `steps {}` and
`container() {}`. This considerably reduces the size of the file.

pipeline: switch to scripted mode

---

Jenkinsfile
utils.groovy

The basic issue this patch is trying to fix is our overdependence on the
PVC; right now, if the PVC gets wiped, the next build will reset the
versioning and delete all the previous builds in prod.
So an easy way to fix this is simply to make sure that the PVC is in the
same state as the prod version. This should be a no-op normally, except
if the PVC got wiped.
Eventually, we should think about higher-level "release" management such
as how many builds to keep and whether to push smoketested images to
e.g. S3 or something (and instead treat artifacts.ci.centos.org/ as a
"buildmaster" pipeline), etc...

pipeline: always sync in state from prod first

---

Jenkinsfile
utils.groovy

First, learn to read what the previous build was and then skip the rsync
out stage if there are no new builds.
Second, decorate build descriptions of new builds with their build ID or
otherwise, just say no changes. This makes it easy at a glance to find
out which jobs created new builds.

pipeline: decorate builds and exit early if no changes

---

Jenkinsfile
utils.groovy

Three fixes:
- First, `test -f builds/latest` will always fail because either it
doesn't exist, or it does but it's a symlink, whereas `test -f` checks
that it's a file.
- Second, `shwrap_rc()` returns the exit code. But in shell semantics, 0
means successful, so the if-statement actually had an opposite logic.
Of course taken together those two issues meant two negatives became a
positive and it *seemed* like it worked when testing locally... So
evil.
- Third, when checking for the SSH key, we were still using
`fileExists()` which is broken inside Kubernetes containers.
So let's create a dedicated `path_exists()` which fixes all of this and
lowers the chances of getting this wrong again in the future. Note we
use `test -e` here to more closely match `fileExists()` (which really
doesn't …

pipeline: minor logic fixes with fileExists

---

HACKING.md
manifests/pipeline.yaml

The only thing that really changes is the default `REPO_URL` parameter.

pipeline: adjust for repo move and rename

---

utils.groovy

We don't need every OSTree object synced in or out printed. That makes
the build logs a bit too spammy. Let's just settle for `--stats`, which
prints all the interesting info (e.g.  number of files created, total
sizes, total bytes sent, etc...

utils: don't use rsync -v, just use --stats

---

Jenkinsfile

Right now, the pipeline is only ever triggered manually. Let's fire up
the engine here and start churning out builds at a regular interval. We
can reconsider turning this off down the line if we have sufficient
"push triggers" to safely disable the timer.
This makes use of the new devel flag that was added in the previous
patch.

pipeline: run every 30 minutes

---

Jenkinsfile

Make use of the new `compress` command in coreos-assembler to compress
the artifacts before syncing out.
Closes: #14

pipeline: compress artifacts

---

Jenkinsfile

Let's not keep only the last 3 builds here. That default is really to
appeal for the local dev case. I'm working towards adding a
`prune --keep-younger-than` switch to make it time based instead but for
now let's keep say... 15 builds so there's some semblance of permanence.

pipeline: prune less aggressively

---

HACKING.md

Followup to #26  to properly override the docker unit in `/etc`.
I did try `systemctl edit docker.service` and placing the following in:
```
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd-current \
--add-runtime oci=/usr/libexec/docker/docker-runc-current \
--default-runtime=oci \
--authorization-plugin=rhel-push-plugin \
--containerd /run/containerd.sock \
--exec-opt native.cgroupdriver=cgroupfs \
--userland-proxy-path=/usr/libexec/docker/docker-proxy-current \
--init-path=/usr/libexec/docker/docker-init-current \
--seccomp-profile=/etc/docker/seccomp.json \
$OPTIONS \
$DOCKER_STORAGE_OPTIONS \
$DOCKER_NETWORK_OPTIONS \
$ADD_REGISTRY \
$BLOCK_REGISTRY \
$INSECURE_REGISTRY \
$REGISTRIES
```
However, the routing error still showed in `oc status`, so it did not seem like the override took …

HACKING: Add systemd override correction and minor notes

---

Jenkinsfile

It's `--keep`, not `--keep-last-n`. (Though the underlying script that
does the work uses `--keep-last-n`.)

pipeline: fix `prune` invocation

---

Jenkinsfile

Otherwise, we'll just hit ENOSPC eventually. rpm-ostree doesn't/can't
know what it should delete since (not surprisingly) the cache is meant
to cache packages that may be used in the next compose.
We could try to be smart and e.g. only keep the latest NEVRA of all
packages, etc... but for now let's just let rpm-ostree re-download and
import it all once in a while. It's good to exercise the import code too
since it can subtly change between rpm-ostree versions.

pipeline: nuke cache.qcow2 once it grows past 8G

---

Jenkinsfile

When testing #39, I had only tested that the qcow2 gets nuked. The
issue is that the *next* build will error out since it expects the qcow2
to already be created.
Simply switch to always running `coreos-assembler init --force` since
it's idempotent anyway so it'll only recreate the qcow2 if it was nuked
in the previous run.

pipeline: re-create cache.qcow2 after nuking it

---

Jenkinsfile

Let's get these images out there for people to try.

Build metal-bios and metal-uefi

---

Jenkinsfile

Start using the new `buildextend-installer` command from:
https://github.com/coreos/coreos-assembler/pull/306

pipeline: start building installer ISOs

---

manifests/pipeline.yaml
manifests/pod.yaml
manifests/sleep.yaml

Brian created us a new PVC and the claim has a new name because
we needed the other one around while we copied it over.

pvc: use coreos-assembler-claim2 in centos CI

---

HACKING.md
manifests/pipeline.yaml

Allow developers to easily customize it if they don't have 100Gi to
spare.

pipeline: make PVC_SIZE a template parameter

---

HACKING.md

There are minor inconsistencies otherwise between the CLI and the
server. E.g. `new-app` will fail to find templates on v3.9. Or editing
some aspects of imagestreams will fail if not with v3.6.1.

HACKING.md: match v3.6.1

---

Jenkinsfile

Just so we're explicit, and to help debugging the pipeline.

pipeline: also echo something when in prod mode

---

manifests/pipeline.yaml

The switch to quay.io was a little premature here. The latest image is
for now only available from the previous location. Let's bump again to
v2.164.2, which is the latest LTS release.
This also fixes an issue with login which affected the previous
image[1], which somehow only manifested itself in prod.
[1] https://github.com/openshift/jenkins/issues/786

Bump Jenkins to v2.164.2

---

Jenkinsfile

Don't rsync `repo/` back and forth anymore since it's no longer used in
the latest cosa:
https://github.com/coreos/coreos-assembler/pull/515

pipeline: stop rsync'ing OSTree repo

---

Jenkinsfile
manifests/pod.yaml

These are split out of #59 and should be straightforward to review. The first two have no impact on the current pipeline. The last one slightly modifies how initialization is performed.

Prep patches for S3 & devel

---

HACKING.md
Jenkinsfile
manifests/pipeline.yaml

This is a first step towards switching to S3. We still rsync to the
artifact server, but we also upload new builds to S3. Once we confirm
this works nicely, we can switch over to using `buildprep` and
completely wean off the artifact server.
---
Requires: https://github.com/coreos/coreos-assembler/pull/527
I tested this from my local cluster and it works, though I'm also working on #57 to make it easier to test changes like these.

pipeline: upload builds to S3

---

Jenkinsfile

When testing pipeline and/or cosa changes, one sometimes wants to run
through the whole thing even if nothing changed in the input.

pipeline: add FORCE parameter to force rebuild

---

HACKING.md
Jenkinsfile
devel-up
manifests/pipeline.yaml
manifests/pod.yaml
utils.groovy

So, a lot happening in this patch, but essentially the idea is:
1. add some more parameters to the template to support "devel" resources
2. add annotations to the pipeline buildconfig to allow us to pass data
to the pipeline code; update the pipeline to pick this up
3. allow uploading to S3 in devel mode using the provided devel prefix
4. add a new `devel-up` utility to make it easier and safer to create
and update devel pipelines; no way to delete them yet, will do that
in a follow up
The reason for the `devel-up` utility is that I wanted more "semantic"
control over the way devel resources are created than through directly
using parameters, especially around ensuring that they absolutely do not
modify prod resources. But also, it's much more convenient to use than
overriding each param …

Add support for developer pipelines

---

Jenkinsfile

Now that we have a prod build in S3, we can fully switch over to it.
Most of the changes are straightforward. One note of interest: the
"pruning" stage is now really just about pruning the local cache. For
now, we're not pruning from the bucket at all, pending a more defined
policy & mechanism.

pipeline: fully move to S3

---

manifests/sleep.yaml

Useful for debugging s3 issues.

manifests/sleep: update sleep container to have aws creds

---

HACKING.md
manifests/pipeline.yaml

This allows for someone running in a different namespace/project
than `fedora-coreos`.

manifests/pipeline: remove namespace params from template

---

HACKING.md
manifests/pipeline.yaml

Update the docs so that we can be more compatible with latest templates.
We update the input ImageStreamTag for our jenkins deployment to match
latest openshift (`jenkins:2`)
related: https://github.com/coreos/fedora-coreos-pipeline/pull/32

Update docs so we can use jenkins:2

---

HACKING.md

We recently started uploading artifacts to s3. Let's add a note to the
docs about creating a secret in openshift with that information.

HACKING: add note about creating aws credentials secret

---

Jenkinsfile

When I was testing the `/.aws` directory existed even if
the secret didn't exist (not sure why). Changing this to
`/.aws/config` seems to work.

Jenkinsfile: fix detection of aws config

---

devel-up
manifests/pipeline.yaml

This will shortly be the default branch in the repo.

pipeline: switch default branch to testing-devel

---

HACKING.md
Jenkinsfile
utils.groovy

I think we should stop using `/srv` as a workdir entirely and just
always build in the workspace. The core issue here is that (1) we want
to be able to have concurrent builds, and (2) a cosa workdir can't be
easily shared today. This also simplifies the devel vs prod logic quite
a bit since it had some funky conditionals around this.
So then, how can developers without S3 creds actually *access* built
artifacts? We simply archive them as part of the build. This is in line
also with #31, where we'll probably be archiving things anyway.
Finally, how *can* we use the PVC as cache in a safe way shareable
across all the streams? I see two options offhand:
1. as a local RPM mirror: add flags and logic to `cosa fetch` to read &
write RPMs in `/srv`, hold a lock to regen metadata
2. as a pkgcache …

pipeline: stop using /srv as workdir

---

deploy

otherwise in `--official` mode you see:
```
Traceback (most recent call last):
File "./deploy", line 235, in <module>
sys.exit(main())
File "./deploy", line 35, in main
resources = process_template(args)
File "./deploy", line 134, in process_template
params += params_from_git_refspec(args.pipeline, 'PIPELINE_REPO')
UnboundLocalError: local variable 'params' referenced before assignment
```

deploy: fix referenced before assignment bug

---

HACKING.md
deploy

I now understand better the difference between `oc apply` and `oc
replace`. The former accepts partial specs and is capable of updating
just parts of the objects, similar to a patch.  Whereas `oc replace`
will completely replace the object.
Here we want the latter. E.g. if we drop out a field from a list, we
also want it to drop out of the object on the next `./deploy`. Our
manifest should be canonical.

deploy: use `oc replace` instead of `oc apply`

---

streams.groovy

I actually wanted to have "blocking" semantics from the beginning, but
abandoned on that when switching away from the `build` step. And I
didn't think to try `oc start-build --wait`. There's `--follow` too, but
it doesn't work with Jenkins pipelines.
We can probably improve on this in the future by capturing the build
name, and printing a link to the Jenkins console for that build.

streams: use `--wait` so we wait and report errors if downstream fails

---

HACKING.md
Jenkinsfile
utils.groovy

Now that we have S3 uploads set up, let's stop the "compat" rsync'ing to
the artifact server. Instead, I propose we leave a single file there
which points people to https://builds.coreos.fedoraproject.org/browser.
Once we're officially in preview mode, we can evaluate whether we should
make the above less accessible, or perhaps simply dropping the prod
streams from the dropdown.

pipeline: stop rsync'ing to artifact server completely

---

HACKING.md

Add a note on running oc rootless while Docker by default requires
root, which tripped me up at first coming back to this.

HACKING.md: add note on running oc rootless

---

Jenkinsfile.production

In the short-term, we'll be triggering production (i.e. `testing`)
builds manually. Other streams are unaffected (`testing-devel` and
`bodhi-updates`).
This is so that we can manually drive versioning for the time being
until we have something automated in place.

production: disable all triggers for now

---

Jenkinsfile

Adds a step which downloads the `fedora-coreos-releng-automation` repo
and runs the `coreos-meta-translator` against the current build to
produce `release.json` files.

Jenkinsfile: add step for building release metadata

---

README.md

Align instructions with the actual process, and make them more explicit.

doc: document getting access to Jenkins

---

Jenkinsfile

Add a temporary `VERSION` parameter that will allow us to manually input
the version we want for `testing` builds. This will be used in the
short-term for releasing FCOS preview.

pipeline: add VERSION job parameter

---

Jenkinsfile

We shouldn't need this anymore. All streams have now migrated to the new
layout.

Jenkinsfile: drop `|| true` hack

---

Jenkinsfile

Adds a publish step for official builds that runs plume against the
version/stream. This will modify all object ACLs for the given build to
be public-read and create or modify the releases.json metadata index.
Requires coreos/coreos-assembler#606

Jenkinsfile: add Publish step

---

Jenkinsfile

We're already running inside the container, where `plume` is already in
the path, so we don't need to go through `cosa shell` for it.
I don't think that's the root cause of
https://github.com/coreos/mantle/issues/1023, but worth doing
regardless.

Jenkinsfile: call plume directly

---

Jenkinsfile

We already run `test -e` against this hard-coded path, switch the plume
call to using it directly as well.

Jenkinsfile: directly reference aws creds location

---

Jenkinsfile

There are a few undesirable things in here, but it will do for now. E.g.
we're not replicating across multiple regions, nor are we uploading
separate vmdks.
There's a lot of stuff around this that the RHCOS team has internally.
We should look to upstreaming it into cosa (or replacing it with
existing functionality in mantle and extending as necessary), so that it
can be shared with FCOS.
For now, we're just patching things together so we at least have
`us-east-1` for preview.

Jenkinsfile: start uploading AMIs

---

Jenkinsfile

There's no way to verify right now either that the artifacts were
corrupted during uploads or tampered with. The right solution for this
is signing (see [1]), but until then, let's at least upload a CHECKSUMS
file for the former, and display it in the Jenkins logs as a temporary
hack for the latter (I mean, the logs are rotated out eventually, so
it's definitely not ideal).
[1] https://github.com/coreos/coreos-assembler/issues/268

Jenkinsfile: add CHECKSUMS file in uploads

---

Jenkinsfile

xz compression should be much faster now with:
[1] https://github.com/coreos/coreos-assembler/pull/632
So let's drop the hack and always use xz. For the developer use case,
the MINIMAL parameter means there's only really the `qcow2` to compress.

Jenkinsfile: go back to always compressing with xz

---

Jenkinsfile
utils.groovy

We want to maintain OSTree history between our releases. To do this, we
fetch the latest release from the release index, and pass it to cosa
through the `--parent` switch.
For more information, see:
https://github.com/coreos/coreos-assembler/issues/159#issuecomment-512594688

Jenkinsfile: use latest release on stream as parent

---

README.md

It's easy to get confused when talking about developer and official
pipelines and production streams and development streams. Let's spell
this out so we can refer to it when discussing these things.

README.md: add a "Terminology" section

---

Jenkinsfile

Use cosa to compress the qcow2, so we get multi-threading, before
archiving. Otherwise, we risk overloading the Jenkins master PVC before
too long.
Another strategy eventually would be to still upload to S3 (see [1]
which is related to this). But even then, we'd still want to compress
first.
[1] https://github.com/coreos/coreos-assembler/issues/668

Jenkinsfile: compress qcow2 before archiving on failure

---

Jenkinsfile

To be able to start the release job, we need `oc` which is not in cosa.
Run that step on the master itself, just like the wrapper jobs do.

Jenkinsfile: run Publish step on master

---

Jenkinsfile

Minor regression from #115. Now that the `Publish` stage is outside the
main cosa `podTemplate`, it always executes, even if no new builds were
created. This is because the no-op `return` only returns from that
scope.
Fix this by only assigning to `newBuildID` if it's actually new. Then
gate the `Publish` step on that.

Jenkinsfile: only run Publish on new builds

---

manifests/pod.yaml
manifests/sleep.yaml

We don't use the CentOS artifact server anymore. So just drop the secret
mount in the interest of only mounting those we really need.

manifests: drop duffy credentials

---

Jenkinsfile

Prep for actually being able to run tests in AWS.
See discussions in https://pagure.io/fedora-infrastructure/issue/8064.

Jenkinsfile: share AMI with Fedora testing account

---

Jenkinsfile

- Jenkinsfile: move kola AWS tests above Archive stage
- Jenkinsfile: shorten and enhance Kola stage names
- Jenkinsfile: check KOLA AWS cred before Kola:AWS stage

kola aws stage enhancements

---

Jenkinsfile
Jenkinsfile.kola.aws
Jenkinsfile.release
Jenkinsfile.stream.metadata.generator

Add the stream to the description of the job so we can find
related jobs in the UI without having to look at logs.

Jenkinsfiles: Add STREAM into description for Jenkins UI

---

Jenkinsfile.kola.aws

We are bumping up against instance limits in our test account so let's
drop the parallelization down.

Jenkinsfile.kola.aws: decrease parallelization to 5

---

manifests/pod.yaml

The `resources.requests.memory` tells the scheduler to put us on a node
with enough free RAM. The `XZ_DEFAULT` env tells `xz` not to go over
what we requested from OCP so we reduce the chances of being evicted for
memory consumption.
Closes: #136
---
Haven't tested this yet

manifest/pod: ensure we always have at least 2.5GiB of RAM

---

manifests/pod.yaml

Otherwise, `xz` just scales down to 1 thread.
Nodes should have the memory for this since we used to run without any
limits before and only occasionally got evicted.

manifest/pod: bump memory request to 6.5G

---

Jenkinsfile

`xz` doesn't like floating points as its `--memlimit`, and honestly I
don't blame it. Let's just use megabytes so everything is nice and
integer-y.

Jenkinsfile: use MiB for memory requests

---

HACKING.md
Jenkinsfile
configs/fedmsg.toml
manifests/pod.yaml

This makes use of the new `cosa sign robosignatory` command to sign both
the OSTree commit and final image artifacts.
Requires: https://github.com/coreos/coreos-assembler/pull/763

pipeline: add support for signing via RoboSignatory

---

Jenkinsfile.kola.aws
Jenkinsfile.release
Jenkinsfile.stream.metadata.generator

We were only doing it in the main Jenkinsfile, but many of the other
ones use the same `pod.yaml` definition so we need to sub out that
variable there too.
In the future, I'd like to switch all jobs over to
[coreos-ci-lib](https://github.com/coreos/coreos-ci-lib) instead to make
this less error-prone and only actually mount the secrets each job
needs.

Jenkinsfile.*: consistently substitute COREOS_ASSEMBLER_MEMORY_REQUEST

---

Jenkinsfile.kola.aws
Jenkinsfile.release

After [1], `buildprep` wants to write to `tmp/` but that directory
doesn't exist yet. Really, we should be nice to cosa and `init` the
workdir first so it doesn't get confused.
[1] https://github.com/coreos/coreos-assembler/pull/823

Jenkinsfile.*: do `cosa init` before `buildprep`

---

docs/aws-iam-policies/community-account/prod-account-match-fcos-upload-amis
docs/aws-iam-policies/prod-account/fcos-upload-amis

We need this for the new mantle code that replicates AMIs:
https://github.com/coreos/mantle/pull/1112

docs/aws-iam-policies: add DescribeSnapshotAttribute

---

Jenkinsfile.kola.aws

Right now, the logic for parsing `kola-blacklist.yaml` lives in cosa. So
use that to run the tests.
Could make `cosa kola` smarter here so that it picks up the AMI from the
metadata and passes that instead of the qemu image. But this hack works
for now.

Jenkinsfile.kola.aws: use `cosa kola` to run tests

---

HACKING.md
Jenkinsfile
deploy
manifests/pipeline.yaml
manifests/pod.yaml

Let's focus people on the new way forward for KVM, which is
the KVM device plugin from Kubevirt.  This is also now documented
in coreos-assembler.
Tested in the CoreOS CI cluster, an OpenShift 4.2 GCP nested virt setup following
https://github.com/coreos/coreos-assembler/blob/master/doc/openshift-gcp-nested-virt.md
I didn't test that the OCI KVM hook path still works.

Add support for KVM device plugin

---

jenkins/master/plugins.txt

This is the first step towards setting up GitHub auth login for Jenkins.
Still playing around with this, and I'd like first to start with
enabling it for the coreos-ci project (where GitHub PRs will be tested).
But I want that project to use the exact same Jenkins definition as here
to ensure equivalence.

jenkins: add github-oauth plugin

---

Jenkinsfile.kola.aws

As part of the move to `cosa kola` the output dir is now `tmp/kola`.

Jenkinsfile.kola.aws: Use the new output dir.

---

Jenkinsfile.kola.aws

It's no longer under `_kola_temp` and for some reason it's also no longer
under `aws-latest`.

Jenkinsfile.kola.aws: fix the path to the report

---

Jenkinsfile

We're trying to build an update to 30.20191014.0 and we have
built a COSA container from that same time. That container didn't
support building aliyun.

Remove Aliyun stage temporarily

---

Jenkinsfile

This reverts commit d141c27888876e51dc8f65f866d6ef29ca3f6685.
We won't be using old cosa again.

Revert "Remove Aliyun stage temporarily"

---

HACKING.md
manifests/jenkins.yaml
manifests/jenkins.yaml.orig

There is this great plugin which I've somehow only learned about
recently to make Jenkins configuration much easier:
https://github.com/jenkinsci/configuration-as-code-plugin
The RHCOS pipeline already makes use of it.
To use this though, we need to be able to change the podspec of Jenkins
itself, which until now was embedded in the `jenkins-persistent`
template.
There's more though: I want to be able to define environment variables,
configmaps, secrets, etc... The default template doesn't provide
facilities for this.
So this patch essentially imports the template into our tree so that we
can have more control. The downside of course is that we lose updates to
the template. (Though that could also be seen as an upside too: we get
better reproducibility even if the template is upgrade.) …

manifests: add jenkins.yaml template

---

HACKING.md
Jenkinsfile
jenkins/master/plugins.txt
manifests/jenkins.yaml
manifests/pipeline.yaml
manifests/pod.yaml

We need to add more monitoring on the pipeline. Otherwise it's going to
be very easy to go red for a few days without noticing.
My initial goal was to hook up to IRC, but the reality is that I think
we'll need both Slack and IRC because many folks mostly live in Slack
nowadays.
(That said, I still fully intend to add IRC support via fedmsgs as
discussed in #41).
Now, how this patch works is that we add two new Jenkins plugins:
- configuration-as-code
- slack
The first one is used to configure the second one. More broadly, it's
able to configure almost all of Jenkins and its plugins via YAML instead
of dropping to XML, so we'll likely be leveraging it some more in the
future.
The actual configuration bit here is more or less the same as RHCOS,
with some minor variations (we use secrets …

Add support for Slack notifications

---

Jenkinsfile

This uses the new `versionary.py` script which implements the new
versioning scheme:
https://github.com/coreos/fedora-coreos-releng-automation/pull/50
---
Marking as draft for the same reason as https://github.com/coreos/fedora-coreos-releng-automation/pull/50. Just flushing it out since I already had it written up and tested.

Jenkinsfile: use versionary to implement version scheme

---

Jenkinsfile

This isn't working for some reason. Let's see if we can unblock the
pipeline. We might need to disable the signing of the artifacts later
as well.
This is related to https://github.com/coreos/fedora-coreos-pipeline/issues/178

Jenkinsfile: don't sign the ostree commit for now

---

Jenkinsfile

Followup to 586126c. Looks like the issue affects signing of the artifacts
too. This is related to https://github.com/coreos/fedora-coreos-pipeline/issues/178

Jenkinsfile: don't sign the artifacts for now

---

Jenkinsfile

We'll now use the Live ISO/kernel/initrd for installs. This is related
to: coreos/fedora-coreos-config#261

Jenkinsfile: stop building the installer ISO/kernel/initrd artifacts

---

Jenkinsfile

Regression from 4531066e5dd0a99bf827181af8094acb9ad42dc0 in the
case where no version override is provided, and we're doing
an unofficial build.  My test pipeline blew up with a `null`
in the commandline.

Jenkinsfile: Handle the case of unofficial versions

---

Jenkinsfile.release

So that we can override it for one-shot runs, just like the main
pipeline. Also print the final podspec before provisioning the container
to help with troubleshooting.

Jenkinsfile.release: add COREOS_ASSEMBLER_IMAGE parameter

---

Jenkinsfile
Jenkinsfile.kola.aws
Jenkinsfile.release
Jenkinsfile.stream.metadata.generator

This will force the Kubernetes plugin to provision a new pod for each
job run rather than try to reuse them.
This is also prep for having parallel pipeline runs.

Jenkinsfile: use random UUID as node label

---

Jenkinsfile

So we test NVMe root disk, Secure Boot etc.
See https://github.com/coreos/coreos-assembler/pull/1029

pipeline: Run cosa kola --basic-qemu-scenarios

---

Jenkinsfile

Now that https://github.com/coreos/mantle/issues/1059 is fixed (see
https://github.com/coreos/mantle/pull/1153), we can use the new
`--no-test-exit-error` switch to be more strict about kola error
handling.
This way, we immediately fail the build if something fundamental went
wrong with kola.

Jenkinsfile: stop ignoring kola errors

---

Jenkinsfile
Jenkinsfile.kola.aws
utils.groovy

Start running the new upgrade test right after building the QEMU image.
In the AWS test job, run the upgrade test on AWS in parallel.
For more information, see:
https://github.com/coreos/mantle/pull/1168

Hook up upgrade testing

---

Jenkinsfile
Jenkinsfile.kola.aws

Cosa now puts the output of upgrade tests in `tmp/kola-upgrade`, so
tweak things here accordingly.
This makes the two jobs more consistent and also fixes the issue of
`Jenkinsfile.kola.aws` running both testsuites in parallel but
outputting into the same directory.

Jenkinsfile{,.kola.aws}: tweak upgrade test output dir

---

.cci.jenkinsfile

For now, this just does a basic sanity checking that the manifest files
in `manifests/` are valid. Though in the future, we can make e.g. it run
through the pipeline itself in dry-run mode.

ci: hook up to CoreOS CI

---

Jenkinsfile
Jenkinsfile.release
manifests/pipeline.yaml

Sprinkle `runPolicy: Parallel` a bit everywhere, then adapt the various pipeline code to deal with it correctly. See individual commit messages for details!

Allow concurrent builds/releases/tests

---

Jenkinsfile.kola.aws

There were two issues here. First, we were doing return inside of
`stage {}`, so we weren't actually failing the build. Fix this by moving
the result check outside.
Second, the upgrade test needs the OSTree tarball. Pass `--ostree` to
`buildprep` so it downloads it. I hesitated putting the test in the
build pipeline instead, since we obviously have the tarball already, but
I think keeping all AWS testing outside the main build path is better.
Note the main pipeline does do upgrade testing via QEMU already.

Jenkinsfile.kola.aws: fix upgrade testing

---

Jenkinsfile.kola.aws
Jenkinsfile.release

Now that buildprep supports passing in a build id let's use that
so we're more explicit.

switch cosa buildprep commands to specify which build

---

HACKING.md
deploy
manifests/jenkins-s2i.yaml
manifests/pipeline.yaml

See individual commit messages, but essentially the end goal here is preparations for sharing things with [CoreOS CI](https://github.com/jlebon/coreos-ci). Specifically, I want CoreOS CI to use the exact same Jenkins build configs, i.e. the inputs to the S2I builder. However, the pipeline and CoreOS CI will have different JCasC configurations (provided via configmaps) and Jenkins app templates (`jenkins.yaml`).

Prep patches for sharing with CoreOS CI

---

Jenkinsfile.kola.aws
Jenkinsfile.release

For example, if we're testing `stable`, we want to be running against
the `stable` kola blacklist, which might be different from what's in
`testing-devel`.

Jenkinsfile.kola.aws: checkout the corresponding stream branch

---

Jenkinsfile
Jenkinsfile.release

Add stages to call fcos-pipeline-ostree-import-request.py from the
fedora-coreos-releng-automation repo in order to send requests via
Fedora Messaging to the coreos-ostree-importer that is running within
Fedora Infrastructure's OpenShift instance.
There are two import stages. One in the normal pipeline (Jenkinsfile)
that is for importing all commits into the compose repo and one in
the release pipeline (Jenkinsfile.release) that will only run for
production streams and import commits into the production OSTree repo.
Additionally there are a few other commits. Please see individual commit
messages for more information.

Add stages for importing OSTree commits into Fedora OSTree repos

---

Jenkinsfile

We're seeing occasional issues where pods can't find `/dev/kvm` even
though we have a `oci_kvm_hook: allowed` selector (and in fact
`oci-kvm-hook` is installed on the whole cluster).
Print out the pod list on startup so that we can figure out on which
node the pod was scheduled to help debugging the next time we hit this.

Jenkinsfile: do `oc get pods -o wide` upfront

---

Jenkinsfile

Add `buildextend-exoscale` to pipeline
https://github.com/coreos/fedora-coreos-tracker/issues/384

Add Exoscale buildextend to pipeline

---

Jenkinsfile

On general principle, no reason not to run this test.

pipeline: Run kola testiso

---

manifests/pod.yaml

We've been hitting strange I/O related issues recently. We originally
traced it down to a specific node that was cordoned off, but now we're
hitting it on other nodes as well.
I think it might be related to the cache qcow2 being on an NFS and some
I/O patterns we do trigger some issues. Anyway, since the pipeline is
failing pretty bad, let's test that theory and swap it out for just an
`emptyDir`.
Also rename the mount to `cache` rather than `data` to make it clear we
don't actually need it.

manifests/pod: stop using PVC cache for now

---

utils.groovy

We want to always fail the build if the result is not `PASS`. But we
only want to archive the qcow2 if the platform is `qemu-unpriv`.

utils: fail the build if kola tests fail

---

Jenkinsfile

Let's cap build runs to 4h. Builds should never take that long. Ideally,
we'd do timeouts per stage, and that could make sense (e.g. signing for
example could in the worst case take more than 1h, but building the
qcow2 shouldn't really take more than 15m), though just having one
overall timeout to start with will at least prevent jobs from getting
stuck anywhere in the process forever and taking up a pod in a cluster.
Closes: #195

pipeline: add overall timeout of 4h

---

Jenkinsfile

For public images GCP would like for the description of the image to be
in the format: `DISTRO, DISTRO RELEASE, VERSION, INFO` so that information
can get pulled into web UIs and documentation. Let's start with something
like:
```
Fedora CoreOS, Fedora CoreOS stable, 31.20200310.3.0, x86_64 published on 2020-03-25
```

Jenkinsfile: add description for the GCP uploaded image

---

Jenkinsfile.development
Jenkinsfile.mechanical
Jenkinsfile.production
streams.groovy

There's more work needed before we can unblock those. For background,
on bodhi-updates, see:
https://github.com/coreos/fedora-coreos-config/pull/335#issuecomment-610634917
For the next-devel stream, see:
https://github.com/coreos/fedora-coreos-tracker/issues/283#issuecomment-610974733

streams: disable bodhi-updates and next-devel for now

---

streams.groovy

We should be able to rebuild this stream soon after
https://github.com/coreos/fedora-coreos-config/pull/351 merges.

streams: re-enable next-devel

---

Jenkinsfile

For example, on `next-devel`, we don't have any releases yet.

pipeline: handle release index without releases

---

Jenkinsfile

We always want to build in strict mode. See:
https://github.com/coreos/fedora-coreos-tracker/issues/454

pipeline: use `cosa build --strict`

---

Jenkinsfile

We also need to fetch in strict mode. This requires [1]. See that PR
for more information.
[1] https://github.com/coreos/coreos-assembler/pull/1378

pipeline: use `cosa fetch --strict`

---

jenkins/config/seed.yaml

This patch begins the transition from our current buildconfig-based
pipeline jobs to the one used by CoreOS CI, which is CasC + job DSL +
simple Groovy files in a `jobs/` dir + using the shared coreos-ci-lib
library for making it easy to leverage OpenShift. I really like how it
all fits together, and the upstream CI experimentation has seen some
positive results.
For now, we only install the seed job. This will allow us to then
add pipeline jobs directly in `jobs/`. This is the same CasC fragment
present in CoreOS CI:
https://github.com/coreos/coreos-ci/blob/2421fabaef79f93d2c111fdf9bce648ab3d19680/jenkins/config/seed.yaml
There's follow-ups there to make that seed job cleaner (and deduping
from CoreOS CI).

jenkins/config: add seed.yaml

---

jenkins/config/github-coreosbot.yaml
jobs/bump-lockfile.Jenkinsfile

This job will implement lockfile bumping for testing-devel and
next-devel: coreos/fedora-coreos-tracker#293.
The original plan for this functionality was to have it in config-bot:
coreos/fedora-coreos-releng-automation#48
But in the end, I think it's more natural to have it as a Jenkins job
given that it does a lot of the same things as the pipeline/upstream CI
jobs. So that way it looks and feels just like another job that runs
cosa, and we get kola artifacts, we can re-use the shared library,
it's easily inspectable, we can hook it to Slack, etc...

jobs: add bump-lockfile

---

Jenkinsfile

Upgrade tests on the `next` stream are going to fail right now because
of a known regression:
https://github.com/coreos/fedora-coreos-tracker/issues/473
Add a temporary knob to allow continuing the build without it.
I initially tried just blacklisting it, but because it's the only test
in the suite right now, kola errors out due to no tests being available
to run.

pipeline: add temporary knob to allow upgrade tests to fail

---

Jenkinsfile.kola.gcp

This adds the Jenkinsfile.kola.gcp file that will allow us to run tests
against GCP images just like we do for AWS images.

Add pipeline to test GCP images

---

Jenkinsfile
Jenkinsfile.release

In our build/release workflow for GCP we will build and upload/create
a GCP image in the build pipeline. In the build pipeline we will
deprecate the image because we haven't decided to release it yet.
In the release pipeline we will undeprecate the image and deprecate
all other images in that image family using the ore gcloud promote-image
command.
Also attach the image to a license upon creation.

update for GCP image build/release workflow

---

Jenkinsfile.kola.gcp

We were missing a `\` but we also need to specify the `=` in the
--platform calls otherwise cosa kola gets confused.

Jenkinsfile.kola.gcp: fix upgrade test

---

Jenkinsfile.kola.gcp

`--upgrades` will switch it to `run-upgrades`, but adding `run` will
override that.

Jenkinsfile.kola.gcp: remove `run` parameter from upgrade test

---

Jenkinsfile.kola.gcp

Upgrade tests use the image of the previous release, not the candidate
release we're testing itself. The `--find-parent-image` switch will
automatically find the starting image to use.
Closes: https://github.com/coreos/fedora-coreos-tracker/issues/487

Jenkinsfile.kola.gcp: drop --gce-image

---

Jenkinsfile

I think Jenkins doesn't like that the parallel branch name starts with
numbers. Anyway, I think it's clearer if we just use the same names as
the artifacts that each branch is testing.

Jenkinsfile: tweak parallel branches' names

---

Jenkinsfile

This will allow for launched instances to have access to /dev/kvm
by default. I am not aware of any known drawbacks to doing this as
I've been informed by GCP folks that if there is an environment that
doesn't have nested virt support or if there is a policy that disallows
it the instance simply won't have access to /dev/kvm. No other errors
would be presented to the user (like not being able to launch an
instance).

Jenkinsfile: attach nested virtualization license to GCP images

---

jobs/bump-lockfile.Jenkinsfile

The credential bindings bind to environment variables that e.g. `bash`
can access. So here we need to escape the variable references to make
sure it's `bash` that dereferences them. Oddly, this somehow did work at
first, so I think it did/does sometimes also bind to Groovy variables.

bump-lockfile: fix variable substitution for auth

---

jobs/bump-lockfile.Jenkinsfile
streams.groovy

Until f33 branches or we start using it to track new kernel/systemd
updates.

Disable next-devel stream for now

---

HACKING.md
jenkins/config/aws.yaml
jenkins/master/plugins.txt
jobs/sync-stream-metadata.Jenkinsfile
manifests/jenkins.yaml

Add a new job that will automatically sync the fedora-coreos-streams
metadata to S3. This is part of streamlining the release process.

Add new sync-stream-metadata job

---

Jenkinsfile

The metal4k test is failing right now. Let's make sure we grab the logs
so we can do some debugging it without having to rebuild it locally
first.

pipeline: archive testiso logs

---

Jenkinsfile

This is a bit heavy-handed, but the pipeline is failing right now at the
`metal4k` `iso-offline-install` test and I can't reproduce it locally.
It's possible that there's a subtle mismatch, or it's somehow down to
the Jenkins environment. To rule that out, let's just archive the iso
for now if `testiso` failed.

pipeline: archive liveiso on failure

---

Jenkinsfile

We need the metal4k image in place before generating the ISO so that we
can `osmet pack` it. Otherwise understandably, the `iso-offline-install`
test for `metal4k` will fail. We should probably add a switch that makes
it required to `buildextend-live`.

pipeline: generate liveiso after metal4k

---

Jenkinsfile

There is a box in the web UI that shows the images were
"Created By: Fedora CoreOS". Let's change our description
slightly so that it says "Created By: Fedora" instead.

Jenkinsfile: slightly change description for GCP images

---

jobs/bump-lockfile.Jenkinsfile
jobs/sync-stream-metadata.Jenkinsfile

I'd like to have CoreOS CI exercise the new cluster for a bit before
moving the production pipeline itself over. For now, let's pin the
version of coreos-ci-lib we use here which still uses oci-kvm-hook
instead of kubevirt.

jobs: pin to coreos-ci-lib for OCP3 for now

---

jobs/bump-lockfile.Jenkinsfile
streams.groovy

We want to experiment in `next` with the major podman version bump
so let's re-enable `next-devel`.
See https://github.com/coreos/fedora-coreos-tracker/issues/560
This reverts commit d65ae1cba488c4be9ae6b43b5e7975c49f5776ac.

Re-enable `next-devel` stream

---

Jenkinsfile

This test is flaky right now. See
https://github.com/coreos/coreos-assembler/issues/1597.

pipeline: ignore failures from pxe-install scenario

---

Jenkinsfile

https://github.com/coreos/coreos-assembler/issues/1597 is fixed.  This reverts commit c175ec031e277e02256889cf82fdc7558e81f867.

pipeline: stop ignoring failures from pxe-install scenario

---

Jenkinsfile

Generate a PXE rootfs image that only contains a flag file for alerting purposes.  We'll switch to a real separate rootfs image after a deprecation period.
For https://github.com/coreos/fedora-coreos-tracker/issues/390.  Must be merged at the same time as https://github.com/coreos/coreos-assembler/pull/1608.

pipeline: build legacy PXE images for now

---

Jenkinsfile

With https://github.com/coreos/coreos-assembler/pull/1620, running `cosa compress` before `kola testiso` is no longer more efficient, but we should still test with compressed artifacts because that's what users will use.

pipeline: update comment

---

Jenkinsfile

Switch next and next-devel to the modern artifacts.

pipeline: disable legacy PXE artifacts except on testing*/stable

---

Jenkinsfile.release

Let's be explicit and require that users/machines specify which version
to release instead of having a dangerous/racy "use latest" fallback.

Jenkins.release: error out if VERSION is not provided

---

Jenkinsfile.kola.aws
Jenkinsfile.kola.gcp

```
commit 184ef19b52f2ac5ab370c134039afc0bf48f8889
Date:   Tue Aug 25 11:50:42 2020 -0400
Jenkinsfile.kola.{aws|gcp}: make STREAM param a choice
Matches the main pipeline.
commit e13e1e464e0cc86b6e657e4b6d2af93b4eea74b6
Date:   Tue Aug 25 11:51:12 2020 -0400
Jenkinsfile.kola.{aws|gcp}: auto-generate stream dir if missing
It's annoying to have to type it in when triggering tests manually.
(That parameter ideally wouldn't be needed at all. But it's useful in
the developer case where we're targeting a separate bucket. I'd like to
rework the developer workflow eventually.)
```

Jenkinsfile.kola.{aws|gcp}: various improvements

---

Jenkinsfile.kola.aws
Jenkinsfile.kola.gcp

Jenkins doesn't allow assigning a new value to the job parameters. Make
it a separate variable instead.
Fixes: #265

Jenkinsfile.kola.{aws|gcp}: fix groovy error

---

HACKING.md
Jenkinsfile
deploy
jenkins/master/plugins.txt
jobs/bump-lockfile.Jenkinsfile
jobs/sync-stream-metadata.Jenkinsfile
manifests/jenkins-s2i.yaml
manifests/jenkins.yaml
manifests/jenkins.yaml.orig
manifests/pipeline.yaml
manifests/pod.yaml

```
commit cc4b2095febdfdc697b8bffe86a68421126791eb
Date:   Mon Aug 24 09:44:59 2020 -0400
jenkins: rebase to latest OCP4 template
And as usual, keep marking all the deltas with `DELTA`.
commit 9564c1a289d2044593a5aec9dac2e052d599c6d1
Date:   Mon Aug 24 09:45:00 2020 -0400
pipeline: adapt to new cluster URL and version
Update the Jenkins URL and cluster URL to the new cluster, move the jobs
which use coreos-ci-lib to go back to the master branch, and change the
default KVM selector to kvm-device-plugin. (We'll rip out that switch
altogether in a following patch).
commit 516091e19a778d18bd84f1d19e4c24049d1e4df3
Date:   Mon Aug 24 09:45:01 2020 -0400
plugins: bump configuration-as-code to 1.35
Otherwise we get version dependency issues with the other new plugins.
commit …
```

Move pipeline to new OCP4 cluster

---

HACKING.md
jenkins/config/github-webhook.yaml

```
$ git log master..
commit a1abda72f11dfd0a56b456760aa45ac13ca89034
Author: Jonathan Lebon <jonathan@jlebon.com>
Date:   Fri Jun 5 16:43:18 2020 -0400
config: use a webhook shared secret
Just as good practice, we should use a shared secret when using
webhooks.
commit 8ca6a5a076bcf3c69e1af46966c1f477c71e7096
Author: Jonathan Lebon <jonathan@jlebon.com>
Date:   Fri Jun 5 16:42:36 2020 -0400
config: let Jenkins manage webhooks
That way we don't have to go fiddle around in repo settings manually.
```

Some webhook configuration improvements

---

jobs/bump-lockfile.Jenkinsfile

This job is key to our promotion model. We've had lapses in the past
where we didn't realize it was failing for a few days.
Let's send a Slack notification whenever the job fails to prevent this
(and yes, still hoping to eventually move to IRC notifications).
While we're here, also wrap it all in a timeout as good practice.

bump-lockfile: add timeout and send Slack msg on failure

---

Jenkinsfile

The new kubernetes-plugin already prints what node the pod is scheduled
on, which serves our purposes.

pipeline: drop `oc get pods -o wide` call

---

jobs/bump-lockfile.Jenkinsfile

In a good build, in the `finally` block the current build's status isn't
*yet* `SUCCESS`... because the build is still running. And so the
conditional we have there fails. Fix this by explicitly setting the
status to `SUCCESS` at the end of the job.

bump-lockfile: explicitly mark build as SUCCESS

---

README.md

I actually can't log into the new Jenkins (or see the `fedora-coreos`
project) but I'm pretty sure this is the right one.  Add a link
to the "new" OCP4 docs I found.

README.md: Update links/info for new CentOS CI 4.4 OCP cluster

---

Jenkinsfile

We need to do an out-of-cycle testing release this week.

pipeline: switch testing builds back to legacy PXE artifacts

---

manifests/jenkins.yaml

We're seeing intermittent issues where the NFS PVC mount seems too slow
for Jenkins to function properly:
https://pagure.io/centos-infra/issue/26#comment-685779
Switch over to an emptyDir for now. (This means that on restarts Jenkins
will lose all job history.)

manifests/jenkins: use emptyDir for now

---

jenkins/master/plugins.txt

I think we're hitting
https://github.com/jenkinsci/configuration-as-code-plugin/pull/1359,
which is fixed in v1.39.
```
2020-09-16 16:38:13 WARNING jenkins.telemetry.impl.java11.MissingClassTelemetry reportException Added a missed class for missing class telemetry. Class: javax.annotation.Nonnull
java.lang.ClassNotFoundException: javax.annotation.Nonnull
at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1387)
at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1342)
at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1089)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.tryConstructor(DataBoundConfigurator.java:118)
```
Let's try out that release.

jenkins/plugins: bump configuration-as-code to 1.39

---

Jenkinsfile

Hold until the out-of-cycle testing release is complete.
This reverts commit ca0f43ca09d126376503d09dac69199e4630120f.

pipeline: switch testing builds back to modern PXE artifacts

---

utils.groovy

This is affecting the pipeline too now:
https://pagure.io/centos-infra/issue/79
Add the hack here too until we fully drop utils.groovy in favour of
coreos-ci-lib (where this hack already exists).

utils: add umask workaround

---

manifests/jenkins.yaml

```
commit e750f1fdde511f9a9db415c635a5e71e540044df
Date:   Thu Oct 22 12:05:24 2020 -0400
Revert "manifests/jenkins: use emptyDir for now"
This reverts commit e519ccc6e9359e56050711dbac25cd2d83c2c021.
The NFS backend is still recovering, but it seems fast enough now to
handle Jenkins using it again.
commit ca9510dcb37fad05454d94f2dd21fa1619dedff9
Date:   Thu Oct 22 13:40:43 2020 -0400
jenkins.yaml: bump VOLUME_CAPACITY to 5Gi
This is the size of the PVC that was actually created back when we
migrated to the cluster. Might as well make the manifest match what
we're operating with now.
```

Go back to using a PVC for Jenkins

---

jobs/kola-aws.Jenkinsfile
jobs/kola-gcp.Jenkinsfile

This is the classic "I meant bash env var not Groovy var" trap.

jobs/kola-{aws,gcp}: escape $ for bash env

---

jobs/kola-aws.Jenkinsfile
jobs/kola-gcp.Jenkinsfile

Otherwise, it confuses the `cosa kola` wrapper which tries to process
the arguments.
We should fold the denylist handling and basic scenario testing into
kola proper so we can drop this wrapper.

jobs/kola-{aws,gcp}: use `--arg=val` format for platform args

---

jobs/kola-gcp.Jenkinsfile

We can't use `readJSON` because IIRC that runs on the master but the
config file is mounted in the pod. Just use `jq`. And that way we get to
use the automatically generated env var too.

jobs/kola-gcp: use `jq` instead of `readJSON`

---

Jenkinsfile
Jenkinsfile.release
jobs/sync-stream-metadata.Jenkinsfile

This patch adds four new fedmsgs:
- `build.state.change`: emitted at the start and end of a build
- `stream.release`: emitted when a build is released
- `stream.metadata.update`: emitted for stream/graph metadata updates
This will allow other services to hook more closely into our process.
Some use cases right now are AWS Marketplace listing updates, mirrors
triggering a sync, and OpenQA testing the latest artifacts.
I started with a helper for sending the messages in `utils`, but I'd
like to get rid of `utils` down the line in favour of moving all that
functionality into the shared library.
Closes: coreos/fedora-coreos-tracker#225

Add new fedmsgs for builds, releases, and metadata

---

configs/fedmsg.toml
jobs/sync-stream-metadata.Jenkinsfile
manifests/pod.yaml

This is the path under which `coreos-ci-lib` puts the secret. We want
the config to work in both the "old world" (where it uses `pod.yaml`)
and the "new world" (where it uses `pod(secret: ...)` from
`coreos-ci-lib`), so let's update the path in the config and `pod.yaml`
to match `coreos-ci-lib`.
This fixes one `XXX` in the `sync-stream-metadata` job which turns out
to be a hard blocker because the container runs as non-root and so
doesn't have the privs to link at `/run/fedora-messaging-coreos-key`.

Point fedmsg config to new k8s secret path

---

jobs/sync-stream-metadata.Jenkinsfile

We need the appended `--dryrun` to be on the same line as `aws s3 sync`.

jobs/sync-stream-metadata: fix --dryrun arg passing

---

jobs/sync-stream-metadata.Jenkinsfile

One obvious thing that I missed while working on #288 was that this job
doesn't actually have a `STREAM` parameter since it syncs all the
streams in one shot. So the fedmsg it emits will have `null` as the
stream name.
To make this stream-sensitive, let's change to doing `aws s3 sync`
separately for each stream with change detection for each. That way we
only emit fedmsgs for streams which actually had their metadata changed.

jobs/sync-stream-metadata: sync one stream at a time

---

Jenkinsfile

Otherwise, the `finally` block where we emit a message won't be able to
access it.

pipeline: declare basearch earlier

---

Jenkinsfile

Otherwise it will require services which want to make use of these
fedmsgs to hardcode knowledge of our bucket layout.

pipeline: pass URL to build dir in fedmsgs

---

manifests/pod.yaml

We're hitting pull limit errors on Docker Hub, and anyway that one is
deprecated in favour of the one on Quay.io so let's switch to that.

manifests/pod: use jnlp image from quay.io

---

jobs/sync-stream-metadata.Jenkinsfile

These were accidentally dropped in #295.

jobs/sync-stream-metadata: use --acl and --cache-control args

---

jenkins/master/plugins.txt

```
commit f1cba81bf0d139474a7b126bb231bd3fdba81058
Date:   Wed Dec 16 10:56:56 2020 -0500
plugins: add configuration-as-code-groovy
This is needed so that we can run some Groovy code via CASC dropins.
Obviously this goes against the declarative CASC premise a bit, but in
some cases you need that escape hatch. Here for example, we'll use this
to modify the pod concurrency cap on the *pre-existing* "openshift"
cloud that gets created (which it seems you can't do in pure CASC).
commit 35191fa603ff5ddbbdcdbc1591e771666a16e40a
Date:   Wed Dec 16 10:59:03 2020 -0500
plugins: add basic-branch-build-strategies
This will be used to allow skipping PR rebuilds when only the base
changes.
```

Add configuration-as-code-groovy and basic-branch-build-strategies plugins

---

Jenkinsfile.mechanical
streams.groovy

We need to start tracking changes that happen in rawhide earlier so that
we can better participate in the branching and stabilization process of
Fedora releases.
Let's create a mechanical rawhide stream.

streams: add rawhide mechanical stream

---

Jenkinsfile
Jenkinsfile.release

It doesn't quite work yet because e.g. in GCP we need to create a
license. But at least, let's push out builds which passed local QEMU
tests.
(Related to this, adding another stream like this reminds we really need
to tackle GC at some point. E.g. for rawhide, we should have an
aggressive policy.)

pipeline: don't upload to clouds for rawhide for now

---

README.md

The example ticket used in #303 is private, so not everyone can see it.
Use another example ticket which is public.

README.md: fix link to example access request ticket

---

Jenkinsfile

They're currently failing because of
https://github.com/coreos/coreos-assembler/issues/1977.

pipeline: stop triggering OpenStack tests

---

Jenkinsfile
Jenkinsfile.release

This was moved to cosa in
https://github.com/coreos/coreos-assembler/pull/2006.

pipeline: move from `trans.py` to `cosa generate-release-meta`

---

Jenkinsfile

When a builds occur we now generate a keylime hashlist and upload it to an expected location. We also upload a sha256sum.
See:
- https://github.com/keylime/enhancements/blob/master/16_remote_allowlist_retrieval.md
- https://github.com/coreos/coreos-assembler/blob/master/src/cmd-generate-hashlist
- ~https://github.com/coreos/coreos-assembler/pull/1970~
When closing [the upload PR](https://github.com/coreos/coreos-assembler/pull/1970) we decided to modify the pattern for POC as such:
- Output the hashlist as `exp-hash.json`
- Ensure the `exp-hash.json` file is in the builds/ directory so it is uploaded as a sibling of `{meta|commitmeta}.json`
- sha256sum the `exp-hash.json` file as `exp-hash.json-CHECKSUM`
- Once this work moves beyond POC we will update the output file to an expected …

Jenkinsfile: Create and upload keylime hashlist

---

jenkins/master/plugins.txt

This will allow us to add timestamps to all build logs.
Prompted by: https://github.com/coreos/rpm-ostree/pull/2583

jenkins: add timestamper plugin

---

streams.groovy

We're adding a `branched` stream:
https://github.com/coreos/fedora-coreos-tracker/issues/743

streams: add branched mechanical stream

---

jobs/bump-lockfile.Jenkinsfile

We want bump-lockfile to print the package diff so that it's easier to
pinpoint likely culprits when it fails. Do a `cosa buildprep` so we get
that diff.

bump-lockfile: do `buildprep` for package diff

---

jenkins/config/timestamper.yaml

Follow-up to https://github.com/coreos/fedora-coreos-pipeline/pull/309.

jenkins/config: turn on timestamper for all pipeline jobs

---

streams.groovy

Right now, the top-level
`fedora-coreos-pipeline-{development,mechanical,production}` jobs wait
on each FCOS build it spawns and errors out if any fails. But we don't
really need to do that because we barely look at those top-level jobs
anyway since all the action is in the primary `fedora-coreos-pipeline`
job, which also already emits Slack messages on failures.
This also causes FCOS builds to be done serially instead of in parallel.
And worse, failures in the first ones cause the latter ones to never be
triggered. (Right now for example, `rawhide` is failing and it's
preventing `branched` from even running.)
So drop the `--wait` switch.

streams: don't wait for build to finish

---

jenkins/master/plugins.txt

This plugin allows scripts to trigger jobs using a secret token without
having to set up authentication. I'd like to use this with GitHub
Actions in the future.

plugins: add build-token-root

---

jobs/bump-lockfile.Jenkinsfile

That way it's easier for folks to tell where this push came from, and
from there look at the repo README for deployment and ownership
information.
Brought up by Colin in IRC.

jobs/bump-lockfile: include link to job

---

Jenkinsfile
jobs/kola-aws.Jenkinsfile
jobs/kola-gcp.Jenkinsfile
jobs/kola-openstack.Jenkinsfile

We're hitting SELinux flakes in the releases:
https://github.com/coreos/fedora-coreos-tracker/issues/751
Working on a better way to allow known SELinux failures, but for now
let's just use the new `--no-default-checks` to unblock releases.

Temporarily use --no-default-checks

---

Jenkinsfile
jobs/kola-aws.Jenkinsfile
jobs/kola-gcp.Jenkinsfile
jobs/kola-openstack.Jenkinsfile

This reverts commit 74a78a3858038cdf738b3e4952e8c94e8ebd50d5.
We're dropping SELinux checking and support for that switch from kola,
so stop using it:
https://github.com/coreos/coreos-assembler/pull/2066

Revert "Temporarily use --no-default-checks"

---

jobs/bump-lockfile.Jenkinsfile

We weren't correctly archiving artifacts because we run inside a
`dir(branch) { ... }` block, which causes `archiveArtifacts` to
interpret paths relative to that dir, but `fcosKola()` outputs the
artifact at the top-level workspace directory.
Work around this by just calling `fcosKola` from the workspace.

jobs/bump-lockfile: fix artifact archiving

---

jobs/bump-lockfile.Jenkinsfile

Right now, we try to no-op early if we detect that the base lockfiles
didn't change. However, `--update-lockfile` will still touch the
lockfiles if just the repo timestamps changed (#232). This then causes
us to run `cosa build`, which no-ops, and then subsequent tests fail
because there is no e.g. qcow2 or ostree artifact that was built.
Fix this by detecting the no-op case just like the main pipeline does.
Closes: #232

bump-lockfile: strengthen no-op detection

---

streams.groovy

We've got plenty of CI failures that we need to sort through. Let's
disable these streams to decrease the noise for now.

streams: disable mechanical streams for now

---

jobs/bump-lockfile.Jenkinsfile

```
commit b25627639f2778e6d4a305bcbe3125bb93d72290
Author: Jonathan Lebon <jonathan@jlebon.com>
Date:   Wed Apr 7 12:12:57 2021 -0400
Revert "bump-lockfile: strengthen no-op detection"
This reverts commit 94f68d41d4258b1b9be3546bf4c0016c0c4bd3ed.
Just checking that a new build was created is not enough. One scenario
is if:
- the base lockfile was updated
- no new builds with the updated base lockfile happened
- no new packages are available
Then we'll be doing a `buildprep` for a build using the old package set
even though the lockfile in git is up to date.
The next commit will switch tactics.
```
```
commit ea2f08797bfe553bd2c560270e2c7bfeadcb9577
Author: Jonathan Lebon <jonathan@jlebon.com>
Date:   Wed Apr 7 12:15:53 2021 -0400
bump-lockfile: compare lockfiles directly to determine …
```

Revert "bump-lockfile: strengthen no-op detection" and compare lockfiles directly to determine no-op 

---

jobs/bump-lockfile.Jenkinsfile

These are global settings, so they just need to be done once, not
per-branch.
This avoids git hitting locking issues by racing with itself across
branches.

jobs/bump-lockfile: set up git user upfront

---

manifests/jenkins.yaml

This is basically the same as https://github.com/coreos/coreos-ci/pull/30, which seems to be working well.

jenkins: increase HEARTBEAT_CHECK_INTERVAL to 10 mins and turn on LAUNCH_DIAGNOSTICS

---

Jenkinsfile

The latest run of `next-devel` didn't sign images because of a failure.
Because the image signatures don't exist the upgrade test fails because
it can't verify the image download, which `coreos-installer download`
tries to do. Easiest thing to do for now is just disable the run upgrade
stage so we can get `next-devel` unblocked.

Jenkinsfile: temporarily don't run upgrade tests

---

jenkins/config/github-webhook.yaml

This is now called `hookSecretConfigs` and it's an array.

jenkins/config: fix deprecated hookSecretConfig

---

manifests/jenkins.yaml

The default is 10 mins, which is too short for Jenkins to come up
(likely because of slow NFS). So then OCP considers the rollout failed
and reverts to the previous version.

manifest/jenkins: bump readiness timeout to 20 mins

---

Jenkinsfile

This reverts commit c5bcb1acf416c198517f4105c28935530154c47d.
With https://github.com/coreos/coreos-assembler/pull/2138
the issue is fixed now!

Revert "pipeline: stop triggering OpenStack tests"

---

jobs/bump-lockfile.Jenkinsfile
jobs/bump-lockfiles.Jenkinsfile

Right now, the job tries to update both `testing-devel` and `next-devel`
in parallel, but this makes the output messy and hard to follow. It also
makes it harder to tell from the job status page which of the two
branches failed (and the BlueOcean UI isn't much help either).
Instead, let's make `bump-lockfile` focus on a single stream, and have a
driver job which simply triggers `bump-lockfile` once per stream so that
they're separate jobs. This mirrors how the main pipeline jobs
themselves are set up.
Closes: #331

bump-lockfile: de-parallelize

---

jobs/bump-lockfile.Jenkinsfile

Now that the job is stream-specific, we can be more specific in the
Slack message.

bump-lockfile: add stream name to Slack message

---

jobs/bump-lockfile.Jenkinsfile

It defaults to `/srv/fcos` otherwise.

bump-lockfile: point `fcosKola` to workspace

---

jenkins/master/plugins.txt

plugins: bump configuration-as-code to v1.49

---

manifests/jenkins.yaml

Jenkins already runs as gid 0, but we need to specify `fsGroup: 0` in
the pod definition too so that Kubernetes will make sure that the local
PVC mounted in will be chown'ed to the root gid so we can access it.

jenkins.yaml: use `fsGroup: 0` for Jenkins

---

jobs/bump-lockfile.Jenkinsfile

Otherwise, the Slack notifier code will think that the job failed and
emit a trashfire message.

jobs/bump-lockfile: explicitly set SUCCESS status in no-op case

---

Jenkinsfile
Jenkinsfile.release
Jenkinsfile.stream.metadata.generator
deploy
jobs/kola-aws.Jenkinsfile
jobs/kola-gcp.Jenkinsfile
jobs/kola-openstack.Jenkinsfile
manifests/pipeline.yaml
manifests/sleep.yaml

This reverts commit 0f8cf3a.
The `:latest` tag has fuzzy semantics. Let's be more explicit here and
use the actual branch-derived name.

Revert "COSA image: use :latest tag to ease migration"

---

jobs/sync-stream-metadata.Jenkinsfile

Otherwise, surprisingly the `git` step defaults to `master` instead of
whatever the default branch upstream is.

jobs/sync-stream-metadata: specify `main` branch when cloning fedora-coreos-streams

---

streams.groovy

Now that we've moved `testing-devel` to cgroups v2 there is no
difference between `testing-devel` and `next-devel`. Disable the
`next-devel` pipeline so we can avoid doing useless work.

streams: disable next-devel stream

---

utils.groovy

This is a heavy I/O operation because it requires copying the qcow2 from
the pod's workspace back to the controller.
I think it may have contributed to a recent job timing out because
compressing and then copying takes time. We also noticed that the kola
test results archived just before calling this function didn't make it,
which I suspect could be a result of Jenkins being interrupted while
archiving the qcow2 image.
Anyway, in practice we haven't used this a lot to investigate failures,
because in the end one tends to rebuild it locally for easier hacking.
So let's drop it.

utils: stop archiving the QEMU image on failure

---

jobs/kola-openstack.Jenkinsfile

Run them one at a time so we don't hit VexxHost resource limits.

jobs/kola-openstack: disable concurrent builds

---

jobs/bump-lockfile.Jenkinsfile

If we don't have package updates for the contentset of FCOS for a few
days, which is unusual but not unheard of (right now we haven't had
an updated RPM for 5 days), then bump the timestamp anyway. It's an
indicator of freshness for FCOS so even if no packages have changed
let's update it to bump the date in the FCOS version numbers.

bump-lockfile: update metadata timestamp periodically

---

jobs/bump-lockfile.Jenkinsfile

So they can be used in arithmetic.

bump-lockfile: convert timestamps into integers

---

Jenkinsfile

If we are operating on a mechanical stream then we can pin packages in
lockfiles but we don't maintain a full set so we can't do a strict build.

pipeline: don't do strict builds for mechanical streams

---

Jenkinsfile

This was added in https://github.com/coreos/coreos-assembler/pull/1566
and recently enabled for RHCOS.  Let's ship it here too to keep
things aligned upstream/downstream.

pipeline: Ship Azure Stack

---

jobs/bump-lockfile.Jenkinsfile

We don't want the bits, we just need to know if they passed tests or
not. Currently Gangplank doesn't support this [1] but we can force
it by just deleting the builds.json in a post command.
[1] https://github.com/coreos/coreos-assembler/issues/2317

bump-lockfile: force gangplank to not upload artifacts

---

Jenkinsfile
Jenkinsfile.release
jenkins/config/seed.yaml
utils.groovy

This introduces coreos-ci-lib in the production jobs and starts making
use of its shwrap helpers. This allows us to drain the duplicates we
have here in the "utils" module.
There's more stuff we can drain from "utils" into coreos-ci-lib, but
this at least paves the way for using more coreos-ci-lib helpers in
these jobs. (For example, we should switch over to `fcosBuild`,
`fcosKola`, etc... the way it's used in upstream CI). Notably, this will
also allow us to leveraging the gangplank work going on in
coreos-ci-lib.

Use shwrap* helpers from coreos-ci-lib in prod pipelines

---

Jenkinsfile.development
Jenkinsfile.mechanical
Jenkinsfile.production

It's not used anywhere and I'm seeing a library load error right
now so let's just clear them to help debug since they're not being
used.

Jenkinsfile.{development,mechanical,production}: stop loading utils.groovy

---

.gitignore
multi-arch-builders/README.md
multi-arch-builders/fcos-aarch64-builder.bu

We can use these machines via gangplank to do our multi-arch builds
remotely. The first will be an aarch64 builder.

Add instructions for deploying a multi-arch builder.

---

Jenkinsfile
utils.groovy

```
commit d577d969cf45f3c89cb675e3ef99a4321a390ce6
Date:   Fri Aug 6 09:50:26 2021 -0400
Jenkinsfile: iterate through releases until finding parent
In the case there was no previous release for an architecture
it can be null. In the case there were releases where some
architectures were skipped, we need to go through the list.
Handle both of those cases here.
commit 979427e265d6b49084fb6d378ef5b605b4ffc1b9
Date:   Fri Aug 6 09:35:26 2021 -0400
Jenkinsfile: serialize access to builds.json
Since we are about to start forking off pipeline runs for
multiple architectures at the same time we need to add some
locking and higher level logic around builds.json. We only
want a single job accessing it at the same …
```

Jenkinsfile: serialize access to builds.json

---

Jenkinsfile
jobs/multi-arch-pipeline.Jenkinsfile

This is the first attempt at adding a multi-arch pipeline. We'll
call the multi-arch-pipeline job from the main pipeline after QEMU
tests have passed.
This is currently mostly a copy/paste of the original pipeline. In
the future we want to factor out these bits and re-use them between
the main pipeline and the multi-arch-pipeline job.

Add multi-arch-pipeline job

---

jobs/multi-arch-pipeline.Jenkinsfile

The job name for this job won't be *fedora-coreos-pipeline so let's
treat it differently and just queue off of the jekins URL.

multi-arch-pipeline: handle "official" logic different

---

jobs/multi-arch-pipeline.Jenkinsfile

We're already passing it earlier in the cosa sign command invocation.

multi-arch-pipeline: don't pass --arch twice

---

utils.groovy

Otherwise things that pull from it (like the builds browser)
will break.

utils: cp builds.json with public access

---

Jenkinsfile.release

In the x86_64 pipeline we early archive the ostree but the meta.json
that gets uploaded includes the qemu qcow. Right now the aarch64
pipeline is finishing before the x86_64 pipeline does and when we
go to buildupload it's complaining because the x86_64 qemu qcow
doesn't exist either locally or in s3.
```
Exception: builds/36.20210812.91.0/x86_64/fedora-coreos-36.20210812.91.0-qemu.x86_64.qcow2 not found locally or in the s3 destination!
```
Since we shouldn't be uploading image artifacts in the release step
anyway, let's just pass --artifact=ostree, which will essentially
give us what we want. It won't re-upload the ostree because it already
exists in s3, and it won't try any other artifact, including qemu qcow.

Jenkinsfile.release: limit buildupload artifacts

---

jenkins/config/seed.yaml

Otherwise, we lose all the triggers defined in those jobs. This is a
natural consequence of pipeline jobs being able to describe their own
triggers as imperative code.
Add a `FORCE` parameter if we really want to update existing jobs, with
a helper text about the trigger subtlety.

seed: don't redefine existing jobs by default

---

streams.groovy

Fedora 35 has branched now, so let's track it.

streams: re-enable `branched` stream

---

Jenkinsfile

We're not quite ready for them on the production streams just yet.

Jenkinsfile: limit multi-arch-pipeline to non production builds

---

jobs/kola-aws.Jenkinsfile
jobs/kola-gcp.Jenkinsfile

```
commit 3af893efef8095bf58e92f01298c7e02a6502f0e
Date:   Thu Aug 19 16:49:52 2021 -0400
kola-gcp: support arch, get image from meta.json
Similar to what we just did for AWS let's support passing in the
architecture (even though GCP only supports one) and also let kola
pick up the image from the meta.json rather than digging for it here
in the job.
commit 475f622705ba80d4327f849d48c19c2f65d8e407
Date:   Tue Aug 10 15:53:36 2021 -0400
kola-aws: allow kola to introspect instance type and AMI
kola recently gained the ability to pick up the AMI ID from
the specified build metadata and also switch the instance type
based on the target architecture. Let kola do the heavy lifting
here for us.
See …
```

kola-aws,kola-gcp: support arch, let kola inspect meta.json

---

Jenkinsfile
jobs/multi-arch-pipeline.Jenkinsfile

multi-arch pipeline runs execute some time after the x86_64 pipeline
runs. Let's make sure they run from the same config git version to
mitigate any drift that could have happened.
This is mostly useful for the devel branches that change often. It's
less likely to affect the prod branches that don't really change much
(especially over time course of a release).
It also isn't really that useful for our mechanical refs that don't have
full lockfile definitions as a change on the yum repo side would still
creep in. Either way it's at least useful for a development refs/branches.

multi-arch-pipeline: drive exact config git commit for arch pipeline runs

---

jobs/multi-arch-pipeline.Jenkinsfile

Messed this up in the last refactor.

multi-arch-pipeline: fix tar call to create kola.tar.xz

---

Jenkinsfile
jobs/multi-arch-pipeline.Jenkinsfile

```
commit 3cdd1f846019e2883989a0557454aaa6fb207db9
Date:   Mon Sep 6 00:09:59 2021 -0400
Revert "Jenkinsfile: limit multi-arch-pipeline to non production builds"
This reverts commit 431f7e8ad33ed3e56d9f8c9fd740c9c0d79f9272.
We want them for production builds now too.
commit 869a78cc49ca232a2dff160870d90aad0e5319f0
Date:   Sun Sep 5 16:28:20 2021 -0400
multi-arch-pipeline: re-enable aws upload/testing
Now that we've hacked in console=ttyS0 (see [1]) now we can
start to upload/test there again.
[1] https://github.com/coreos/fedora-coreos-tracker/issues/920
commit 2307ae760222e8c3d1cca369e1ded8beaf851f73
Date:   Sun Sep 5 16:23:20 2021 -0400
multi-arch-pipeline: hack in …
```

multi-arch-pipeline: final enablement bits for aarch64

---

utils.groovy

This matches `cosa buildupload`. Otherwise the default is too long and
it's not easy for us to invalidate the CloudFront cache. Really, we
should look at folding this back into `cosa buildupload` to maintain our
sanity. E.g. something like
```
cosa buildupload --build ... --arch ... --builds-json-only
```

utils: set max-age on builds.json to 5 minutes

---

streams.groovy

It's now diverged from testing-devel since it's tracking f35.

streams: turn next-devel back on

---

jobs/bump-lockfile.Jenkinsfile

If we end up pushing an update even if no package changed
(see 544a2cc) then we may need to force the cosa build so it doesn't
re-use the previous iteration. If it does that then it will fail
because the previous build had been compressed already:
```
harness.go:1124: Cluster failed starting machines:
lstat /home/jenkins/agent/workspace/bump-lockfile/builds/35.20210909.10.0/x86_64/fedora-coreos-35.20210909.10.0-qemu.x86_64.qcow2.xz:
no such file or directory
```

bump-lockfile: force build if we get there

---

jobs/kola-aws.Jenkinsfile
jobs/kola-gcp.Jenkinsfile
jobs/kola-openstack.Jenkinsfile

The fcosKola library function was changed to default to running basic
qemu tests in [1]. Let's skip those in our cloud provider tests because
obviously we're not testing in qemu.
[1] https://github.com/coreos/coreos-ci-lib/commit/33a06a663519315877e54c9e123627b03ff50826

kola-{aws,gcp,openstack}: don't run basic qemu tests

---

streams.groovy

The `next-devel` stream is on f35 now.

streams: disable `branched` stream

---

jenkins/controller/plugins.txt

It contains a fix for #352. Once the base Jenkins imagestream is updated
in our cluster, we can drop this so we don't lock on 1.33.1.

plugins: bump github to 1.33.1

---

jenkins/controller/plugins.txt

Otherwise, the current version (2.40) is too old for the timestamper
plugin to work with.

plugins: bump workflow-api to 2.46

---

jobs/kola-openstack.Jenkinsfile

Despite extending the timeout to 10 minutes we're still hitting
timeouts waiting for nodes to come up in vexxhost. Reaching out
to the CEO he suggested trying the v3 instances (newer infra) to
see if that helped.
If this doesn't work we can use the equivalent of `--boot-from-volume`
to get EBS like instances (shouldn't take time to copy image to local
compute nodes).

kola-openstack: switch to v3-starter-4 openstack flavor

---

Jenkinsfile.release

In the FCOS release process, we have this step after the release job
runs where we want to wait until the OSTree commit was successfully
imported into the production repo and verify that it can be pulled and
that it's signed (though that last bit is also implicit with the ability
to even pull).
This requires human releasers to download the previous QEMU image, then
run `rpm-ostree upgrade` multiple times until it succeeds, and then look
at `rpm-ostree status`.
This patch enhances the release job to automate all that so that the
releaser just needs to verify the output.
This uses the new `cosa run -x` added in
https://github.com/coreos/coreos-assembler/pull/2338.

release: automate waiting for import and pull test

---

Jenkinsfile
jobs/kola-aws.Jenkinsfile
jobs/kola-gcp.Jenkinsfile
jobs/kola-openstack.Jenkinsfile
jobs/multi-arch-pipeline.Jenkinsfile

This will allow us to only run tests that were for the specific config
repo version that we built against. This prevents issues like what we saw
recently where tests got kicked off later and the config repo had merged
a new change that had a test. The test failed because the test was ran
but the corresponding needed change was not in the built FCOS version.

kola-{aws,gcp,openstack}: use a specific config git commit for tests

---

jenkins/controller/plugins.txt

We're currently at v1.18.1. And while the changelogs don't mention
anything to that effect, let's fast-track the latest and see if it helps
https://github.com/jenkinsci/configuration-as-code-plugin/issues/1646.

plugins: fast-track ssh-credentials v1.19

---

jobs/kola-openstack.Jenkinsfile

We're having some networking issues in ca-ymq-1 right now let's switch
to sjc1 while we investigate. We also needed to switch our instance type
because `v3-starter-4` is not available in sjc1.

kola-openstack: switch to sjc1 region

---

jobs/kola-openstack.Jenkinsfile

The switch to the new region is causing the upload and
image creation to take a lot longer.

kola-openstack: bump timeout to 90 minutes

---

jobs/kola-openstack.Jenkinsfile

The networking issues in the region have now been fixed. According
to the rep: " there was an issue in our internal BGP E-VPN control plane
that was causing this issue, this has been resolved and it's now
working".
Let's switch back to ca-ymq-1 since the infra is a little faster and
instances were less likely to time out there.
This reverts commit c4bdf1f42f70d9ac2bbd5a1ce2825c9d9581b854.

Revert "kola-openstack: switch to sjc1 region"

---

jobs/multi-arch-pipeline.Jenkinsfile

This works around corner cases like described in:
https://github.com/coreos/coreos-assembler/issues/2380

multi-arch-pipeline: tell gangplank to copy the parent build metadata

---

jenkins/controller/plugins.txt

This plugin will make it easier to interact with GitHub. E.g. adding
comments, adding additional CI contexts, etc...
Planning to use this for
https://github.com/coreos/fedora-coreos-tracker/issues/990 but we could
also use this for enhancing other things, e.g. adding a comment with the
RPM diff, or having a separate CI context if a downgrade is detected to
make it easier to tell, etc...

plugins: add pipeline-github

---

Jenkinsfile

This reverts commit 75111d1740eefcc229a25478c605756ca18eda88.
We're done debugging this now. See
https://github.com/coreos/coreos-assembler/pull/2537.

Revert "pipeline: add some debugging info re. umask and permissions"

---

Jenkinsfile
jobs/multi-arch-pipeline.Jenkinsfile

This commit has two changes:
- Pass the COREOS_ASSEMBLER_IMAGE parameter from the main pipeline
when forking off the multi-arch pipeline.
- Default to "localhost/coreos-assembler:latest" in the multi-arch
pipeline when a full quay.io COSA image isn't given. i.e. we don't
want `coreos-assembler:main` to fall through to the multi-arch
builder.

multi-arch-pipeline: fix COREOS_ASSEMBLER_IMAGE image passing

---

Jenkinsfile

Forgot the `value:` in the value passing.

Jenkinsfile: fix parameter passing to multi-arch-pipeline

---

Jenkinsfile
Jenkinsfile.release
jenkins/config/coreos-ci-lib.yaml
jenkins/config/seed.yaml
jenkins/controller/plugins.txt
jobs/bump-lockfile.Jenkinsfile
jobs/bump-lockfiles.Jenkinsfile
jobs/kola-aws.Jenkinsfile
jobs/kola-gcp.Jenkinsfile
jobs/kola-openstack.Jenkinsfile
jobs/multi-arch-pipeline.Jenkinsfile
jobs/sync-stream-metadata.Jenkinsfile
utils.groovy

Update configuration-as-code to 1.54 as it prevented the
Credentials Plugin as others from loading.
Adding pipeline-utility-steps 2.9.0 as is required for the current
Jenkins version to run the pipelines.
Add the coreos-ci-lib global library to the configmap.

plugins: configuration-as-code and pipeline-utility-steps

---

manifests/pipeline.yaml

That way we use the latest pulled cosa image in the internal registry,
which shouldn't be very out of date. This also avoids race conditions
during quay.io rebuilds.

manifest/pipeline: set cosa referencePolicy to `local`

---

jobs/multi-arch-pipeline.Jenkinsfile

We're emitting one on finish but were missing the start one for parity
with x86_64.

multi-arch-pipeline: emit build.state.change fedmsg on start

---

HACKING.md

This came up during deployment of the pipeline in the stage environment.

HACKING: add a link to Jenkins CI Slack app for canonical token

---

Jenkinsfile
jobs/kola-kubernetes.Jenkinsfile
jobs/multi-arch-pipeline.Jenkinsfile

This job will run the new Kubernetes e2e node tests in AWS:
https://github.com/coreos/fedora-coreos-config/pull/1297
Like the other tests, we trigger it as a followup job from the pipeline
jobs.

Add kola-kubernetes job

---

multi-arch-builders/README.md
multi-arch-builders/fcos-aarch64-builder.bu

```
commit 26e8238fb3ac27607cb270c39224b88a05924899
Date:   Wed Nov 10 10:43:36 2021 -0500
multi-arch-builders: use pull-always in container build
This way we don't need the preceding line in the systemd service that
consistently needs to be updated when the Fedora version changes.
commit 169db2da922b034f9a6a077e442c10e59758a54e
Date:   Wed Nov 10 10:34:14 2021 -0500
multi-arch-builders: drop building buildroot image
It was dropped from COSA in:
https://github.com/coreos/coreos-assembler/pull/2550
```

multi-arch-builders: drop building buildroot image

---

jobs/kola-kubernetes.Jenkinsfile

We only want to run the k8s test in this job.

kola-kubernetes: also disable upgrade testing

---

TROUBLESHOOTING.md

This is actually just a way to verify that
https://github.com/coreos/fedora-coreos-pipeline/issues/444 is fixed.

TROUBLESHOOTING: capitalize "Jenkins" and "DNS"

---

jobs/multi-arch-pipeline.Jenkinsfile

It doesn't look like this currently works. Tracked in
https://github.com/coreos/fedora-coreos-tracker/issues/1044.

multi-arch-pipeline: disable kola-kubernetes followup job

---

jobs/kola-openstack.Jenkinsfile

I've got an open ticket with VexxHost about our issues with uploading
images to ams1 and they've bumped our quota in ca-ymq-1 to unblock us
while we figure things out. Let's use ca-ymq-1 for everything for now.

kola-openstack: use ca-ymq-1 region for everything

---

Jenkinsfile

This is failing and needs to be looked at but that won't happen
for a few weeks so let's disable it for now.

Jenkinsfile: disable kola-kubernetes test for now

---

jobs/kola-aws.Jenkinsfile

We saw a regression recently where m6i instances failed to boot on
newer kernels. Add a test here to make sure that continue to boot in
the future.
See https://github.com/coreos/fedora-coreos-tracker/issues/1004

kola-aws: add test on m6i.large instances

---

jobs/kola-aws.Jenkinsfile

Now that https://github.com/coreos/coreos-ci-lib/issues/95 is fixed
we can run these in parallel.

kola-aws: run m4.large and m6i.large tests in parallel

---

HACKING.md
Jenkinsfile.release
jenkins/config/oscontainer-secret.yaml
manifests/jenkins.yaml

This PR is intended to supercede and incorporates elements of: https://github.com/coreos/fedora-coreos-pipeline/pull/383

release: Copy oscontainer to quay.io

---

jobs/bump-lockfile.Jenkinsfile

For x86_64 we run a full test suite and also test the metal images
via an ISO install. Let's gain some parity for aarch64. These steps
were copied from the multi-arch-pipeline.

bump-lockfile: more tests for aarch64

---

manifests/jenkins.yaml

The default is 30 minutes, which is short enough that you sometimes have
to log back in multiple times a day. Let's just bump it to one day.
Closes: #455

manifests/jenkins: bump session timeout

---

Jenkinsfile.release

Jenkins blocks it by default and recommends using single quotes instead
so that the environment variable is substituted by the shell itself.

release: don't use Groovy string interpolation for OSCONTAINER_SECRET

---

jenkins/config/oscontainer-secret.yaml

We want to base64-encode the contents of a file, not the path of the
file itself.

jenkins/config: fix oscontainer-secret formatting

---

jenkins/config/oscontainer-secret.yaml

This reverts commit db97d5674fd82fda76826355a1be9b0a351c2173.
Lessons learned:
- `${oscontainer-secret/dockercfg}` expands to the *contents* of the
path at `/run/secrets/oscontainer-secret/dockercfg`
- therefore, `${readFile:${oscontainer-secret/dockercfg}}` will ask
jcasc to read the file at `$CONTENTS`, which is of course not what we
want.
So the only issue was actually the path typo, which was fixed in #461.
As such, this is not a perfect revert. I also kept the updated
documentation link and added some details to the comment.

Revert "jenkins/config: fix oscontainer-secret formatting"

---

Jenkinsfile.release

We hit this issue where one pipeline run kicked off immediately after
another one had finished. So we had something like:
- next-devel-x86_64#1
- next-devel-aarch64#1
- next-devel-x86_64-release#1
- next-devel-x86_64#2
- next-devel-aarch64-release#1
At the point that the release job runs for `#1` after the aarch64
pipeline is done the builds.json has already been updated with build
ID from the `#2` run. In this case `cosa meta` will look at the meta.json
from the wrong build.
To work around this we need to just be explicit and pass the build
ID directly to `cosa meta`.

Jenkinsfile.release: pass --build to cosa meta

---

multi-arch-builders/README.md
multi-arch-builders/fcos-aarch64-builder.bu

```
commit 38e3d3326bdc8ce28f60b54058c36e3f068838f7
Date:   Wed Feb 2 22:22:29 2022 -0500
multi-arch-builders: use --no-cache when building cosa image
We want it to be fresh. Let's enforce it for now until we can get
consistency by having the nocache line bumped regularly [1].
[1] https://github.com/coreos/coreos-assembler/issues/2636
commit 02b305a8e74119776c2b57822edac521a24d71f8
Date:   Wed Feb 2 22:20:58 2022 -0500
multi-arch-builders: change aarch64 builder disk VolumeType
gp3 disks are a bit more performant so let's use that to try to speed
up some of our tests, especially when the machine is loaded.
```

multi-arch-builders: a few updates

---

jobs/bump-lockfile.Jenkinsfile
jobs/bump-lockfiles.Jenkinsfile
jobs/kola-aws.Jenkinsfile
jobs/kola-gcp.Jenkinsfile
jobs/kola-kubernetes.Jenkinsfile
jobs/kola-openstack.Jenkinsfile
jobs/multi-arch-pipeline.Jenkinsfile
jobs/sync-stream-metadata.Jenkinsfile

Adds the buildDiscarder property to the the jobs to prevent the builds to store unlimited logs and artifacts.

jobs: Add buildDiscarder property to the build pipelines

---

manifests/jenkins-s2i.yaml
manifests/pipeline.yaml

manifests/jenkins-s2i: drop deploy-default references and migrate more annotations to configmap

---

jenkins/controller/plugins.txt

Needed by latest `kubernetes-plugin`.
We should update every other plugin on there, but let's do that
separately when we know we're in a good place.

plugins: bump workflow-api to latest

---

jobs/release.Jenkinsfile

This will make it so we won't send a slack message if we succeeded.

jobs/release: set SUCCESS if we didn't fail

---

jobs/release.Jenkinsfile

The jobs which trigger this job were changed to pass in a boolean, but
the parameter on this job itself was still a string choice. Adapt.
Fixes 4058b24 ("Jenkinsfile.release: move to regular job `release`").

jobs/release: make AWS_REPLICATION a bool

---

multi-arch-builders/fcos-aarch64-builder.bu

```
commit cf047a99901cef93dab3d1cc5f5aa620648d4c34
Date:   Wed Feb 9 21:27:34 2022 -0500
multi-arch-builders: fix ownership of some systemd directories
We need to specify these directories so they get the right
ownership and aren't owned by root.
commit f9c21f0370ca1f8bf0e60e2376494dcc33f7cf46
Date:   Wed Feb 9 21:23:12 2022 -0500
multi-arch-builders: remove --no-cache when building COSA
Now that https://github.com/coreos/coreos-assembler/issues/2636
has been implemented we'll get a cache bump weekly.
```

multi-arch-builders: a few butane config updates

---

jobs/release.Jenkinsfile

I forgot to adapt this when changing the parameter to a proper boolean.
Fixes: https://github.com/coreos/fedora-coreos-pipeline/pull/474

jobs/release: fix AWS_REPLICATION parameter handling

---

jobs/build.Jenkinsfile

We're trying to debug
https://github.com/coreos/fedora-coreos-tracker/issues/1108, but it's
not reproducing locally, nor in CoreOS CI.
Let's add a quick and dirty checkbox that we can activate to have the
pipeline just hold at the place where it would run kola so we can `oc
exec` in and do it ourselves to try to reproduce it in more similar
conditions.

jobs/build: add temporary KOLA_RUN_SLEEP parameter

---

manifests/jenkins-s2i.yaml

Fixes c72b00ce021a ("manifests/jenkins-s2i: migrate more annotations to
configmap").

manifests/jenkins-s2i: drop unused template parameters

---

jobs/build.Jenkinsfile

It's already in `meta.json` so we can't *not* upload it. Otherwise if
there's a build failure before the full upload, it can cause issues.
E.g. a broken link in the build browser and throwing off upgrade tests.
We could remove it from the JSON but that seems unnecessary.

jobs/build: also early archive QEMU image

---

jobs/build.Jenkinsfile

This reverts commit 29e179bcfc3f52a110d867d06c50446de3ff7a99.
This uploads the QEMU image uncompressed, which is not what we want.
See discussions in
https://github.com/coreos/fedora-coreos-pipeline/pull/484.

Revert "jobs/build: also early archive QEMU image"

---

jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile
jobs/release.Jenkinsfile
streams.groovy

Before, we were running the release job multiple times per build: once
for each architecture. This was done by triggering it at the end of both
the x86_64 build and multi-arch builds.
However, it's possible that the x86_64 build fails while the multi-arch
build succeeds. In that case, we don't want to release just for e.g.
aarch64 if the x86_64 build is missing or broken.
Fix this by making only the x86_64 build trigger the release job. This
way, it'll only be triggered once and only if the x86_64 build
succeeded. Add locking in the release job and the multi-arch job to
ensure that the release job cannot execute until the multi-arch job has
completed, whether successfully or not.
This also allows us to hack around issues in the tools used by the
release job which don't fully support …

jobs: only run release job once per build

---

jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile
jobs/bump-lockfile.Jenkinsfile
jobs/kola-aws.Jenkinsfile
jobs/kola-gcp.Jenkinsfile
jobs/kola-kubernetes.Jenkinsfile
jobs/kola-openstack.Jenkinsfile
jobs/release.Jenkinsfile
manifests/pipeline.yaml

This makes it easier for developers to turn off Slack notifications. In
addition, it allows us to drop the try/catch blocks since we know it
should always succeed if attempted.

Add `notify-slack` knob to configmap

---

manifests/pipeline.yaml

Otherwise, `yes` will be treated as a boolean value.
Fixes b1c05455 ("Add `notify-slack` knob to configmap").

manifests/pipeline: stringize `NOTIFY_SLACK` parameter

---

jenkins/config/seed.yaml
jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile
jobs/bump-lockfile.Jenkinsfile
jobs/kola-aws.Jenkinsfile
jobs/kola-gcp.Jenkinsfile
jobs/kola-kubernetes.Jenkinsfile
jobs/kola-openstack.Jenkinsfile
jobs/release.Jenkinsfile
utils.groovy

Rather than shelling out to `oc` multiple times to read configmap knobs,
just read the whole configmap once upfront and parse it into a variable.
This is not only more efficient but also avoids issues with the current
execution environment not necessarily having `oc` available.
I left `developer_prefix` alone for now since we're going to nuke it
anyway.

jobs: load pipeline configmap once upfront

---

jobs/build.Jenkinsfile
jobs/release.Jenkinsfile

This will allow us to specify ADDITIONAL_ARCHES to the toplevel build
job and have it filter all the way through the cascading secondary jobs.
It also means that we're using a single source of truth (the parameter)
for each job rather than mixing the paramater and the additional_arches
definition from `streams.groovy`.

build/release: allow passing arches from toplevel build job

---

jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile

I erroneously thought in 72406a1 that we should change those comparisons
to `null` since `pipecfg['nonexistent']` returns `null`. But actually
the configmap template will always define the key anyway and the default
value is the empty string.

jobs: fix comparison for `src_config_ref`

---

jobs/release.Jenkinsfile

The .split() will give us a Ljava.lang.String where we need it to
be an java.util.ArrayList so we can run .containsAll() and .intersect()
on it. See https://stackoverflow.com/questions/27965351/groovy-arraylist-getting-confused-for-a-string
Fixes 102eec8

jobs/release: force some types to be a List

---

jobs/release.Jenkinsfile

We don't want a green check mark if we fail in a sanity check.
Fixes 8c30e1f

jobs/release: mark job as failed if returning early

---

streams.groovy

Now that `next-devel` is based on Fedora 36 there's no longer any value
to have `branched` around.

Disable `branched` stream.

---

HACKING.md
deploy
jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile
jobs/bump-lockfile.Jenkinsfile
jobs/kola-aws.Jenkinsfile
jobs/kola-gcp.Jenkinsfile
jobs/kola-kubernetes.Jenkinsfile
jobs/kola-openstack.Jenkinsfile
jobs/release.Jenkinsfile
manifests/pipeline.yaml
utils.groovy

The whole concept is a bit confusing and there is a decent amount of
conditional logic in there. If someone needs to do some hacking for
development we'll just give them their own project in openshift and
a fresh s3 bucket in another account. That way there's no risk of
messing with the official releases, but they are exercising similar
code paths.

Drop logic for developer_prefix in pipelines

---

jobs/kola-azure.Jenkinsfile

We were hitting the 45 minute timeout. We have plenty of quota in
azure so let's double the parallelability to 10.

kola-azure: bump kola --parallel to 10

---

jobs/kola-azure.Jenkinsfile

Even at 45 we're still getting close. Let's just move it to 60.

kola-azure: bump timeout to 60 minutes

---

manifests/pod.yaml

This is needed for jobs/build.Jenkinsfile so we can detect when
the Azure secret exists and behave accordingly. I guess this wasn't
needed for jobs/kola-azure.Jenkinsfile because we define the pod
differently with cosaPod() and specify the secret there [1].
This is a fixup to 72f2177.
[1] https://github.com/coreos/fedora-coreos-pipeline/blob/7dde485c8706afbf06ca7da5a6f64a4d2910b63b/jobs/kola-azure.Jenkinsfile#L71-L73

manifests/pod.yaml: add Azure secrets to pod definition

---

jobs/bump-lockfile.Jenkinsfile

I don't quite recall the details of this hack, but I think it had to do
with RPM digests and signing. Though it's been a while now since we've
started stripping digests from lockfiles.
Anyway, let's just drop it for now. If we hit any errors from it, we'll
at least have something to debug.

jobs/bump-lockfile: drop cost=500 hack

---

jobs/build.Jenkinsfile

Going through and adding a new supported build type for virtualbox to cosa.
as per https://github.com/coreos/fedora-coreos-tracker/issues/1008

build.Jenkinsfile: include VirtualBox in build process

---

multi-arch-builders/README.md
multi-arch-builders/fcos-aarch64-builder.bu

```
commit 427c6161cf0556211acbd3cba6d0619e44fc68e0
Date:   Tue Apr 19 13:36:28 2022 -0400
multi-arch-builders: double disk size for aarch64 builder
We've run out of space on occasion. Let's double it to try
to make sure we have plenty of room to wait for our prune
jobs to clean things up.
commit e44d343c878e18a1608a0de9470353b0b7c45969
Date:   Tue Apr 19 13:34:29 2022 -0400
multi-arch-builders: add service to prune dangling container resources
This will allow for aborted builds to get cleaned up and not hog a
bunch of resources.
```

multi-arch-builders: handle disk space issues for aarch64 builder

---

jobs/build-arch.Jenkinsfile
manifests/pipeline.yaml

The latter mirrors to the former, but it's a periodic that runs every
hour. So let's just use the images directly from app.ci for faster
iteration.
Related: https://github.com/coreos/coreos-ci-lib/pull/107

Move from Quay.io to app.ci

---

jobs/build.Jenkinsfile

We're seeing issues where the pipeline sometimes hits EAGAIN on `fork`:
https://github.com/coreos/fedora-coreos-tracker/issues/1186
This may have started happening more frequently after the recent
addition of VirtualBox.
Anyway, it's kinda silly to build that many images in parallel. There's
diminishing returns and eventually a performance cost. So let's do it in
two rounds instead. (Ideally instead it'd be a kind of task pool, but
let's not try to implement that in Groovy.)

jobs/build: cut image building parallelism in half

---

jobs/kola-azure.Jenkinsfile

It happens often that resource groups get leaked. Sometimes this is
because Jenkins times out the job, sometimes for other reasons that
aren't super clear to me. Let's run garbage collection in our jobs
to clean up old resource groups that have outlived their reasonable
lifetime.

kola-azure: add stage for garbage collection of leaked resource groups

---

next-devel/badge.json
next-devel/status.json
streams.groovy

testing-devel and next-devel are now redundant after the Fedora 36
release. Disable next-devel until it becomes useful again.

streams: disable next-devel

---

jobs/kola-openstack.Jenkinsfile

Allow rerun success on openstack platform. The rerun success tag was implemented in https://github.com/coreos/coreos-assembler/pull/2857.
Issue: https://github.com/coreos/coreos-assembler/issues/2853

kola-openstack.Jenkinsfile: Allow rerun success on openstack platform

---

jobs/bump-lockfile.Jenkinsfile

The git repo is under src/config. Without this we get an error
about not being in a git repo. Fixes 237a03b.

jobs/bump-lockfile: fix retrigger logic

---

multi-arch-builders/fcos-aarch64-builder.bu

```
commit 3b8589daaff04eb1c95681641a7602f35f7c7a49
Date:   Tue May 24 09:43:06 2022 -0400
multi-arch-builders: build and prune at a different time of day.
Rather than 00:00 UTC let's push it further back hopefully when
most of our team is either still asleep or already asleep. I've
seen a couple cases recently where the 00:00 UTC runs happen around
the time the `testing-devel` is running for the day from the
bump-lockfile bump and it ends up taking out an intermediate container
and volume used by gangplank.
commit c4d44cfbc77ac96e6cfeeef52de38683751d9cf9
Date:   Tue May 24 09:41:03 2022 -0400
multi-arch-builders: Force writing /etc/hostname
Force /etc/hostname even if the file already exists. I saw this on …
```

multi-arch-builders: force hostname; prune during the night

---

jobs/sync-stream-metadata.Jenkinsfile

Now that we have release notes in the streams repo, also start syncing
it to S3 from which the website will fetch it just like stream metadata.
This will trigger a `stream.metadata.update` message even if only
release notes changed. I'm not aware of any consumers of this today, but
still eventually we should probably split stream/updates/release notes
into separate messages.

jobs/sync-stream-metadata: also sync release notes

---

jobs/sync-stream-metadata.Jenkinsfile

jobs/sync-stream-metadata: fix release notes extension

---

jobs/sync-stream-metadata.Jenkinsfile

Now it's `python3`, not `python`.

jobs/sync-stream-metadata: fix python binary name

---

jobs/bump-lockfile.Jenkinsfile

This is prep for `bump-lockfile` creating lockfiles on new arches like
s390x and eventually ppc64le.

jobs/bump-lockfile: `git add` lockfiles before committing

---

jobs/build-arch.Jenkinsfile

This will allow us to run s390x builds. Right now limited to just
the qemu image.

jobs/build-arch: add s390x spec

---

jobs/build-arch.Jenkinsfile

AWS doesn't support s390x/ppc64le and we don't currently have an
OpenStack environment that supports either of those arches either.

jobs/build-arch: only run AWS/OpenStack tests for aarch64

---

jobs/release.Jenkinsfile

This way we're not reimplementing the "find the ostree container in meta.json"
bits, and we're also now mutating `meta.json` which could lead
in the future into having the base image also be in the stream
metadata.

jobs/release: Use `cosa push-container`

---

jobs/release.Jenkinsfile

Let's simplify this even further and drop the `withEnv` wrapper.
Note we're switching from single to double quotes here. As a result, we
need to escape the `OSCONTAINER_SECRET` variable since it's in the env
only.

jobs/release: drop use of `withEnv`

---

jobs/build.Jenkinsfile
utils.groovy

jobs/build: fix error detection in parallel Kola:QEMU stages
Now that they are nested inside parallel, the `return` doesn't
effectively stop the pipeline run. Let's use `error` instead.
Also add in warnError in the case it fails but we want to continue.
Also add in some extra comments on why the try/catch is needed.
Fixup for 717d960

jobs/build: fix error detection in parallel Kola:QEMU stages

---

jobs/build.Jenkinsfile

The apostrophe in "Don't" ended my single quote early. Just change
it to "Do not".
Fixup for 45af871

jobs/build: Fix typo in description for NO_UPLOAD

---

jobs/build.Jenkinsfile

There's an issue with `flufl.Lock` where it fails when exiting the
locked context with `NotLockedError: Already unlocked` when something
else was trying to lock it.
We'll keep digging into that, but for now let's just unparallelize these
to get releases going again. It doesn't save us much time anyway.

jobs/build: unparallelize keylime hash generation

---

jobs/build.Jenkinsfile

We're trying to debug
https://github.com/coreos/fedora-coreos-tracker/issues/1233 but logs
aren't helping much. We think adding `rd.debug` might help in case it's
e.g. a dracut initqueue issue.
Add a separate test for this on a separate ISO so that we don't affect
the official artifacts.

jobs/build: add temporary iso-live-login UEFI test with rd.debug

---

jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile
jobs/bump-lockfile.Jenkinsfile

We follow this pattern in the RHCOS pipeline, so let's do it here too.
Testing the multipath case may have caught something like
coreos/fedora-coreos-config#1827 before it made it to RHCOS.

jobs: use the 4K testiso tests to test multipath

---

multi-arch-builders/README.md
multi-arch-builders/builder-common.bu
multi-arch-builders/fcos-aarch64-builder.bu
multi-arch-builders/fcos-s390x-builder.bu

90% of the butane config is shared amongst the builders. Let's create
a builder-common.bu to share the common configuration.

multi-arch-builders: create a common butane config

---

jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile
jobs/release.Jenkinsfile
manifests/pod.yaml

It's good practice to be explicit with the requests used by pods, so
let's configure the CPU requests.

jobs: set cpu request for pods

---

jobs/bump-lockfile.Jenkinsfile

- withExistingCosaRemoteSession is loaded into the pipeutils var
- fix spacing on session arg to withExistingCosaRemoteSession

jobs/bump-lockfile: fixups for 18e23b9

---

utils.groovy

Otherwise it's a global binding.
I think this is what's causing what appears to be races where one arch
seem like it's using another arch's session in `bump-lockfile`.

utils: add missing `def`

---

jobs/build-arch.Jenkinsfile

The way kube secrets work is the files are usually symlinks to another
file in the same directory. Let's sync the whole directory so we get
the target file as well.
Also changed the sync definition for the key to be more succinct.

jobs/build-arch: Fix copy over of fedmsg.toml

---

jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile

Also rework a bit the structure of the "parallel" invocation
for testiso.

jobs/{build,build-arch}: don't run metal4k tests on s390x

---

jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile

Otherwise we need to sync some stuff back first and so far we haven't
had to do that.

jobs/build-arch: run the releng tasks on the remote too

---

jobs/bump-lockfile.Jenkinsfile

With 354762e this is no longer needed because the buildfetch happens
on the remote builders.

jobs/bump-lockfile: remove remote-session sync

---

jobs/bump-lockfile.Jenkinsfile

I was seeing some issues where the `arch` variable was getting
evalated lazily and all three of my parallel runs were all executing
against the same architecture. Adding a locally scoped arch variable
seems to fix it.

jobs/bump-lockfile: use locally scoped arch var

---

jenkins/config/k8s-plugin-tweaks.yaml

The Kubernetes plugin enforces a maximum number of concurrent
connections to the Kubernetes API server to avoid crowding it. Once the
limit is reached (the default is 32), connection requests are queued and
wait until an existing connection is terminated. Pending connection
requests can time out after the configured interval (the default is 5s)
if not serviced. Such timeouts manifest as the following error:
io.fabric8.kubernetes.client.KubernetesClientException: not ready
after 5000 MILLISECONDS
For each `sh` step executed in a pod that's *not* the JNLP container, a
Kubernetes connection is allocated. In our pipeline, the `build` job
runs everything in the cosa container. We have sections where many
`sh` steps are executed in parallel (the `cosa buildextend-${it}`
closures), and if …

jenkins/config: bump kubernetes-plugin maxRequestsPerHost

---

jenkins/config/k8s-plugin-tweaks.yaml

This reverts commit fc3532704a0c3082810d34ca461d52747a53150a.
The intention is good, but we can't do this via JCASC because it
clobbers the existing `openshift` cloud configuration instead of merging
it in.

Revert "jenkins/config: bump kubernetes-plugin maxRequestsPerHost"

---

jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile
jobs/release.Jenkinsfile
manifests/pod.yaml

With the recent changes in https://github.com/coreos/coreos-assembler/pull/2975
we now need to set a cpu request limit.

jobs/{build,build-arch,release}: set cpu limit

---

manifests/jenkins.yaml

By default, when using a PVC, the OpenShift S2I Jenkins image only
instantiates templates on the first run. This however means that
configuration state can accumulate in the PVC.
Set the `OVERRIDE_PV_CONFIG_WITH_IMAGE_CONFIG` env var which tells the
S2I run script to always instantiate and copy in templates. This
*should* preserve build logs.
An example of this is the Kubernetes cloud config, which was lost in a
recent change (see #583).

manifests/jenkins.yaml: set OVERRIDE_PV_CONFIG_WITH_IMAGE_CONFIG

---

jobs/build-cosa.Jenkinsfile
manifests/pipeline.yaml

```
commit 0503f33d7f60ec1982280c653c551351ecc6bcee
Date:   Wed Aug 3 21:25:10 2022 -0400
manifests/pipeline: use image from quay.io for our imagestream
Forgot to update this previously.
commit 183bf751d03e90b7e5301a992ecba3226d6b8ec3
Date:   Wed Aug 3 21:24:06 2022 -0400
jobs/build-cosa: fixup description and slack messages
Update the first to mention the shortcommit and that we are waiting
on the lock. Update the latter to have the @shortcommit syntax.
```

manifests/pipeline: use image from quay.io for our imagestream

---

HACKING.md
deploy
jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile
manifests/jenkins-agent.yaml
manifests/jenkins-s2i.yaml
manifests/pipeline.yaml
manifests/pod.yaml

We're working on getting this pipeline working internally. The first
thing we hit is that Red Hat has its own internal root CA.
We'll need to handle this both for cosa and the Jenkins agent which
wants to fetch `remoting.jar` from the controller as soon as it starts.
This patch handles just the latter for now. We do this by optionally
supporting building our own Jenkins agent with the certificates in it.
For cosa, I think we will be able to work around this by directly
pointing e.g. git and libdnf at the certificate.

Add support for additional root CA certs

---

manifests/jenkins.yaml

This reverts commit 086c56ea2320d0f711ba5f32ed55caa9294ed1e9.
This helped us recover access to the Kubernetes API server, but it's not
a great default because it means we lose everything anytime Jenkins is
restarted for any reason (e.g. pipeline or cluster updates). We do want
to reprovision from scratch more often, but we need to first move off of
the Jenkins SCM webhook handling, which is not friendly to frequent
reprovisioning.

Revert "manifests/jenkins.yaml: set OVERRIDE_PV_CONFIG_WITH_IMAGE_CONFIG"

---

jobs/build-cosa.Jenkinsfile

Everytime we lose jenkins history it tries to build COSA
4.1 through 4.11 all over again. Let's limit it to `main`
for now and investigate using the Generic Webhook Trigger
plugin [1] next week.
[1] https://plugins.jenkins.io/generic-webhook-trigger/

build-cosa: just build against main for now

---

jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile

```
commit c9fc772f7c17d77b94b6254cbab0888d63c7e736
Date:   Thu Aug 4 19:23:35 2022 -0400
jobs/build: request as many CPUs as parallel VMs
Right now we're running with `--parallel 5` and run the upgrade tests in
parallel, but only have 4 CPUs. This causes some heavier tests to fail.
Let's request as many CPUs as we run VM tests in parallel. Since the
latter is calculated from the memory request, that's what we do.
In effect, this bumps up our CPU requests to 6.
```
```
commit 04cb8c388688cfb4a11f1db1381aca2a37998df6
Author: Jonathan Lebon <jonathan@jlebon.com>
Date:   Fri Aug 5 11:21:12 2022 -0400
jobs/build: run reprovision tests not in parallel
Those tests take 4G of RAM each and are heavy in I/O. Run them serially
to stay within our declared memory request and minimize the chances of …
```

jobs/build: request as many CPUs as parallel VMs and run reprovision tests serially

---

jenkins/config/fcos-ppc64le-builder.yaml
manifests/jenkins.yaml
multi-arch-builders/README.md
multi-arch-builders/fcos-ppc64le-builder.bu

We have a builder so should start using it.

multi-arch-builders: add ppc64le builder info

---

jobs/build-cosa.Jenkinsfile

The cosa image we build is used to trigger internal RHCOS multi-arch
rebuilds (and in the near future will be used directly once we have all
the arches built). But the stack on the target cluster is too old to
understand OCI, so we get:
Internal error occurred: missing signature key
Add `--v2s2` to push in v2s2 format.
Once we've rebased RHCOS to the FCOS pipeline, we should be able to
revert this.
Related: https://github.com/coreos/coreos-assembler/pull/2726

jobs/build-cosa: push in v2s2 format

---

jobs/build-cosa.Jenkinsfile

We'll add this into streams.additional_arches soon, but for now let's
default to having the build-cosa job build for ppc64le.

jobs/build-cosa: build COSA container for ppc64le

---

jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile
jobs/bump-lockfile.Jenkinsfile

If an upgrade fails we have a parameter for allowing the build to
continue. Let's detect this case and give an appropriate slack
message and color.

print warning message to slack if `UNSTABLE`

---

jenkins/controller/plugins.txt

This plugin can automatically import Kubernetes secrets with a certain
label into Jenkins. This will allow us to drop secret definitions
defined in a bunch of places (Jenkins template, JCASC dropins, and cosa
pod template).

plugins: add kubernetes-credentials-provider

---

jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile
jobs/bump-lockfile.Jenkinsfile

Since we have a kola basic tests stage where we separately run the
basic tests, let's denylist them when we run the rest of the kola
tests.

don't run kola basic tests twice

---

jobs/bump-lockfile.Jenkinsfile

This way we don't need to maintain two separate lists.

jobs/bump-lockfile: make arch list based on streams.additional_arches

---

utils.groovy

This new helper will be useful together with the new
`kubernetes-credentials-provider` plugin to only run a block of code if
a given Jenkins credential exists.

utils: add `tryWithCredentials` function

---

HACKING.md
deploy
jobs/build.Jenkinsfile
jobs/bump-lockfile.Jenkinsfile
manifests/jenkins-agent.yaml
utils.groovy

Roughly, this series documents how to create a secret for the root CA usable with kubernetes-credentials-provider, and then uses the auto-created secret in the pipeline to optionally have it added to the cosa container (relying on https://github.com/coreos/coreos-assembler/pull/3032).
See individual commit for more details.

Rely on new kubernetes-credentials-provider plugin for root CA cert and inject it into cosa container

---

deploy
manifests/jenkins-agent.yaml

Too much Rust.
Fixes 88a769a ("Simplify root CA cert provisioning").

deploy: fix `has_additional_root_ca()` return value

---

jobs/build-cosa.Jenkinsfile
jobs/build-fcos-buildroot.Jenkinsfile

Along with some enhancements to `build-cosa`.
```
commit 612d3902d0142491a26ed5d9770daf99f235945a
Date:   Thu Sep 1 18:17:22 2022 -0400
add build-fcos-buildroot job
This job will build the fcos-buildroot container and push it to quay
at quay.io/repository/coreos-assembler/fcos-buildroot
Fixes https://github.com/coreos/fedora-coreos-config/issues/1950
commit d5431a8f419c18af1b31a6b2241c70452336617b
Date:   Thu Sep 1 20:47:49 2022 -0400
jobs/build-cosa: pass --cache-ttl to remote-build-container
This option exists in podman now and we can use it to make it so
our builders don't hit yum repos many times a day.
commit f592875461da04c88ec6998f17058b16a89292e6
Date:   Thu …
```

add build-fcos-buildroot job

---

jobs/build-fcos-buildroot.Jenkinsfile

This isn't the build-cosa job so we shouldn't report errors
that way.

jobs/build-fcos-buildroot: fix slack message topic

---

jobs/build.Jenkinsfile

```
commit fe2634dafe8202fdd01161c3ac8c8b5f564bb044
Date:   Tue Sep 6 23:38:48 2022 -0400
jobs/build: warn when workaround for iso-live-login is detected
For now we want to notify ourselves when this workaround is observed. It won't
fail the build, just give us information. See
https://github.com/coreos/fedora-coreos-tracker/issues/1233
commit 8f4ada8c3c9774c1ad105e55179e3bb362e3032f
Date:   Tue Sep 6 22:42:43 2022 -0400
jobs/build: drop the extra testiso with rd.debug test
It turns out that passing in `--qemu-iso` to `kola testiso` doesn't
work. See https://github.com/coreos/coreos-assembler/issues/3071
This effectively reverts 34c0d2c.
```

jobs/build: warn when workaround for iso-live-login is detected

---

jobs/kola-azure.Jenkinsfile

We keep bumping up into the timeout here. Let's increase it by 15 minutes to try to handle this.

jobs/kola-azure: bump timeout to 75 minutes

---

HACKING.md
jenkins/config/generic-webhook-trigger.yaml
jenkins/controller/plugins.txt
jobs/build-cosa.Jenkinsfile
jobs/build-fcos-buildroot.Jenkinsfile

```
commit 8cbed1420b2192549bb298754015105c97c578cf
Date:   Sun Sep 11 09:06:10 2022 -0400
HACKING: document generic webhook setup in GitHub
This explains what values to use when setting up a webhook in GitHub
for the jobs that are using the Generic Webhook Trigger plugin.
commit 9101e2b66d8ab797a5ede43796550112da6f25cd
Date:   Sat Sep 10 11:05:43 2022 -0400
jobs/build-cosa: use the Generic Webhook Trigger plugin
This plugin allows us to get the exact branch name from the webhook
payload itself and use that when doing a build. The githubPush()
method we were using previously would only trigger the job to happen
but then the job could select any possible branch that hadn't been
built recently to build. This …
```

Add and use generic-webhook-trigger plugin

---

jobs/release.Jenkinsfile

What I had wasn't properly expanding the `basearch` groovy variable and was passing `$basearch` directly to bash and failing with unbound variable. There is some code right below this that uses collect to do the same thing so let's just re-use that here.
Fixes 08dcb09.

jobs/release: fix --arch parameter to `cosa push-container-manifest`

---

HACKING.md
jenkins/config/fedora-push-registry-secret.yaml
jobs/release.Jenkinsfile
manifests/jenkins.yaml

Also keep old location active for now.
Fixes https://github.com/coreos/fedora-coreos-tracker/issues/1171

jobs/release: move oscontainer to quay.io/fedora/fedora-coreos

---

config.yaml
jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile

Since it was set it was overriding the stream every time the `build` job would run. This is kind of confusing behavior. Let's get rid of it and just force people who are hacking to use the real branch names, but in their fork.

jobs/{build,build-arch}: drop src_config_ref

---

config.yaml
jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile

No need to hard code this into the jobs any longer. Let's drain this value into the config itself.

jobs/{build,build-arch}: drain AWS test account ID into config

---

jobs/build-development.Jenkinsfile
jobs/build-mechanical.Jenkinsfile

streams.development and streams.mechanical went away. Let's use the variable that was intended for us to use for this.
Fixes 314f02f.

jobs/build-{development,mechanical}: fix variable usage

---

config.yaml
jobs/build-arch.Jenkinsfile

```
commit a75cdfdac686da8e1058c4e0d3d75edbcf336064
Date:   Fri Sep 16 09:51:18 2022 -0400
jobs/build-arch: only patch gf-set-platform in the FCOS pipeline
This patch is a temporary hack, but it's still around for now and
we need to start supporting the RHCOS pipeline. Let's conditionalize
the patch on if we are operating on the FCOS pipeline.
commit d5563b7cf57bfb1b29b49717fca3f672ca303708
Date:   Fri Sep 16 09:46:08 2022 -0400
config: add toplevel type: config setting
This will allow us to use this information in the pipeline to perform
certain actions or not.
commit adc6f865e1a7348773c0b541888da4c18fbd081d
Date:   Thu Sep 15 15:39:35 2022 -0400
jobs/build-arch: …
```

support older COSA versions for multi-arch building

---

HACKING.md
jenkins/config/aws.yaml
jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile
jobs/bump-lockfile.Jenkinsfile
jobs/kola-aws.Jenkinsfile
jobs/kola-azure.Jenkinsfile
jobs/kola-gcp.Jenkinsfile
jobs/kola-kubernetes.Jenkinsfile
jobs/kola-openstack.Jenkinsfile
jobs/sync-stream-metadata.Jenkinsfile
manifests/jenkins.yaml
manifests/pod.yaml

```
commit 98acd23193246cf17a89c085f3003ebfa07081ce
Date:   Fri Sep 16 16:09:37 2022 -0400
jobs/build-arch: fix indentation
commit 32333c021068c0f926b3657eb0f2961535a7925f
Date:   Fri Sep 16 15:45:34 2022 -0400
treewide: rename AWS credentials
This does the following rename:
- aws-fcos-builds-bot-config -> aws-build-upload-config
- aws-fcos-kola-bot-config -> aws-kola-tests-config
It is a further attempt to remove "FCOS" from any names in the pipeline.
commit a6b2649319d61fa53b337db74fc5665f5aef4a31
Date:   Fri Sep 16 14:30:11 2022 -0400
treewide: remove hardcoded `fcos-builds` bucket
We should be getting this from the configured s3_bucket in
config.yaml.
commit …
```

More removal of FCOS specific naming

---

jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile
jobs/release.Jenkinsfile
jobs/sync-stream-metadata.Jenkinsfile

We've moved the scripts we need from that repo to cosa, so stop cloning the repo and use the ones from the cosa directory instead.
Requires: https://github.com/coreos/coreos-assembler/pull/3113

tree: stop cloning releng-automation repo, use cosa

---

jobs/build-arch.Jenkinsfile

The function was renamed so this reference no longer worked.

jobs/build-arch: fix call to get_artifacts_to_build()

---

utils.groovy

If default_artifacts or additional_atifacts are empty then we'll get `null` in the list of artifacts. Let's fix that.

utils: fix null entry in list of artifacts

---

HACKING.md
jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile
jobs/kola-azure.Jenkinsfile
jobs/kola-gcp.Jenkinsfile
jobs/kola-openstack.Jenkinsfile
manifests/pod.yaml

```
commit a17efa6f0baa76caac88bf6771d8eef5f21289a4
Date:   Tue Sep 27 21:28:39 2022 -0400
treewide: migrate Azure credentials/secrets to kube creds plugin
Similar to what was just done for AWS, GCP, and OpenStack. This one
was a little more complicated because there are two files needed:
azureProfile.json and azureAuth.json. Since the kube credentials
jenkins plugin doesn't handle multiple files in a single secret very
well I just broke them out into separate secrets.
commit c93f4acbee2d5966b24aa3cd40ad3822073656d0
Date:   Tue Sep 27 21:07:29 2022 -0400
treewide: migrate OpenStack credentials/secrets to kube creds plugin
Similar to what was just done for AWS/GCP.
commit …
```

updates for GCP/OpenStack/Azure AWS registry secrets/config

---

HACKING.md
configs/fedmsg.toml
jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile
jobs/release.Jenkinsfile
jobs/sync-stream-metadata.Jenkinsfile
manifests/pod.yaml
utils.groovy

This commit does several things:
- Converts the fedora-messaging-cfg secret (now fedora-messaging-config) into a secret rather than a configmap so it can be dynamically loaded with withCredentials and not required to be hard mounted into the pods.
- Sets up a new fedora-messaging-coreos-x509-cert secret (was fedora-messaging-coreos-key) in the x509ClientCert type for the kube credentials plugin.
- Removes the old configmap/secret mounts from the COSA pod.yaml
- Switches configs/fedmsg.toml to have a templated string `FEDORA_MESSAGING_X509_CERT_PATH` that will be substituted out at runtime with the actual path of the files.
- Adds tryWithMessagingCredentials() to aid in setup/use of the config and secrets for fedora messaging.

treewide: convert fedora messaging credentials to support k8s creds plugin

---

HACKING.md
jenkins/config/slack.yaml
manifests/jenkins.yaml

~~Also add `trySlackSend()` function, use it across the tree~~

treewide: migrate slack-api-token for use with k8s creds plugin

---

HACKING.md
configs/fedmsg.toml
utils.groovy

The version of the Kubernetes Credentials Provider plugin that we
are on right now doesn't support x509ClientCert yet. Let's use two
separate secretFile secrets instead.

treewide: use secretFile for fedora messaging creds

---

utils.groovy

We run with `set -u` so we need to provide a default value if `COREOS_ASSEMBLER_REMOTE_SESSION` is not defined.
Fixes ebdec22 ("treewide: convert fedora messaging credentials to support k8s creds plugin").

utils: fix undefined `COREOS_ASSEMBLER_REMOTE_SESSION` handling

---

HACKING.md
jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile
utils.groovy

- jobs/build: unparallel the cloud image upload/creation for now
- utils: fix more variables in tryWithMessagingCredentials
- Revert "jobs/build-arch: emit ostree import request from controller"
- HACKING: fix fedora-messaging secrets definition

A few minor pipeline fixes that should get us working again

---

HACKING.md

In GitHub, we'll insert the secret without a newline, so we need to make sure that we don't have a newline here either.

HACKING.md: ensure webhook secret has no newline

---

config.yaml
jobs/build-arch.Jenkinsfile

Let's not have code that explicitly switches on FCOS vs RHCOS in the pipeline. Instead, let's try to take each instance on a case-by-case basis and formalize the distinction they're trying to express at a higher level.
In the case of the aarch64 serial console issue, we'll get that via the recent `platforms.yaml` work. For now, to not regress let's introduce a temporary knob to activate the AWS aarch64 serial console hack.

config.yaml: drop `type: fcos` knob

---

jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile
utils.groovy

```
commit 013056891e212d6e37ec5caae48f1349310f3c4a
Date:   Mon Oct 3 16:40:38 2022 -0400
jobs/build: support yumrepos knob in pipecfg
Now that `cosa init` has a concept of "yumrepos", wire that through from
the pipecfg so that RHCOS can make use of it.
```
```
commit bf1051d8e796f67f3606ee794e9204f802a0381b
Date:   Mon Oct 3 17:06:05 2022 -0400
jobs/build-arch: add root CA on remote workers
Remote workers also need to be able to access e.g. the yum repos.
Propagate any configured root CA in the controller cosa into the worker
cosa.
```

jobs/build: support yumrepos knob in pipecfg and add root CA on remote workers

---

HACKING.md
deploy
jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile
jobs/release.Jenkinsfile
manifests/jenkins-agent.yaml
manifests/jenkins-s2i.yaml
manifests/jenkins.yaml
manifests/pipeline.yaml
manifests/pod.yaml

Because of the additional root CA, we need the ability to optionally set
up a BuildConfig that will layer the root CA onto the base jenkins-agent
image.
However, the way we did this was exposing this choice to the Jenkins
jobs where they had to know which tag to use. This becomes cumbersome if
we also want to make use of coreos-ci-lib helpers.
Rather than trying to plumb that all the way through, we change tactics:
1. set a system property telling the Kubernetes plugin to default to our
Jenkins agent imagestream tagged `:latest`
2. default `:latest` to be the base OpenShift Jenkins agent image
3. if an additional root CA is provided, make `:latest` be the output of
the `jenkins-agent` BuildConfig
That way, jobs no longer have to set any explicit Jenkins agent image,
and the Kubernetes …

Rework jenkins-agent handling

---

jobs/build-arch.Jenkinsfile
jobs/build-fcos-buildroot.Jenkinsfile
jobs/build.Jenkinsfile
jobs/bump-lockfile.Jenkinsfile
jobs/kola-aws.Jenkinsfile
jobs/kola-azure.Jenkinsfile
jobs/kola-gcp.Jenkinsfile
jobs/kola-kubernetes.Jenkinsfile
jobs/kola-openstack.Jenkinsfile
jobs/release.Jenkinsfile
jobs/sync-stream-metadata.Jenkinsfile

Stop fishing values out of `pipecfg` into separate variable and get in
the habit of referencing `pipecfg` directly instead.

jobs: drop unnecessary pipecfg aliases

---

jobs/kola-aws.Jenkinsfile

```
commit fc19699a056b4f195972413abd9868b8b7ca96c2
Date:   Tue Oct 4 11:27:37 2022 -0400
jobs/kola-aws: switch Xen test to i3.large to verify NVME
Since we had a user report of broken NVME on i3.large let's switch
our Xen test to that instance type and verify the NVME device works
there. Also add in a test to make 100% sure we chose a Xen instance.
commit 45fe3510a5846f3388a40cc559558c9dd1c55fd7
Date:   Tue Oct 4 10:11:34 2022 -0400
jobs/kola-aws: parallelize tests
We don't typically have problems with quota on AWS so let's run all
these in parallel. It has a few benefits:
1. Faster
2. If a test in Kola:Full fails because of a flake we still get the
other tests (Xen, Ice Lake, Graviton3) to run. So we can …
```

jobs/kola-aws: parallelize tests; switch xen to i3.large

---

jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile

RHCOS uses a different naming scheme from FCOS. Support a new `ref` member under `source_config` and also per-stream overrides (for the `master` branch).
```yaml
source_config:
url: https://github.com/openshift/os
ref: release-${STREAM}
streams:
4.12:
source_config_ref: master
```

jobs/build: templatize source config ref to use

---

HACKING.md
manifests/jenkins-agent.yaml
manifests/jenkins-s2i.yaml
manifests/jenkins.yaml
manifests/pipeline.yaml

```
commit 0424601f087fb4143fa280830d3bf20c2db30132
Date:   Wed Oct 5 22:13:30 2022 -0400
manifests: add app=coreos-pipeline label to some objects
This should help clean more things up when trying to follow the
documentation at https://github.com/coreos/fedora-coreos-pipeline/blob/main/HACKING.md#nuking-everything
commit d0ab10453d6d319eb411a7dee717dd8ecfb39929
Date:   Wed Oct 5 22:11:34 2022 -0400
treewide: fedora-coreos -> coreos-pipeline in some labels/descriptions
This advances the recent efforts to make the pipeline naming more
generic so it doesn't feel so specific to Fedora CoreOS. In the case
we replace "Fedora CoreOS" in various places with "CoreOS Pipeline".
```

treewide: fedora-coreos -> coreos-pipeline in some labels/descriptions

---

manifests/jenkins.yaml

The imagestream already has the local lookupPolicy enabled, so this already works. That way we avoid hardcoding the registry name.

manifests/jenkins.yaml: use imagestream name for jenkins-agent

---

utils.groovy

Fixes 99c69fb ("utils: also sync root CA to remote cosa").

utils.groovy: fix path to CA certificates

---

utils.groovy

We can't use `cosa remote-session sync` here because we are running on the remote as the unprivileged builder user and not in the root group. Workaround with `sudo`.
Fixup for 99c69fb

utils: fix remote copy for addOptionalRootCA

---

jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile
jobs/release.Jenkinsfile

In fa556b2 ("convert remaining jobs to use cosaPod"), we changed scopes so that the cosa container no longer covered the `finally` block. But we emit a fedmsg there with the final result of the job, so we do still need the cosa container. Fix this by re-ordering the scopes again.

jobs: fix `cosaPod` scope and reorder

---

utils.groovy

We need the trailing slash here so that rsync copies the contents of the directory rather than the directory itself into the new directory.

utils: fix rsyncing X.509 fedmsg cert directory

---

config.yaml

I think we can drop this now that we have `next-devel` on F37. We'll re-enable it if we find a good reason to.

config: disable branched stream

---

docs/config.yaml

We're adding a lot of keys to `config.yaml` right now. We need to make sure we do a proper job of documenting them so that it's easier for others to make use of the file.
Let's document the keys we currently support and from now on require any new keys to be documented there.

docs: document config.yaml schema

---

docs/config.yaml
utils.groovy

- Instead of using additional artifacts use skip artifacts, in this way the default artifact list will use the artifact list from the latest version and not the old.
Signed-off-by: Renata Ravanelli <rravanel@redhat.com>

utils.groovy: Change `additional_artifacts` to `skip_artifacts`

---

jobs/build.Jenkinsfile
jobs/kola-aws.Jenkinsfile
jobs/kola-azure.Jenkinsfile
jobs/kola-gcp.Jenkinsfile
jobs/kola-kubernetes.Jenkinsfile
jobs/kola-openstack.Jenkinsfile

Now that we set the memory limit as well we find out we're using more than we are requesting. Let's request a more appropriate amount of memory for our jobs.
For the build job we set it to 8.5 Gi because we run two testiso runs
at the same time and those can take up to 4Gi each.
For the kola-* jobs the request is updated to 1Gi if the job is going
to download and decompress the disk image artifact and 512Mi otherwise.

jobs/{build,kola*}: bump memory requests

---

jobs/build.Jenkinsfile

Some of the tests require 1.5G of RAM now due to
https://bugzilla.redhat.com/show_bug.cgi?id=1907030. We need to bump our calculation of parallelism accordingly in the absence of https://github.com/coreos/coreos-assembler/issues/3118. Otherwise depending on how kola schedules tests, we might go over the limit.

jobs/build: bump per-VM memory requirement to 1.5G

---

jobs/bump-lockfile.Jenkinsfile

This is applying 158e468 and 65079cf to the bump-lockfile job.

jobs/bump-lockfile: update memory/ncpu calculations

---

config.yaml

The Typhoon project requested this and it worked for me the last time I tried so we might as well start creating the file.

config: start producing azure artifacts for aarch64

---

jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile

We've structured our artifact builds into two runs and we've also gone to some effort to put the metal and metal4k builds into the first run and the live ISO build into the second run (since the ISO depends on the metal/metal4k). The way we had it before if you trimmed down your list such that you were only building metal/metal4k/live then you'd end up with metal in the first run and metal4k/live in the second run, which fails for obvious reasons. Let's flip that so that metal and metal4k will be in the first run.

jobs/{build,build-arch}: fix off by one issue with artifact builds

---

jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile
jobs/bump-lockfile.Jenkinsfile
jobs/kola-aws.Jenkinsfile
jobs/kola-azure.Jenkinsfile
jobs/kola-gcp.Jenkinsfile
jobs/kola-kubernetes.Jenkinsfile
jobs/kola-openstack.Jenkinsfile

With recent updates to coreos-ci-lib [1] we can now using the kola() and kolaTestIso() functions even for multi-arch. This enables us to share code for kola tests across the three places that had heavily duplicated code in the past.
[1] https://github.com/coreos/coreos-ci-lib/pull/120

jobs/{build,build-arch,bump-lockfile}: start using kola() kolaTestIso()

---

jobs/build-cosa.Jenkinsfile

I've seen this job fail a few times today with:
```
[2022-10-19T20:00:25.440Z] + cosa remote-build-container --arch x86_64 --cache-ttl 24h --git-ref 32062fd522296e8b74199b2841697c85f26733c8 --git-url https://github.com/coreos/coreos-assembler.git --repo quay.io/coreos-assembler/staging --push-to-registry --auth=****
[2022-10-19T20:00:28.690Z] 2022-10-19 20:00:28,214 INFO - Translated https://github.com/coreos/coreos-assembler.git#32062fd522296e8b74199b2841697c85f26733c8 into 32062fd
[2022-10-19T20:00:28.690Z] 2022-10-19 20:00:28,215 INFO - Targetting a container image for quay.io/coreos-assembler/staging:x86_64-32062fd
[2022-10-19T20:00:28.690Z] 2022-10-19 20:00:28,215 INFO - Running command: ['podman', 'search', '--list-tags', 'quay.io/coreos-assembler/staging'] …
```

jobs/build-cosa: bump memory request to 512Mi

---

jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile
utils.groovy

```
commit 6427fd9113ce38ff545a094d7317f2459bae7203
Date:   Fri Oct 21 00:49:17 2022 -0400
jobs/{build,build-arch}: add stage names for kola runs
This should make the output in our blue ocean pipeline view
a bit easier to view.
commit 6ba3b0a9dd18255a63e596df0866761abd2cdf13
Date:   Fri Oct 21 00:46:09 2022 -0400
jobs/{build,build-arch}: only run tests if artifacts exist
Let's conditionalize running ISO tests and cloud tests if the
necessary artifacts for those tests exist in our build metadata
for the current run.
Structuring it like this enables us to easily comment out artifacts
in the pipeline config.yaml and seamlessly disable running the tests
for the artifact rather than having to comment out code. …
```

Use new credentials functions; limit cloud test run logic

---

jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile
utils.groovy

Hoist the code used to build the secondary artifacts into our
pipeline utils.groovy file so we can share that code between the
two main jobs. Also rework it a bit to use a different maxRuns
heuristic to achieve the same goal it had before.

utils: add build_artifacts() function; use it

---

HACKING.md
config.yaml
docs/config.yaml
jobs/release.Jenkinsfile
utils.groovy

Those are two containers we need to push in RHCOS that's not in FCOS.
Expand the list of supported keys in `registry_repos` for those and
accordingly rework the logic in the release job to be more functional.
Make it automatically skip containers that weren't actually built (e.g.
`extensions` are not built on FCOS and RHCOS <= 4.11).
Support stream-specific additional `registry_repos` so that RHCOS <=
4.11 can specify the `registry.ci.openshift.org` location, which is no
longer needed in 4.12.
Add a new `add_build_tag` which is required to ensure that the pushed
images are not garbage-collected.
Use the new `cosa copy-container` which knows to "unmanifest list" when
copying from Quay.io to `registry.ci.openshift.org`.

Add support for pushing extensions container and legacy oscontainer

---

jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile

The key in the meta.json is `amis`, not `aws`.
Fixes 0779a76.
Also add emoji to build-arch job aws build stage.

jobs/{build,build-arch}: fix AMI detection logic for cloud test

---

jobs/release.Jenkinsfile

Actually just remove the quotes here as they aren't needed.
Fixes f2d2628

jobs/release: fix missing closing quote in GCP image promotion

---

utils.groovy

In the case where we're not building live artifacts we were passing in a maxRuns value of `null` to the utils.ParallelRuns() function. Let's add a condition such that we'll set it to 10 if maxRuns is still uninitialized (`null`).
Fixes 8af6653

utils: set maxRuns to 10 when not building `live` artifacts

---

config.yaml
docs/config.yaml
jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile
utils.groovy

```
commit 197e3cd3f5f7595e1974e7607c5f91dd8c91e28e
Date:   Fri Oct 21 23:12:32 2022 -0400
config: add cloud.test_architectures key
This key is used to limit which architecures we attempt to run cloud
tests for on a given cloud/platform. For example, we create OpenStack
artifacts for every architecture, but we don't have an OpenStack that
we can test in that has all of those architectures so we need to limit
the architectures that those tests are attempted on.
commit 8648df677b414e181e0997d2b2f1e4900b17f4d8
Date:   Fri Oct 21 22:35:34 2022 -0400
factor out cloud test kickoff into run_cloud_tests() function
This code is now pretty much duplicated. Let's factor it out and
simplify it.
```
Requires #705

factor out cloud test kickoff into run_cloud_tests() function

---

jobs/build-arch.Jenkinsfile

```
commit 7dad35b6a47e5dae47f6a928514d4a17090cfe1b
Date:   Sat Oct 22 09:07:18 2022 -0400
jobs/build-arch: aws_aarch64_serial_console_hack check sooner
With the current logic a pipeline needs to exclude `aws` in the list
of artifacts it includes in the config.yaml even if it doesn't need
the hack. Let's re-work the logic so pipelines that don't need the
hack don't need to exclude `aws` in the aarch64 artifact list. This
also means those pipelines won't need to be updated when the hack
is removed.
commit 67c9fca26f8ae0e73ddec054e945f234973a61fe
Date:   Sat Oct 22 09:01:00 2022 -0400
jobs/build-arch: break aws cloud upload stage out
Right now with it nested under a `Cloud Upload` stage it won't
show up in the …
```

enhancements for build-arch aws stage

---

config.yaml
docs/config.yaml
utils.groovy

Every arch supports metal, metal4k, live, and openstack artifacts.
Instead of repeating it four times, add support for a generic "all" key
which is merged on all arches.
Prep for adding more artifacts in that key.

config.yaml: support artifacts in common for all arches

---

utils.groovy

We're hitting up against memory limits when building the legacy oscontainer in the RHCOS pipeline. Before bumping our request higher, I'd like to try first reducing slightly our parallelism. (Worth noting that pipeline currently builds 14 artifacts, so this will still keep us within 2 parallel runs, but better distributed.)

utils: lower artifact building parallelism to 8

---

libupload.groovy

```
commit 6413b25f8ae3bb8fd995d3913e8a65b96dfb4ff5
Date:   Tue Oct 25 14:30:11 2022 -0400
libupload: don't buildextend with --force for azure
If we make it to the cloud uploads in the pipeline then we've
reserved a build ID and any new runs will reserved a different
build ID. We shouldn't need to pass `--force` here.
In it's current form we're building the azure image in the
"Build Artifacts" stage and again in the "Cloud Upload" stage
befause `--force` tells `buildextend-azure` to ignore the
existing built artifact.
commit bbf300c3b011f584b9eaa9b5502ae086533dc805
Date:   Tue Oct 25 14:28:02 2022 -0400
libcloud: avoid null pointer exception
If there are no AWS test accounts specified then the `.join()` will …
```

libupload: a few fixes for corner cases

---

HACKING.md
docs/config.yaml
jobs/release.Jenkinsfile
libupload.groovy

This adds another entry in our clouds config in our config.yaml and also documents support for an aws-govcloud-image-upload-config secret.

support uploading to AWS govcloud

---

config.yaml
docs/config.yaml
libupload.groovy

Some RHCOS pipelines make their AMI public during initial publishing. Let's make it configurable.

libupload: add support for passing `--public` to buildextend-aws

---

libupload.groovy

Right now the CLI accepts `--config` for the file with credentials. It also doesn't need `s3://` (or `oss://`, which would be more appropriate for Aliyun) prepended to the bucket.

libupload: fix buildextend-aliyun step

---

libupload.groovy

Missed the line continuation marker in 1e89b69.

libupload: fix line continuation for AWS upload

---

docs/config.yaml
jobs/release.Jenkinsfile

It turns out that we won't need to support building *both* the legacy oscontainer and the new one for 4.12. In the new transition plan, the new format will directly take the place of the old one as `oscontainer` in `meta.json` and `machine-os-content` in the release payload. This minimizes the impact on OpenShift tooling.
Update the release job to set the `oscontainer` key for the new container and verify that we're not pushing both the legacy and new container since they would conflict.
This change almost matches the latest behaviour of the old RHCOS pipeline. One difference is that we're no longer setting the key `base-oscontainer`. I think we should delete it from the schema eventually.
See also: https://issues.redhat.com/browse/MCO-392

jobs/release: put new oscontainer under `oscontainer` key

---

config.yaml

As previously announced, we no longer need to copy to the old location now.

config.yaml: stop copying to quay.io/coreos-assembler/fcos

---

multi-arch-builders/README.md

- use a more locked down security group
- use a subnet from us-east-1a
- had trouble getting an instance in the other one
- Don't specify an AMI
- forces the person to look up the latest one

multi-arch-builders: README updates for AWS instance bringup

---

jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile
jobs/release.Jenkinsfile
utils.groovy

This adds the following functions:
- withAWSBuildUploadCredentials(Closure body)
- shwrapWithAWSBuildUploadCredentials(cmds)
- AWSBuildUploadCredentialExists()
and changes code throughout the repo to take advantage of them.
This has the side effect of dropping the use of tryWithOrWithoutCredentials at the top of the build and build-arch jobs.

utils: add AWSBuildUpload credential helper functions

---

utils.groovy

RHCOS 4.11 and older do not want to build the `extensions-container` artifact. The artifact is for all arches. Support `all` for `skip_artifacts` to make skipping it less verbose.
RHCOS 4.11 and older want to build the `legacy-oscontainer` artifact. RHCOS 4.12 and newer do not. Support enhancing the default set by bringing back the `additional_artifacts` key. The artifact is for all arches. Support the `all` key to make adding it less verbose.
For consistency with the other keys, also support `additional_artifacts` per architecture.

utils: enhance per-stream artifact set modifications

---

docs/config.yaml
jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile

For the ART hotfix process, we sometimes need to be able to build with an unsigned kernel. This means that UEFI SecureBoot tests will fail. We should support skipping UEFI tests from the src config repo via e.g. `kola-denylist.yaml`. But to do this properly, we need to first lower `cosa kola --basic-qemu-scenarios` into kola proper, and also ideally merge `kola testiso` into `kola run` (maybe as external tests?) or introduce a new `kola-testiso-denylist.yaml` file (or change the schema of the existing `kola-denylist.yaml`).
Short-term, let's just hack around this by adding a `skip_secureboot_tests_hack` knob in the pipecfg which automatically tells `kola()` and `kolaTestIso()` to skip over SecureBoot tests.
Requires: https://github.com/coreos/coreos-ci-lib/pull/133

Add hack knob to skip SecureBoot tests

---

docs/config.yaml
jobs/release.Jenkinsfile

A bunch of tooling around OpenShift don't support the OCI format yet, so
for the RHCOS images we need to push in v2s2 format.
For FCOS, we want to keep pushing in OCI format. Add a new config.yaml
knob to override this for RHCOS.
Related: https://github.com/coreos/coreos-assembler/pull/2726

Support pushing containers in v2s2 format

---

jobs/build-cosa.Jenkinsfile
jobs/build-fcos-buildroot.Jenkinsfile
jobs/release.Jenkinsfile

```
commit 02ba886a0337c9e7805533fd49b41e47d20c02ab
Date:   Mon Oct 31 20:30:07 2022 -0400
tree-wide: use VFS storage driver for container pushes
This is a less hacky workaround for
https://github.com/coreos/fedora-coreos-pipeline/issues/723
Since we're just pushing containers the performance hit won't be
much.
commit f3a0dc7b175455998f9ef2c23b810deba3a02682
Date:   Mon Oct 31 16:50:04 2022 -0400
tree-wide: use different home dir to workaround podman mount issue
This is to address https://github.com/coreos/fedora-coreos-pipeline/issues/723
One workaround I've found is to change my `$HOME` to a different
filesystem (`/var/tmp`, which is overlayfs) and it seems to workaround
the offending check [1].
This …
```

add in workarounds for new restricted permissions in OCP 4.11

---

jobs/build-cosa.Jenkinsfile

For a period of time we're going to be hacking on the RHCOS pipeline older streams and we've created some branches in the COSA git repo that we'd like to build and push only to the staging quay repo.

jobs/build-cosa: add in hack for build COSA against dev 4.X branches

---

.cci.jenkinsfile

I realized recently that we could use `load()` in CI as a way to syntax-check our Groovy files. Add a CI check that uses this.
This works for regular Jenkinsfiles too (since it's still just the same custom Groovy interpreter). But `load()` will try to execute them, which is not what we want. Hack around this by adding a `return this` at the top. The parser will still actually scan the full file.
This only catches basic syntax errors like unbalanced parentheses or brackets, and not semantic errors like typoed function names or variables. We should be able to add a more complete CI run here in the future that e.g. could execute a part of the pipeline, but it requires some thought.

ci: add basic syntax checking of Groovy files

---

docs/config.yaml
jobs/release.Jenkinsfile

The latest plan for 4.12 is to go back to shipping both the legacy and new oscontainers to not break existing workflows of teams consuming it. So we need to undo some of the recent changes made.
Related: https://issues.redhat.com/browse/MCO-295
Related: https://issues.redhat.com/browse/MCO-392

jobs/release: allow pushing both legacy and new oscontainer

---

config.yaml
docs/config.yaml
jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile
jobs/kola-aws.Jenkinsfile
jobs/kola-azure.Jenkinsfile
jobs/kola-gcp.Jenkinsfile
jobs/kola-kubernetes.Jenkinsfile
jobs/kola-openstack.Jenkinsfile
jobs/release.Jenkinsfile
jobs/sync-stream-metadata.Jenkinsfile
utils.groovy

The `prod/streams/${params.STREAM}` is an FCOS thing. Let's have the `s3_bucket` key in the `config.yaml` also incorporate the subpath.
This will allow the RHCOS config to specify its own subpath and is prep for hotfix builds specifying a different subpath.

Lower FCOS S3 bucket prefix into config.yaml

---

config.yaml
docs/config.yaml
jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile
jobs/release.Jenkinsfile
utils.groovy

Requires: https://github.com/coreos/fedora-coreos-pipeline/pull/738

Drop `official` concept, replace with hardcoded list of well-known protected Jenkins instances

---

jobs/release.Jenkinsfile

For RHCOS 4.11 and older, there is no native oscontainer to push so we don't want to even try. But unlike other cloud-y things, the artifact does exist (`ostree`), so we can't just rely on the fact that we're not building it.
Rather than adding more temporary knobs at the pipecfg, hack around this by checking if the cosa schema supports `base-oscontainer` and if not, don't try to push it.

jobs/release: don't push base-oscontainer on releases missing it

---

utils.groovy

In the case that there is a one-off mArch build that runs first for a particular stream then we need to copy the builds.json back to the local node before we upload.

utils: modify bump_builds_json to work if non x86_64 first

---

docs/config.yaml
jobs/build-arch.Jenkinsfile
jobs/build-cosa.Jenkinsfile
jobs/build.Jenkinsfile
jobs/release.Jenkinsfile
utils.groovy

ART needs the ability to perform hotfix builds, i.e. builds outside the
regular stream for a specific purpose. These builds must not pollute
production stream references.
Support this via the new `hotfix` section of the pipecfg. Require a
`name` subkey which is then used to modify the S3 subpath we upload to
and the oscontainer tags we push to. Add new hotfix parameters to the
`build`, `build-arch`, and `release` jobs which will be used to pass the
repo containing the hotfix pipecfg.
Don't support hotfix cloud uploads since it's not yet needed and
requires plumbing of the hotfix prefix.
Requires: https://github.com/coreos/fedora-coreos-pipeline/pull/739

Add basic support for hotfix builds

---

jobs/build.Jenkinsfile
jobs/bump-lockfile.Jenkinsfile

We're seeing an obscure `Got EOF from completion channel` error when running testISO. The running theory is that we're running out of memory and that seems to be accurate in a test I did earlier today. Let's bump for now and investigate when we have more time.
See https://github.com/coreos/fedora-coreos-tracker/issues/1339

jobs/{build,bump-lockfile}: bump up memory for testISO failure

---

jobs/release.Jenkinsfile

We've seen the buildfetch getting killed and we think it's because we are spiking briefly above the 512Mi limit we had set for ourselves.

jobs/release: bump memory for release job

---

docs/config.yaml
jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile
jobs/release.Jenkinsfile

We want to drop these hacks in the near future, but for now we need to carry them so that we don't have to fork the pipeline.
```
commit 918b4d628c16baf7dfd941c65fd24f457f026b17
Date:   Mon Nov 14 16:54:03 2022 -0500
add hacks.use_yumrepos_branch_workaround
For the moment the git repo that we are pulling our yum repo files
from has a branch per stream of RHCOS (i.e. 4.9, 4.10...). The plan
is to get to a single branch that has all the yum repo files. Until
that happens let's bake in a hack to support what currently exists.
commit 283d5d4a3cad3a75f85ba248cb1ecd0cba465035
Date:   Mon Nov 14 16:52:41 2022 -0500
add hacks.skip_uefi_tests_on_older_rhcos
On older RHCOS (i.e. 4.9) the UEFI+`iso-live-login` test …
```

add in hacks for rhcos 

---

docs/config.yaml
jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile

This allows us to override the compression format to gzip for the RHCOS pipeline for now.

Add hacks.override_compression_format

---

utils.groovy

The project name was `rhcos`, now it's `rhcos-devel`.

utils: update namespace for RHCOS devel pipeline

---

jenkins/config/slack.yaml

After 27693a6, the Slack plugin fails to send messages on new Jenkins instances with:
java.lang.IllegalArgumentException: Project Channel or Slack User ID
must be specified.
This seems to be due to some bug in the plugin where without a `room` setting, it doesn't know to rely on the default room associated with the token. This is filed upstream in:
https://github.com/jenkinsci/slack-plugin/issues/857
Short-term, let's just work around this by specifying an empty `room`.

jenkins/config: add empty `room` field

---

jobs/build-development.Jenkinsfile
jobs/build-mechanical.Jenkinsfile
jobs/build.Jenkinsfile

This will give us control of when the multi-arch jobs are kicked off. In some cases we want them to be kicked off early (to save time). Unfortunately in that case if the x86_64 build later fails (which means the build ID can no longer be used) the work done by the multi-arch builds gets trashed as well.
Let's add a knob so we can kick them off early when desired, but allow for them to be kicked off later in situations where time isn't a large factor.

jobs/build: add EARLY_ARCH_JOBS parameter

---

config.yaml
docs/config.yaml
jobs/build.Jenkinsfile
jobs/bump-lockfile.Jenkinsfile
jobs/release.Jenkinsfile
utils.groovy

Add support for `skip_additional_arches` and `additional_arches` keys in
the stream-level section. E.g. currently for FCOS, we're not shipping
ppc64le for the production streams.
This will also be useful for RHCOS in the future when e.g. keeping older
streams alive on only a subset of arches.

Support skipping or overriding additional arches per stream

---

jobs/build-cosa.Jenkinsfile
jobs/build-fcos-buildroot.Jenkinsfile
jobs/bump-lockfile.Jenkinsfile
jobs/kola-aws.Jenkinsfile
jobs/kola-azure.Jenkinsfile
jobs/kola-gcp.Jenkinsfile
jobs/kola-kubernetes.Jenkinsfile
jobs/kola-openstack.Jenkinsfile

Also includes some re-organization/comment fixes.
```
commit 1fae67e20a7590c94582ece82b18d76617c5eb35
Date:   Fri Nov 18 16:12:22 2022 -0500
jobs/kola-*: include catch/finally in cosaPod() block
This will allow us to do more advanced things in the finally. For
example the `oc` command that got added to `trySlackSend()` in
4404730 needs to run from inside the cosaPod to work.
commit 8f10e97480d7313253724d648d902516a88c64ed
Date:   Fri Nov 18 16:07:54 2022 -0500
jobs/kola-openstack: fix comments move around variables
The comment was outdated since we aren't running tests on multiple
regions any longer.
Moved around the variables to prep for the next patch.
commit a8ffb28e69aaa39bd061e6dd770ae58fb0740330 …
```

tree-wide: include catch/finally in cosaPod() block

---

jobs/build-arch.Jenkinsfile
jobs/build-cosa.Jenkinsfile
jobs/build-fcos-buildroot.Jenkinsfile
jobs/build.Jenkinsfile
jobs/bump-lockfile.Jenkinsfile
jobs/cloud_replicate.Jenkinsfile
jobs/kola-aws.Jenkinsfile
jobs/kola-azure.Jenkinsfile
jobs/kola-gcp.Jenkinsfile
jobs/kola-kubernetes.Jenkinsfile
jobs/kola-openstack.Jenkinsfile
jobs/release.Jenkinsfile
utils.groovy

Some follow-ups to Slack prefixing work

---

HACKING.md

This will be used by the ART workflow at least.

HACKING.md: add docs for triggering builds remotely

---

docs/config.yaml
jobs/cloud-replicate.Jenkinsfile
jobs/release.Jenkinsfile
libcloud.groovy

RHCOS 4.9 and earlier did not upload to GovCloud so we need to temporarily support a hack to skip it on those streams.

Add temporary hack for skipping AWS GovCloud uploads

---

libcloud.groovy

```
commit 5a0a12039a6b126cf368643d185a051af166d747
Date:   Wed Nov 23 15:19:40 2022 -0500
libcloud: specify the source region for AWS replication
Since we can upload to both AWS and AWS Govcloud we don't need to
just let the code pick the first AMI in the list to use as the
source AMI. We need to tell it which one is the source.
commit 8e58bea89ccfe89c01e2fa5cc904636b2010a9a9
Date:   Wed Nov 23 15:15:36 2022 -0500
libcloud: create a separate replicator for AWS govcloud
We can run the replication for govcloud in parallel. Let's
use the same model we're using for the uploaders where we
define a closure and then call that closure for primary
AWS and for AWS Govcloud.
commit …
```

libcloud: fixes for aws uploads

---

config.yaml
docs/config.yaml
libcloud.groovy

We do want this for AWS Marketplace accounts at least. For test
accounts, it's not necessary but doesn't hurt either.

libcloud: also grant `createVolumePermission` to grant_users

---

HACKING.md
deploy
manifests/jenkins-s2i.yaml
manifests/jenkins-with-cert.yaml
manifests/jenkins.yaml

Just like we did for the agent image, play a similar trick to have the
additional cert baked into the controller image. This is required if we
need to fetch resources from HTTPS URLs covered by the root CA in code
that runs directly on the controller. This situation comes up in RHCOS
where we want to be able to load the pipecfg from an internal repo early
on in jobs.

Bake additional cert into Jenkins controller image

---

config.yaml
jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile

We've made hashlist generation look more like just another buildextend command. This allows us to clean up our code related to this.
See: https://github.com/coreos/coreos-assembler/pull/3248

jobs/build: adapt to new hashlist command

---

docs/config.yaml
jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile

We don't need this anymore. On FCOS, the `xz` setting is part of `image.yaml` which `cosa compress` now knows to read from. On RHCOS, we rely on `cosa compress` defaulting to `gzip`. This works for both new and old RHCOS streams using a cosa without the `image.yaml` support.

config: drop support for `override_compression_format` hack

---

manifests/jenkins.yaml

We're hitting https://issues.jenkins.io/browse/JENKINS-55287 which according to some reports can be memory-related. Let's try bumping to 3Gi and see if it helps.

manifests/jenkins: bump memory request to 3Gi

---

config.yaml
docs/config.yaml
jobs/release.Jenkinsfile

Rather than `plume release`, use the new `plume make-amis-public` and
`plume update-release-index` commands directly. Gate the former on
whether the AMIs were already made public on first upload. Gate the
latter on a new `misc.generate_release_index` since we only need it for
FCOS. Finally, get rid of the `skip_plume_release_task` knob.

config: drop `skip_plume_release_task` hack, add `misc.generate_release_index`

---

docs/config.yaml

Missed this in b895f03.
I want to reference this block in an issue.

docs/config: copy docs for `aws.public` to `aws.govcloud.public`

---

manifests/jenkins.yaml

Right now, we're letting it default to the default values of the limitrange, which is 4 for CPUs and 10G for RAMs. That's vastly overkill given that we don't actually do any work in them but rather in the cosa containers colocated in them.
The limits chosen here match the builtin defaults in the kubernetes-plugin.

manifests/jenkins: set resource limits and requests for jnlp container

---

jenkins/config/k8s.yaml

```
jenkins/config: define kubernetes cloud ourselves
Rather than relying on the S2I run script to define the kubernetes
cloud, do it ourselves. This will allow us to further customize it for
our needs, which isn't currently possible with the S2I setup:
https://github.com/openshift/jenkins/issues/1505
The two major differences with what the S2I run script would've defined
are:
1. no defining of pod templates; we don't use those anyway, so this is a
nice cleanup
2. no setting of the kube certificate; the kubernetes plugin is smart
enough to get it from the mounted serviceaccount secret, which is
what the S2I run script does anyway
```
---
```
jenkins/config: bump maxRequestsPerHost to 64
This is a conceptual revert of the revert in #583. Now that we own the
cloud config, we can safely do …
```

jenkins/config: define kubernetes cloud ourselves and bump maxRequestsPerHost to 64

---

jobs/build-arch.Jenkinsfile
jobs/build-cosa.Jenkinsfile
jobs/build.Jenkinsfile
jobs/bump-lockfile.Jenkinsfile
jobs/cloud-replicate.Jenkinsfile
jobs/kola-aws.Jenkinsfile
jobs/kola-azure.Jenkinsfile
jobs/kola-gcp.Jenkinsfile
jobs/kola-kubernetes.Jenkinsfile
jobs/kola-openstack.Jenkinsfile
jobs/release.Jenkinsfile
utils.groovy

This will make the job (and slack message) show up as yellow (warning) if there were missing architectures.
Fixes https://github.com/coreos/fedora-coreos-pipeline/issues/784

jobs/release: show warning status if missing architectures

---

jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile

It's redundant with the emojis and colour and isn't consistent with the other job notifications.

jobs/build: don't include build result as string in Slack msg

---

docs/config.yaml
jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile
jobs/bump-lockfile.Jenkinsfile
jobs/cloud-replicate.Jenkinsfile
jobs/kola-aws.Jenkinsfile
jobs/kola-azure.Jenkinsfile
jobs/kola-gcp.Jenkinsfile
jobs/kola-kubernetes.Jenkinsfile
jobs/kola-openstack.Jenkinsfile
jobs/release.Jenkinsfile

Add support in `build.jenkinsfile` and `build-arch.jenkinsfile` for reading variant information from the pipeline config/stream and passing it into `cosa init`.
xref: https://gitlab.cee.redhat.com/coreos/rhcos-devel-pipecfg/-/merge_requests/3  &  https://gitlab.cee.redhat.com/coreos/rhcos-art-pipecfg/-/merge_requests/9
See [COS-1925](https://issues.redhat.com/browse/COS-1925)

jobs/build: add support for reading variant from stream/pipeline config

---

jobs/release.Jenkinsfile

- We are having trouble detecting why fetch is failing from time to time. To track it a little better, let's add it for a while.
Signed-off-by: Renata Ravanelli <rravanel@redhat.com>

release: Add `time -v` as part of fetch cmd for debugging

---

config.yaml
docs/config.yaml
jobs/build-arch.Jenkinsfile

Once https://github.com/coreos/fedora-coreos-config/pull/1181 has shipped to all streams, drop the aarch64 aws console hack here because it'll no longer be doing anything.

jobs/build-arch: drop aarch64 aws serial console hack

---

jobs/release.Jenkinsfile

This reverts commit 0358b7624c09c30ae111819fa70af86f6764c3bd.
We need to backport https://github.com/coreos/coreos-assembler/pull/3268 to older cosa first.

Revert "release: Add `time -v` as part of fetch cmd for debugging"

---

docs/config.yaml
jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile

All the streams we care about now use the main branch of the yumrepos git repo.

config: drop support for `yumrepos_branch_rhcos_hack`

---

jenkins/config/k8s.yaml

We're still seeing `not ready after 5000 MILLISECONDS` issues. Let's try more band-aids.

jenkins/config: bump maxRequestsPerHost again; set connectTimeout

---

jenkins/config/slack.yaml

The internal Slack workspace recently was upgraded and migrated to a new name. Adapt our configs.

jenkins/config: update Slack team domain

---

jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile

This makes use of the new autolock feature in cosa to force multi-arch
builds to be consistent with the x86_64 build. This takes effect when
building a stream which doesn't currently use lockfiles.
The primary use case is RHCOS, but even once we start using lockfiles
there, this will still be useful for the FCOS rawhide stream.

jobs/build-arch: use new autolock feature

---

jobs/build-arch.Jenkinsfile

Otherwise there's no point in fetching it. This also fixes the fact that
the `cosa buildfetch --file` switch hasn't been backported to older cosa
branches, where we don't support autolocking anyway.

jobs/build-arch: only fetch generated lockfile if autolocking

---

jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile

Commit 6c2d5a0 ("jobs/build-arch: use new autolock feature") made this job start fetching some x86_64 build metadata. This metadata should only be used as part of the autolocking feature. When uploading our build metadata for this arch, we shouldn't re-upload the x86_64 stuff since it might be outdated.

jobs/build-arch: only buildupload for given arch

---

jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile

The `--arch` switch is a top-level switch, not an `s3` subcommand
switch.
Fixes e70fb4b ("jobs/build[-arch]: only buildupload for given arch").

jobs/build[-arch]: fix `cosa buildupload` argument ordering

---

jobs/bump-lockfile.Jenkinsfile

On the remote builders the credentials file is laid down on the filesystem so let's specify the path to it.

jobs/bump-lockfile: add --aws-config-file to buildfetch

---

jobs/bump-lockfile.Jenkinsfile

This job was taking up 7G of storage on the PVC in the FCOS pipeline. Since it runs tests on all architectures it will naturally take up way more storage as it archives all of those kola logs. Let's lower the number of artifacts it stores to 30 to alleviate this storage usage.

jobs/bump-lockfile: lower number of artifacts to keep

---

docs/config.yaml
jobs/build.Jenkinsfile

This allows specifying a different ref than the default when cloning the yumrepos git repo. We're only planning to use this in the hotfix path for RHCOS.

config: add `source_config.yumrepos_ref`

---

jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile
jobs/release.Jenkinsfile

Otherwise, the Slack notifications look just like the regular ones for the official streams the hotfix build is based on. We noticed this when testing the hotfix workflow recently.

jobs: include hotfix name in Slack notifications

---

multi-arch-builders/coreos-ppc64le-builder-512e.bu

- The ppc64le builder is slower than the other architectures during the build, after a long investigation with the disk, we noticed that FCOS installation process is looking at the logical partition of disk (512k) and not the physical (4k) one. As a workaround for now, reprovisioning it with xfs helps with part of the slowness, making it a little bit better.
Signed-off-by: Renata Ravanelli <rravanel@redhat.com>

Update butane config for ppc64le builder

---

multi-arch-builders/README.md

We've moved to a different IBMCloud account so some of the information has changed. Also wanted to codify running the instance and attaching it to a security group.

multi-arch-builders: update instructions for s390x builder

---

HACKING.md
jobs/kola-azure.Jenkinsfile
libcloud.groovy

This PR updates our Azure credential docs and handling to match what was implemented in https://github.com/coreos/coreos-assembler/pull/3349
Mainly we now only need one `azureCreds.json` file for authentication (this means Azure is now more like the others that only need a single file for authentication) and we must update CLI calls to use --azure-credentials.

updates for Azure credential handling

---

jobs/build-arch.Jenkinsfile
jobs/build-cosa.Jenkinsfile
jobs/build-development.Jenkinsfile
jobs/build-fcos-buildroot.Jenkinsfile
jobs/build-mechanical.Jenkinsfile
jobs/build.Jenkinsfile
jobs/bump-lockfile.Jenkinsfile
jobs/cloud-replicate.Jenkinsfile
jobs/kola-aws.Jenkinsfile
jobs/kola-azure.Jenkinsfile
jobs/kola-gcp.Jenkinsfile
jobs/kola-kubernetes.Jenkinsfile
jobs/kola-openstack.Jenkinsfile
jobs/release.Jenkinsfile
jobs/sync-stream-metadata.Jenkinsfile
libcloud.groovy

Currently, if the x86_64 build succeeds, but not e.g. the aarch64 build,
a rerun of the `build` job will no-op. Salvaging the build requires
rerunning just the `build-arch` job for aarch64, and then rerunning the
`release` job. This is relatively easy for a human, but isn't very
automation-friendly.
With this patch, if we no-op but the latest build is missing builds for
some of the architectures, we automatically rerun the `build-arch` job
for those missing arches and then rerun the `release` job. This allows
the interface for automation to solely be the `build` job, and allows
transparently salvaging up-to-date but incomplete builds rather than
paying for a much costlier full rebuild on all arches.

jobs/build: rerun `build-arch` if previous build is incomplete

---

config.yaml

A newer systemd has introduced a file that is causing the command to fail. Let's skip it on rawhide/branched while we investigate. See: https://github.com/coreos/fedora-coreos-tracker/issues/1429

config: skip hashlist generation on rawhide/branched

---

jobs/build.Jenkinsfile

The main reason we added that was because in the new "rerun build-arch and release jobs" path, there was a higher likelihood that the release job could in theory take the locks before the build-arch jobs. But with 0664cd6 ("jobs/build: wait when re-running mArch jobs"), this is no longer a concern.
There's still the theoretical possibility the race happens even in the regular path (especially when `EARLY_ARCH_JOBS` is unset), but (1) something must be really slow in the multi-arch jobs for that to happen (in which case, it might end up taking more than our 5 minute timeout anyway) and (2) the worst case is that we release without that arch before it's built, which is salvageable (by rerunning the release job).
So overall, IMO maintaining this code is not worth the complexity. We can …

jobs/build: stop waiting for multi-arch jobs to take lock

---

jobs/kola-azure.Jenkinsfile
jobs/kola-openstack.Jenkinsfile

We still occasionally hit issues where these jobs get SIGKILLed from the pipeline. I ran a profile recently with `time -v` and this is what I saw:
```
+ /usr/bin/time -v cosa decompress --build=39.20230222.91.0 --artifact=azure
Targeting build: 39.20230222.91.0
Uncompressing: builds/39.20230222.91.0/x86_64
2023-02-22 15:09:11,423 INFO - Running command: ['xz', '-dc', '-T2', 'builds/39.20230222.91.0/x86_64/fedora-coreos-39.20230222.91.0-azure.x86_64.vhd.xz']
Uncompressed: fedora-coreos-39.20230222.91.0-azure.x86_64.vhd
Skipped uncompressing artifacts: ostree nutanix vmware virtualbox gcp digitalocean live-iso live-kernel live-initramfs live-rootfs
Updated: builds/39.20230222.91.0/x86_64/meta.json
Skipping missing arch: s390x
Command being timed: "cosa decompress --build=39.20230222.91.0 …
```

jobs/kola-{azure,openstack}: bump memory again for decompress jobs

---

manifests/jenkins.yaml

By default, the jnlp container has a memory request of 256Mi and no
memory limit. In 9eed927 ("manifests/jenkins: set resource limits and
requests for jnlp container"), we added an explicit memory limit so that
we don't inherit the default 10G memory limit from the limitrange in
the RHCOS OpenShift project. We set it to 256Mi since that's what the
default memory *request* was, but it's too little as a hard limit. Most
of the time, the jnlp unexplicably dies, but at least once, I saw it
fail with:
```
java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
```
Bump it to 512Mi. And also bump the request since in this project we try
to have requests match what the pod actually needs.
While we're here, add a comment about why we …

manifests/jenkins: bump jnlp memory to 512Mi

---

config.yaml

This reverts commit 3a94202df28ca4604232254c4579e99c859c19c1.
The underlying problem should have been fixed by
https://github.com/coreos/coreos-assembler/pull/3386

Revert "config: skip hashlist generation on rawhide/branched"

---

config.yaml
next-devel/badge.json
next-devel/status.json

The Fedora Linux 38 beta release is next week so `next-devel` and `next` are moving over to Fedora 38 content. Re-enable `next-devel` to allow it to differ from `testing-devel`.

config: re-enable next-devel

---

config.yaml

`next-devel` is now on Fedora 38 so there's no point in also tracking it in the `branched` stream.

config: disable `branched` stream

---

jobs/kola-aws.Jenkinsfile
jobs/kola-azure.Jenkinsfile
jobs/kola-gcp.Jenkinsfile
jobs/kola-openstack.Jenkinsfile
jobs/release.Jenkinsfile

On `cosa buildfetch` invocations that fetch large objects, add `time -v` so we get a picture of how much memory the operation took. We're occasionally hitting what looks like OOM issues, but before either increasing our memory requests or tweaking S3 download settings, let's sanity-check first that's what's happening.

jobs: do `cosa buildfetch` with `time -v` when fetching large objects

---

jobs/build-arch.Jenkinsfile
jobs/build-cosa.Jenkinsfile
jobs/build-fcos-buildroot.Jenkinsfile
jobs/build.Jenkinsfile
jobs/bump-lockfile.Jenkinsfile
jobs/kola-aws.Jenkinsfile
jobs/kola-azure.Jenkinsfile
jobs/kola-gcp.Jenkinsfile
jobs/kola-kubernetes.Jenkinsfile
jobs/kola-openstack.Jenkinsfile

Getting the resources for the cosa pod might take time if there's lots of concurrent builds in progress filling our quota. That wait time shouldn't count towards the timeout. Flip the scoping order so that the timeout starts only when we actually have the pod.
This is most problematic in the `build` job where we allocate pods with lots of resources. But for consistency, do this in all our jobs.

jobs: nest timeout within `cosaPod`

---

docs/config.yaml
jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile

While working with unreleased content, we don't want any publicly accessible artifacts. This includes cloud images. Add a `skip_cloud_uploads` key for this.
This is temporary to unblock the RHEL 9.2 work. I think what would be nicer here instead is to still upload to clouds but keep the images private. However, we need to add a `--public` knob to some of the cloud commands we use first.
Another option worth investigating is support for overriding the base `cloud` key entirely like we have for some other keys.

config: support per-stream `skip_cloud_uploads` knob

---

jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile
jobs/bump-lockfile.Jenkinsfile

Otherwise we risk getting multiple refs matching the given pattern (i.e. the branch name showing up in more branches than just the canonical branch). We hit this today with a revert branch that was auto-created accidentally by GitHub through the web UI:
```
$ git ls-remote https://github.com/coreos/fedora-coreos-config next
b9f8903339c142b00105bd0fb97c3fcc21e1502a        refs/heads/next
9007e5804e41097afaa7e42d13455d8a8cd87375        refs/heads/revert-2307-bootloader/next
```
And then the `src_config_commit` variable had multiple lines which messed up parameter substitution lower down.

jobs: pass fully qualified ref name to `git ls-remote`

---

multi-arch-builders/coreos-s390x-rhcos-builder.bu

Add a delay in `create-secex-data.sh` to allow the disk to be fully ready before trying to mount it.
Change the script location to `/usr/local/bin`
Signed-off-by: Jan Schintag <jan.schintag@de.ibm.com>

coreos-s390x-rhcos-builder: Fix problems with create-secex-data.sh

---

docs/config.yaml
jobs/build.Jenkinsfile

The old RHCOS pipeline had a mechanism for checking if the kernel and kernel-rt packages were built from the same version and failing if they were not. The check was never migrated over to the new RHCOS pipeline. Add the check to verify that the kernel and kernel-rt are of the same version and stop the pipeline if there is a version mismatch. Also add an optional field in the stream section of `config.yaml`  to enable, disable this check. 
By default, the check will not run unless the optional field `check_kernel_rt_mismatch` is set to true. This will ensure the check will not run against FCOS builds.
See: https://issues.redhat.com/browse/COS-2021

jobs/build: verify kernel + kernel-rt versions match in rhcos

---

manifests/jenkins.yaml

We're hitting https://issues.jenkins.io/browse/JENKINS-55287 yet again. We had bumped it in ef4c318 ("manifests/jenkins: bump memory request to 3Gi") from 2Gi to 3Gi, but that doesn't seem enough:
```
$ oc describe pod jenkins-22-rvq4w
...
Last State:     Terminated
Reason:       OOMKilled
Exit Code:    1
Started:      Sat, 18 Mar 2023 10:28:31 -0400
Finished:     Tue, 28 Mar 2023 10:37:05 -0400
```
Let's bump it to 6Gi.

manifests/jenkins: bump memory request to 6Gi

---

config.yaml

Reverts coreos/fedora-coreos-pipeline#841
Apparently `cosa buildextend-kubevirt` works fine when running locally
but runs into failures in the pipeline. Let's revert for now until
we get fixes into coreos-assembler so that it can run fine inside
of OpenShift.

Revert "config: Start producing kubevirt artifact for x86_64"

---

config.yaml
docs/config.yaml
jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile
jobs/kola-upgrade.Jenkinsfile
utils.groovy

This will test upgrades from older releases to verify old systems can be updated to the latest versions. For our production FCOS streams we'll kick off a full matrix to try to test from different points in the history of the stream. For development/mechanical streams we'll just kick of a single modulo $date test per build.

jobs: add kola-upgrade test

---

jobs/kola-upgrade.Jenkinsfile

```
commit a6b6946e5623a128512d307ef9abc4fa220e9182
Date:   Fri Mar 31 20:35:52 2023 -0400
jobs/kola-upgrade: fix deadend checks
In would case we should have used `start_version` and in the other case
we should have used `release["version"]` and not `release`.
commit 3fede5fc8a9a2f5e5bf208ca103a49e5c603ce8c
Date:   Fri Mar 31 20:29:50 2023 -0400
jobs/kola-upgrade: SecureBoot on aarch64 isn't supported
Looks like this isn't supported in Fedora. When running the tests
we ran into:
```
2023-03-31T23:49:51Z kola: retryloop: failed to bring up machines:
architecture aarch64 doesn't have support for secure boot in kola
```
I think this migth be the blocker for Fedora right now: …
```

jobs/kola-upgrade: fix deadend checks; disallow uefi-secure on aarch64

---

jobs/kola-upgrade.Jenkinsfile

For <= 37 start_versions we'll hit an OOM in grub when running SecureBoot tests. This is documented in
https://github.com/coreos/fedora-coreos-tracker/issues/1456
Let's workaround the issue for now in our test.

jobs/kola-upgrade: bump memory for <=37 secureboot tests

---

jobs/kola-upgrade.Jenkinsfile

Early versions of `next` on F32 did not yet have Ignition 2.3.0 with spec 3.1.0 support. Let's add an exception that will hardcode the starting version for next if the specified start_version is 32.

jobs/kola-upgrade: add exception for next stream start_version

---

jobs/kola-aws.Jenkinsfile

Snooze this test for the month of April while we wait for a fix for https://github.com/coreos/fedora-coreos-tracker/issues/1438

kola-aws: Snooze xen-tests for rawhide stream

---

jobs/kola-upgrade.Jenkinsfile

This reverts commit 1dcb453f2a4660f25654be83f57b9cda7d46c1c6.
cosa now uses spec v3.0.0[[1]] so this `start_version` should be fine.
[1]: https://github.com/coreos/coreos-assembler/pull/3426

Revert "jobs/kola-upgrade: add exception for next stream start_version"

---

jobs/kola-gcp.Jenkinsfile

cosa was recently updated to use `gcp` rather than `gce`: https://github.com/coreos/coreos-assembler/pull/3424

jobs/kola-gcp: rename `gce`-related switches to `gcp`

---

jobs/bump-lockfile.Jenkinsfile

Running it in a stage will cause it to show up properly in the Blue Ocean view.

jobs/bump-lockfile: run testiso in a stage

---

jobs/build-arch.Jenkinsfile

The tests don't work on the 4.12 pipeline because cosa is missing some
patches. We need to backport at least https://github.com/coreos/coreos-
assembler/pull/3384 but it gets messy because we don't want to also
backport the Ignition config GPG key stuff. Possibly we'll just need a
temporary hack key there in the future.
Anyway, for now let's at least unblock 4.12.

jobs/build-arch: temporarily disable secex tests

---

multi-arch-builders/README.md

We've occasionally seen some failures and/or capacity issues so we'll document `us-east-1` and `ca-tor-1`.

multi-arch-builders: add s390x steps for another region

---

jobs/kola-openstack.Jenkinsfile
jobs/kola-upgrade.Jenkinsfile

This option to `kola run` now takes a string as input. See https://github.com/coreos/coreos-assembler/pull/3430.

jobs/kola-{upgrade,openstack}: update --allow-rerun-success options

---

jobs/kola-openstack.Jenkinsfile
jobs/kola-upgrade.Jenkinsfile

In https://github.com/coreos/coreos-ci-lib/pull/148 we are modifying the defaults to now call kola run with `--allow-rerun-success tags=needs-internet`, which is part of https://github.com/coreos/fedora-coreos-pipeline/issues/842.
Here we drop the `--allow-rerun-success tags=all` call from the upgrade test. Since the test itself has the `needs-internet` tag then it will be covered by the new default.
For the openstack test we'll adjust to the new way to override the argument string passed to `--allow-rerun-success` inside of `kola()`.

jobs/kola-{openstack,upgrade): adjust to coreos-ci-lib allowRerunSuccess changes

---

jobs/kola-aws.Jenkinsfile

The latest kernel version doesn't result in kernel-oops for the zen tests so dropping the snooze on the the test. Since this snooze expired last month, the test's been running successfully on latest rawhide builds.
Closes: https://github.com/coreos/fedora-coreos-tracker/issues/1438

kola-aws: Drop snooze for xen-tests

---

config.yaml

Once https://github.com/coreos/fedora-coreos-config/pull/2435 merges we should be unblocked for releasing ppc64le. We'll do a soft rollout with just `testing`/`next` for now.

Enable ppc64le on testing/next

---

utils.groovy

Let's set the min_supported_start_versions for ppc64le to F38 now that we are doing builds/releases for F38.

jobs/kola-upgrade: enable kola-upgrade test for ppc64le

---

jobs/debug-pod.Jenkinsfile

In order to resolve the limited access to multi-arch for most of our team members,we have the multi-arch builders where we could just use the pipeline itself to spawn a remote session on a builder and the user can then grab a shell via OpenShift to do testing. cosa-init & sleep stages are added as part of creating a job for multi-arch builder access.
Ref: https://github.com/coreos/fedora-coreos-pipeline/issues/803

jobs:debug-pod for multi-arch builder access

---

HACKING.md
docs/config.yaml
jobs/upload-brew.Jenkinsfile

- Create a separate job to upload the metadata;
- We are not required to upload it for every single build as we did before. Only ART will be responsible for it, we are required to make Brew uploads for GAs and other images available to customers.

jobs: Add Brew upload job

---

jobs/debug-pod.Jenkinsfile

On older RHCOS releases we need to use a newer COSA (one that supports `cosa remote-session`). Let's use the `:main` COSA image always so we know we have the latest bits.

jobs/debug-pod: use a controller image for cosa

---

utils.groovy

Snooze the kola-azure cloud test on rawhide for the remainder of June and July while we wait for a fix for:
https://github.com/coreos/fedora-coreos-tracker/issues/1515

utils: snooze kola-azure tests on rawhide

---

utils.groovy

I made a mistake when accessing the `params` variable in my previous PR: https://github.com/coreos/fedora-coreos-pipeline/pull/881.
Update the condition to snooze kola-azure by accessing the `stream` variable directly.

utils: fix typo in kola-azure snooze condition

---

multi-arch-builders/builder-common.bu
multi-arch-builders/coreos-s390x-rhcos-builder.bu

With podman version 4.5.0 it is now possible to skip volumes during prune with a specific label by adding --filter="label!=persistent". Remove the workaround used before to not prune secex-data volume, as it is no longer needed.

s390x-rhcos-builder: Remove podman volume workaround

---

jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile

The version comes before the cosa_img in the argument list.
Fixes b81f738.

jobs/build{,-arch}.Jenkinsfile: fix run_fcos_upgrade_tests() params

---

utils.groovy

The kola-azure tests are passing now that there's a fix for https://github.com/coreos/fedora-coreos-tracker/issues/1515.
This essentially reverts commit 9efb030169ce244fb8493d9d5d70b88475a775a8

utils: remove snooze on kola-azure tests for rawhide

---

docs/debug-pod-access.md

This document provides the background information and the steps to access a debug pod for multi-arch builder access.
Ref: https://github.com/coreos/fedora-coreos-pipeline/issues/803
Jira: https://issues.redhat.com/browse/COS-2339

docs: Documentation on steps to access debug-pod

---

utils.groovy

Snooze the kola-openstack job on all streams for the remainder of July while we investigate https://github.com/coreos/fedora-coreos-pipeline/issues/889.

utils: snooze kola-openstack for all streams

---

jobs/release.Jenkinsfile

The release jobs in both FCOS and RHCOS are failing with `java.lang.NullPointerException: Cannot get property 'principal' on null object`. 
There is a possibility that the `brew` section of the pipecfg doesn't exist, e.g. in FCOS. Add a `?` to the variable assignment to check if `brew` is null before assigning values to these variables.
See: https://github.com/coreos/fedora-coreos-pipeline/pull/886

jobs/release: safely check if `brew` exists in pipecfg

---

jobs/release.Jenkinsfile

- If a secret doesn't exist it will fail to be mounted, as volume Mounts.
- For now let's not pass it as argument to cosaPod, if we don't need the secret

Fix secrets definition in release job

---

jobs/check-aws-regions.Jenkinsfile

It is a periodic jenkins job that runs `ore aws list-regions --disabled` and sends a slack notification if any disabled aws-regions are returned.
Ref: https://github.com/coreos/fedora-coreos-pipeline/issues/152
JIRA: https://issues.redhat.com/browse/COS-2270

jobs: check-aws-regions job for checking disabled aws regions

---

jobs/build-arch.Jenkinsfile
jobs/build-cosa.Jenkinsfile
jobs/build-fcos-buildroot.Jenkinsfile
jobs/build.Jenkinsfile
jobs/bump-lockfile.Jenkinsfile
jobs/check-aws-regions.Jenkinsfile
jobs/cloud-replicate.Jenkinsfile
jobs/kola-aws.Jenkinsfile
jobs/kola-azure.Jenkinsfile
jobs/kola-gcp.Jenkinsfile
jobs/kola-kubernetes.Jenkinsfile
jobs/kola-openstack.Jenkinsfile
jobs/kola-upgrade.Jenkinsfile
jobs/release.Jenkinsfile

Changes in the pipeline job slack notifications where the emoji itself is clickable and the build number is printed only once.

Make the emoji clickable in all pipleine jobs slack notification

---

multi-arch-builders/builder-splunk.bu
multi-arch-builders/coreos-aarch64-rhcos-builder.bu
multi-arch-builders/coreos-ppc64le-rhcos-builder.bu
multi-arch-builders/coreos-s390x-rhcos-builder.bu

Add a splunk forwarder sidecar container to the RHCOS multiarch builders that will send journald logs to a central splunk server.
```
commit ec961fe76eeaf518535d36a221287cdb133ea5a7
Author: Michael Armijo <marmijo@redhat.com>
Date:   Mon Jul 24 02:20:39 2023 -0400
multi-arch-builders: add additional RHCOS specific configs
Add RHCOS specific configs for `aarch64` and `ppc64le` that merges
the newly created splunk cofig with the arch specific configs.
commit 309e991f89af0b97875a34a9ad1a3462641f1af1
Author: Michael Armijo <marmijo@redhat.com>
Date:   Mon Jul 24 02:19:11 2023 -0400
multi-arch-builders: include splunk config in `s390x` RHCOS builder
Include the newly created splunk config when creating the `s390x`
remote builder.
commit bb2e704cfa61607441226fe863d6cd0aa818b55f
Author: Michael …
```

multi-arch-builders: use splunk to monitor and send logs

---

utils.groovy

The kola-openstack tests are passing again. Remove the workaround because the snooze expired on August 1. However, we still need to implement some additional clean up during garbage collection: https://github.com/coreos/coreos-assembler/issues/3550
This reverts commit 18252d4ce7e5dbbc5f1f5ce426cfe61ad7d5c793.

utils: remove 'snooze kola-openstack' workaround

---

jobs/bump-lockfile.Jenkinsfile

Right now it puts the stream in between the two emojis. Let's put the stream at the end.

bump-lockfile: improve slack message

---

manifests/jenkins.yaml

This will allow the emojis that are output by the denylist processing
from kola to show up in the jenkins output rather than being shown
as weird looking binary characters.

manifests/jenkins: set file.encoding=UTF-8

---

jenkins/controller/plugins.txt

The RHCOS Jenkins instance is failing to load because the fast-tracked `kubernetes` and `token-macro` plugins are now outdated. Both of these plugins have updated versions in [openshift/jenkins](https://github.com/openshift/jenkins/blob/master/2/contrib/openshift/base-plugins.txt). Let's remove these fast-tracks as they are no longer needed.
The `antisamy-markup-formatter` plugin is also listed as a dependency for the `timestamper` plugin, so add that to the list of plugins we layer on top of openshift/jenkins.

Minor Jenkins plugin updates

---

jobs/bump-lockfile.Jenkinsfile

Some recent changes like droping unsafety for the cache disk [1] and also adding a few more root reprovision tests that get run on the ppc64le platform [2] are causing us to bump up into the 2 hour time limit. Let's bump it.
[1] https://github.com/coreos/coreos-assembler/pull/3619
[2] https://github.com/coreos/fedora-coreos-config/pull/2597

jobs/bump-lockfile: bump timout by 30m

---

manifests/jenkins-s2i.yaml

I'm not sure why we didn't do this before. Without this, the imagestreams are only updated manually. In the `jenkins-with-cert` flow, we already have an `ImageChange` trigger which ensures that `jenkins:latest` is kept fresh. So this change is putting the non- custom-cert path at parity.
Note that this is separate from starting and deploying the S2I build, which currently is still done manually.

manifests/jenkins-s2i: set `scheduled` on our imagestreams

---

jobs/bump-lockfile.Jenkinsfile

Right now when the bump-lockfiles job runs it kicks off two runs of bump-lockfile (one for each stream) at the exact same time. This might be what is causing our timeouts to be getting hit lately (primarily because the ppc64le runs are taking longer) [1].
Let's limit the bump-lockfile job to a singular run at any given time.
[1] https://github.com/coreos/fedora-coreos-tracker/issues/1579

jobs/bump-lockfile: limit to single run at a time

---

jobs/build-arch.Jenkinsfile
jobs/bump-lockfile.Jenkinsfile

We recently hit `xz` on the ppc64le builder getting OOMkilled. Let's match x86_64 and also limit memory in the multi-arch paths too. Except we're using a more conservative value (though still plenty) since there's no resource-based scheduling on these builders.
We should probably add support for e.g. `cosa compress --xz-memlimit` instead to make this less awkward.

jobs: limit xz memory usage on multi-arch too

---

jobs/build-arch.Jenkinsfile
jobs/bump-lockfile.Jenkinsfile

At 2G, we increased compression time from 2m to 15m. Let's bump it a little more to see if we can strike a better balance between performance and memory.
Also fix the gaping typo of having the `cosa compress` invocation being commented out in 11f2ca6.
Fixes: 11f2ca6 ("jobs: limit xz memory usage on multi-arch too")

jobs: bump multi-arch xz limit to 4G

---

jobs/bump-lockfile.Jenkinsfile

We've done a few things but we still see timeouts sometimes on the FCOS ppc64le builder. It's mainly because that's the least resourced builder we have and it's shared with koji builds going on at the same time. Let's just bump it again.

jobs/bump-lockfile: bump timeout again

---

jobs/bump-lockfile.Jenkinsfile

We have a real problem on our ppc64le builder. Until we can figure it out we bump time yet again.

jobs/bump-lockfile: more time

---

jobs/build-fcos-buildroot.Jenkinsfile

We initially started building it only for x86_64 because there was no need to build for other arches[[1]], but with the work underway to have multi-arch support in CoreOS CI, that's no longer the case.
[1]: https://github.com/coreos/fedora-coreos-config/issues/1950

jobs/build-fcos-buildroot: build for all arches

---

jobs/kola-aws.Jenkinsfile
jobs/kola-azure.Jenkinsfile
jobs/kola-gcp.Jenkinsfile
jobs/kola-openstack.Jenkinsfile

Keeping around the test console logs of the last 100 builds seems excessive. Let's trim it back to 30 to match bump-lockfile. This should help reduce our storage requirements (each kola job right now takes about 1.2G- 1.4G).

jobs/kola-*: trim artifacts to 30

---

docs/config.yaml
jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile
jobs/bump-lockfile.Jenkinsfile
utils.groovy

This is an opt-in for using OSBuild to build the qemu qcow2 for now. It sets the COSA_USE_OSBUILD environment variable to instruct COSA what to do.

Add support for using OSBuild

---

docs/config.yaml
jobs/release.Jenkinsfile

Add a per-stream knob that enables the ability to skip brew uploads. This will allow us to skip these uploads for streams that don't need to be uploaded to brew, like development RHCOS builds that are based on CentOS Stream.
Fixes: https://github.com/coreos/fedora-coreos-pipeline/issues/922

config: add per-stream `skip_brew_upload` knob

---

multi-arch-builders/README.md

Switching back to us-east-1 for the IBM Cloud s390x builder because the Geo IP database thinks the 163.66.64.0/18 block is in France and not Toronto.

multi-arch-builders: updates for s390x us-east-1

---

config.yaml

Follow-up to coreos/fedora-coreos-tracker#1411
I am not familiar with your process, so let me know what I should be following. If you think there should be a new issue for this, for example.  So far after this I am planning to follow up with additional PRs for the web content. 
I tested and verified this works locally on Windows ARM using cost build and cosa buildextend-hyperv.
Thanks!

config: start building hyperv image for aarch64

---

jenkins/controller/plugins.txt

The recent plugin version bumps breaks when building with the current Jenkins version frozen in the cluster. Downgrade some of them to make them compatible.
Fixes 436c1c8 ("jenkins/plugins: update plugins to latest versions").

jenkins/plugins: make plugin versions compatible with Jenkins

---

config.yaml

See coreos/fedora-coreos-tracker#1533 and coreos/fedora-coreos-tracker#1548

Add Apple Hypervisor (applehv) to default artifacts

---

docs/config.yaml
jobs/build-arch.Jenkinsfile

This knob will be used in the RHCOS pipeline to avoid running heavy tests without KVM support on ppc64le.
Related: https://issues.redhat.com/browse/COS-2554

config: add temporary `hacks.ppc64le_kola_minimal` knob

---

jobs/build-arch.Jenkinsfile

Originally, the logic for the `ppc64le_kola_minimal` hack trigged on all arches if the hack was enabled. Update the condition to only trigger when building for the ppc64le architecture.
See: https://github.com/coreos/fedora-coreos-pipeline/pull/940

jobs/build-arch: make `ppc64le_kola_minimal` specific to ppc64le

---

jobs/build-arch.Jenkinsfile

Even that test takes too long and times out. We could increase the test
timeout but at this point, let's try to sprint to something that works.

jobs/build-arch: don't even run `iso-live-login` test with ppc64le_kola_minimal

---

jobs/build-arch.Jenkinsfile
utils.groovy

Our builder only has 32G of RAM. Combined with the fact that ppc64le VMs require a minimum of 4G of RAM, that doesn't leave much capacity for parallelism. We don't run tests, but multiple artifacts launch VMs.
Let's bring it down to 1 build at a time to make it more reliable. If the throughput is too slow, we'll bump to a beefier instance and increase parallelism here.

jobs/build-arch: only run one ppc64le build at a time with ppc64le_kola_minimal

---

jobs/build-arch.Jenkinsfile

We're tightly fitting in the 4h timeout currently on the RHCOS ppc64le builder and sometimes timing out. Bump it up to 5h.

jobs/build-arch: increase timeout with ppc64le_kola_minimal

---

config.yaml

This reverts commit 41121e394c82bc6af843eed3b72472ef8f1adb84. The new Ignition version is being promoted to stable now sow we can allow applehv to be built for stable.

Revert "config: skip applehv on stable for next set of releases"

---

config.yaml
next-devel/badge.json
next-devel/status.json

With https://github.com/coreos/fedora-coreos-config/pull/2757 we dropped the zincati pin in `testing-devel` so there is no longer any difference between `next-devel` and `testing-devel`.

config.yaml: disable next-devel

---

jobs/build.Jenkinsfile

The build-arch timeout was increased to 5h with the ppc64le_kola_minimal hack. Increase the build job's timeout to 5h as well so it doesnt timeout when waiting for the multi-arch job to complete.
See: https://github.com/coreos/fedora-coreos-pipeline/pull/944

jobs/build: increase timeout with ppc64le_kola_minimal

---

jobs/build-arch.Jenkinsfile

The build-arch job is for some reason timing out again at 4h. Let's bump to get through this round of releases and then try to dig in to see if we can speed things up again.

jobs/build-arch: increase timeout (again)

---

utils.groovy

In 582bfae we changed the azure creds used for testing to a single file/secret. What we didn't do was update the run_cloud_tests() logic to check for the new secret name, it was still using the old secret names.
I assume this continued to work because the old secrets still existed in the pipeline until I recently deleted them because our new secret expired and I noticed the old named ones existed and deleted them.
Fixes 582bfae

utils: fix azure launching login in run_cloud_tests()

---

jobs/check-aws-regions.Jenkinsfile

Instead of checking for changes in the SCM, lets trigger this job daily like the bump-lockfiles job.

jobs/check-aws-region: run daily

---

jobs/release.Jenkinsfile

That message supports specifying multiple arches now. So let's do that since it's just cleaner that way.

jobs/release: emit a single `stream.release` fedmsg

---

jenkins/controller/plugins.txt

I'd like to have `bodhi-trigger` in CoreOS CI send messages to Matrix when failures occur. If that works well, we could also in the future move pipeline notifications to Matrix as well.

plugins: add `matrix-communications`

---

jobs/bump-lockfile.Jenkinsfile

This is no longer necessary since c041f3d and should have been cleaned up in that commit.

jobs/bump-lockfile: drop use_osbuild use

---

HACKING.md
deploy
manifests/jenkins-s2i.yaml
manifests/jenkins.yaml

In the case where we don't need custom certs, we had the
`openshift/jenkins:2` imagestream feed into the `jenkins:latest`
imagestream, which then was the input to the S2I build.
And similarly, we had `openshift/jenkins-agent-base:latest` feed  into
`jenkins-agent-base:latest`.
In eb70bf7 ("manifests/jenkins-s2i: set `scheduled` on our
imagestreams"), we added `scheduled: true` for those tags thinking they would
keep those imagestreams up to date with the `openshift/` ones. But in
fact, `scheduled: true` only works when an imagestream tracks an image
in an external registry.
There is no way as far as I can tell to have an imagestream tag track
another imagestream tag. The closest is aliases, but those only work
for tags within the same imagestream, not different imagestreams. This is
by …

manifests: drop "aliased" `jenkins` and `jenkins-agent-base` imagestream tags

---

config.yaml

Fedora 40 has branched from rawhide. Enable the branched stream to track F40.
xref: https://github.com/coreos/fedora-coreos-config/pull/2862

config: enable branched stream

---

config.yaml

This is causing errors in the pipeline parsing the YAML.

config: fixed branched stream indentation

---

config.yaml

We're phasing this in and it will be enabled for `next` soon enough so let's enable it for `branched` now.

config: use OSBuild for the branched stream too

---

config.yaml
docs/config.yaml
jobs/build.Jenkinsfile

The versionary FCOS script was one of the few things that differed between FCOS and RHCOS and was awkwardly attached as a hack knob to work.
Now, we promote it to a proper key under the `misc` section, with support for stream-level overrides. This is prep for also using a versionary in other streams.
The versionary is now part of the source config and cosa knows how to execute it if the `--versionary` argument is passed.

config: promote `versionary` key, rework it

---

config.yaml

Ref: https://github.com/coreos/fedora-coreos-tracker/issues/1674

`next-devel` is now on Fedora 40 so disable `branched` stream

---

jobs/build-kola-containers.Jenkinsfile

Add a new Jenkins job to build containers for kola
Some kola tests require external images. This job will build
and publish the images present under the test/containers path
of coreos-assembler.
Inital PR for coreos-assembler: https://github.com/coreos/coreos-assembler/pull/3727
x-ref https://github.com/coreos/fedora-coreos-tracker/issues/1639
Once https://github.com/coreos/coreos-assembler/pull/3727 is merged i'll need to create the repos in quay and update the default values, before merging this one.

Add a new Jenkins job to build containers for kola

---

docs/config.yaml
libcloud.groovy

We are no longer building any release that requires this hack. Let's drop it.

drop skip_govcloud_hack

---

jobs/build-podman-os.Jenkinsfile

- Integrate essential Podman build jobs into our CI
infrastructure to facilitate unblocking tasks for
the Podman team. The objective is to ensure
flexibility by avoiding strong dependencies on our
internal components such as cosa and libraries,
enabling seamless transition for the Podman team in the future.

Add podman-os build job

---

jobs/build-podman-os.Jenkinsfile

- Reflect changes from https://github.com/coreos/coreos-assembler/pull/3770, adding the extra-kargs configuration from image-base.yaml

 build-podman-os: Add extra-kargs

---

config.yaml
docs/config.yaml
libcloud.groovy

We need to add `FedoraGroup=coreos` tag adhering to the Fedora policy for the AWS account.
Ref: https://github.com/coreos/fedora-coreos-tracker/issues/1605

config: Add `FedoraUser=coreos` tag to AMIs

---

jobs/build-kola-containers.Jenkinsfile

Currently the last time this job ran was over a month ago. Let's build periodically to keep the content fresh and to also know sooner if breaking changes occur.

jobs/build-kola-containers: build weekly

---

config.yaml

They are now on F40 and we can roll this out!
xref: https://github.com/coreos/fedora-coreos-tracker/issues/1653

config: enable OSBuild for testing/testing-devel

---

docs/config.yaml
jobs/build-arch.Jenkinsfile
jobs/debug-pod.Jenkinsfile

The podman remote feature assumes that the version on the client and the one on the host match versions, within some margin. So the `cosa_controller_img` knob we had before was useful.
This reverts commit dbad52bc5f11b73fad6459e54a1ed797fc0fb3a8. But:
1. we drop the `_hack` suffix and update the documentation
2. the default is to always use the `:main` cosa image, which most of the time will have a podman remote matching the FCOS version on the builder (except for that small period of time during a major rebase when FCOS is ahead of cosa)
Motivated by our pipeline hitting
https://github.com/containers/podman/discussions/22531
due to most FCOS streams being on f40 and cosa still being on f39.

Bring back `cosa_controller_img` knob, drop hack status

---

jobs/bump-jenkins-plugins.Jenkinsfile

We are creating this `bump-jenkins-job` in order to periodically update the latest plugin version of Jenkins offered by [Openshift/Jenkins](https://github.com/openshift/jenkins).
`bump-jenkins-job` automates the process of checking for updates to Jenkins plugins, updating the plugin versions in a configuration file, pushing the changes to a Git repository, and opening a pull request for review.
Plugin Update Process:
- This job reads a list of plugins from the file [plugins.txt](https://github.com/coreos/fedora-coreos-pipeline/blob/main/jenkins/controller/plugins.txt) in the repository.
- It iterates over each plugin, checks for updates and if a newer version is available, it updates the version in the file.
- For each plugin, it fetches the latest version by querying a URL based on the …

jobs: Add a bump-jenkins-plugins job

---

config.yaml

The default in COSA is now to use OSBuild [1] so we don't need to set these any longer.
[1] https://github.com/coreos/coreos-assembler/pull/3800

config: drop application of COSA_USE_OSBUILD environment var

---

jobs/bump-jenkins-plugins.Jenkinsfile

Slack notification intended to be sent at both instances of build success and failure.

jobs/bump-jenkins-job: update slack notification

---

jobs/bump-jenkins-plugins.Jenkinsfile

A PR would be created after the build run of bump-jenkins-job. To notify about the open PR, it would be better if the emoji is set to ':pr'.

jobs/bump-jenkins-job: Change in emoji of slack notification

---

jobs/build-podman-os.Jenkinsfile

We implicitly before relied on the osbuild manifest templates to fall into the `ostree container image deploy` path for our use case just by having the `container_repo` key set. But a recent cosa change tweaked this so that now we *must* also explicitly specify `deploy-via-container`.
See also https://github.com/coreos/coreos-assembler/commit/48f11cc8cd928dbd2b2b06927c372b0a10dd1543.

jobs/build-podman-os: set `deploy-via-container: true`

---

utils.groovy

These are environment variables, so we need to escape it to let bash interpret it instead of Groovy.

utils.groovy: escape MATRIX_WEBHOOK_URL and TOKEN

---

jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile
jobs/fix-build.Jenkinsfile
utils.groovy

Very often, our pipeline flakes after the final archiving stage, e.g. if
the fedora-messaging queue is down, or Robosignatory is backed up.
Ideally, as discussed in #566, we could just rerun the job and have it
know to salvage the builds, but there's a lot of details there that we
need to get right. (And... it's probably not worth tackling if we're
eventually moving away from Jenkins anyway.)
For now at least, it's not hard to just have a separate job that reruns
those last final steps from the `build` and `build-arch` jobs so we can
salvage those builds.
You need to know what you're doing when using this job. It should only
be used when strictly necessary. It's often better to just do a new
build instead.
Fixes: #566

jobs/fix-build: new job to fix archived builds

---

jobs/fix-build.Jenkinsfile
utils.groovy

Normally, `cosa sign` verifies that the signatures from Robosignatory are valid and then makes them public. We need to retain this check when using `fix-build` for safety (and also because we need the sigs public).
Just make this so that if `SKIP_SIGNING` is on (i.e. we know the builds were eventually signed), then pass `--verify-only` to `cosa sign` which will skip re-requesting signing.

jobs/fix-build: support verifying signuates

---

jobs/fix-build.Jenkinsfile
utils.groovy

- include version in job description
- fix passing `--arch` args to `cosa buildfetch`
- use `:hammer:` emoji instead of `:key:` for Slack message

jobs/fix-builds: minor fixes

---

docs/config.yaml
jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile
jobs/bump-lockfile.Jenkinsfile
jobs/kola-aws.Jenkinsfile
jobs/kola-azure.Jenkinsfile
jobs/kola-gcp.Jenkinsfile
jobs/kola-kubernetes.Jenkinsfile
jobs/kola-openstack.Jenkinsfile
jobs/kola-upgrade.Jenkinsfile

Kola can now support skipping kola tags per stream \[1]. Add support for that here by modifying each Jenkins job to pass the list of kola tags to skip to the kola function.
\[1]: https://github.com/coreos/coreos-ci-lib/pull/159
See: https://github.com/coreos/fedora-coreos-pipeline/issues/1002

jobs/build: add support for stream level `skip_kola_tags` knob

---

jobs/sync-stream-metadata.Jenkinsfile

This unassuming job is actually critical to the release pipeline flow. We have checkbox items in the release checklist to make sure that it ran correctly, but for other things (e.g. reverting a rollout, or adding release notes), there's zero visibility into whether the sync actually happened unless one goes to check the job.
Let's just always send a Slack notification if the job fails.
Prompted by noticing that it failed recently because of https://github.com/coreos/fedora-coreos-streams/pull/924 only by pure chance (I was looking at the job for another reason).

jobs/sync-stream-metadata: send Slack message on failure

---

jobs/build-podman-os.Jenkinsfile

Recent cosa change enabled osbuild based `secex` build, where image contains more partitions (for dm-verity) and `root` labeled filesystem is not the last one, so now we should also set `rootfs-size`.
See also https://github.com/coreos/coreos-assembler/commit/443b9da52d5556b70492a3229801619881dabc4d

jobs/build-podman-os: set `rootfs-size: 0`

---

config.yaml
multi-arch-builders/coreos-s390x-rhcos-builder.bu
multi-arch-builders/create-cex-device.sh

Add a new systemd unit that sets up a CEX device for use by kola tests.
The device is associated with a UUID. This UUID is passed to kola via
an environment variable for now.
See also: https://github.com/coreos/coreos-assembler/pull/3828

Set up CEX device on s390x builder

---

manifests/jenkins-s2i.yaml
utils.groovy

The following changes are needed to migrate the RHCOS devel pipeline to the new ITUP cluster:
- Add the devel jenkins URL to the list of protected jenkins instances
- Specify the exact mirror to use when downloading Jenkins plugins
```
commit 8fb1f1870648e68211ef2a036cb789d150871363
Author: Michael Armijo <marmijo@redhat.com>
Date:   Mon Jul 1 17:37:08 2024 -0600
manifests/jenkins-s2i: specify mirror for Jenkins plugins download
The new ITUP cluster for the RHCOS pipeline requires all connections
to be specified in a FirewallEgress file. Let's use the environment
variable `JENKINS_UC_DOWNLOAD`[1] to ensure the Jenkins plugins
are always downloaded from 'https://archives.jenkins.io'
[1]: https://github.com/openshift/jenkins/blob/ffc5df9d865e0c60947477a1ff7d354d1d618daf/2/contrib/jenkins/ins …
```

ITUP Cluster updates for the RHCOS Pipeline migration

---

config.yaml

This tag the manifest with the full version number. First step for https://github.com/coreos/fedora-coreos-tracker/issues/1367
Is it that simple ? 
Obviously I need to add the GC code as well

jobs/release: tag containers images with version

---

jobs/sync-stream-metadata.Jenkinsfile

Fetching the Slace API Token seems to be failing in this job because the default fedora-coreos-pipeline service account can't access the openshift secrets directly. This is fallout from https://github.com/coreos/fedora-coreos-pipeline/pull/1012 where sending a Slack message on failure was added to this job.

jobs/sync-stream-metadata: use jenkins service account to start pod

---

jobs/sync-stream-metadata.Jenkinsfile

The logic for sending the slack message on build failure relies on `currentBuild.result`. Set this variable to `SUCCESS` when completing the job successfully.

jobs/sync-stream-metadata: report successful build result

---

gc-policy.yaml

Update the duration of pruning for the mechanical streams from three years to one year since we didn't start uploading AMIs till `38.20220826.91.0` and can hence use an aggressive approach for these streams. Also add `bodhi-updates` stream for the pruning

gc-policy.yaml: Update duration for pruning for mechanical streams

---

jobs/kola-upgrade.Jenkinsfile

When requesting memory for a COSA pod for x86_64 in the past (274a97a) we basically requested a pod with exactly the amount of memory we needed for the 3 virtual machines (bios,uefi,uefi-secure). This lead to a VM getting killed occasionally at first and then more consistently over time [1]. Most often this would be the uefi-secure VM most likely because that process was using more memory than the other two.
[1] https://github.com/coreos/fedora-coreos-tracker/issues/1756

jobs/kola-upgrade: account for overhead in x86_64 case

---

docs/aws-region-enable.md
jobs/check-aws-regions.Jenkinsfile

Added a document detailing the steps for enabling AWS regions. 
Updated the check-aws-regions.Jenkinsfile to include a link to the new documentation.

docs: Add AWS region enablement documentation

---

jobs/check-aws-regions.Jenkinsfile

The url in the slack message is pointing to "aaradhak" fcos-pipeline. This needs to be changed to "coreos" fcos-pipeline

jobs/checkaws: Change the URL to use coreos pipeline

---

manifests/jenkins.yaml

This was done live in cluster, so let's make sure to update our definition so it remains the source of truth.

manifests/jenkins: bump capacity to 25Gi

---

multi-arch-builders/coreos-s390x-rhcos-builder.bu
multi-arch-builders/create-cex-device.sh

To run the cex based luks encryption test, the builder user requires access to `/dev/vfio/0` device. This enable the builder user to use the cex device for luks encryption test.

multi-arch-builders: Set the permission of vfio device

---

config.yaml

IBM cloud does not have CEX hardware and CI test on FCOS is not possible. Hence removing the device UUID from env.

config.yaml: Removed the CEX UUID from config.yaml

---

multi-arch-builders/provisioning/aarch64/main.tf

The Aarch64 builder consistently complains about a lack of space. After a brief discussion we decided to increase its size.
See: https://github.com/openshift/os/issues/1554
Ref: https://github.com/coreos/fedora-coreos-pipeline/pull/1031#issuecomment-2340808882

provisioning/aarch64: increase aarch64 builder volume size

---

multi-arch-builders/builder-common.bu

The Aarch64 builder consistently complains about a lack of space, particularly around 10am UTC / 12pm BST (London).
This additional prune job aims to mitigate the space issues.
See: https://github.com/openshift/os/issues/1554

builder-common: Run additional prune job to free up space

---

manifests/jenkins-s2i.yaml
manifests/jenkins-with-cert.yaml

The `jenkins:2` tag hasn't been rebuilt in almost a year and the Jenkins version and plugin versions are getting out of date. The `scheduled-upgrade` and `scheduled-upgrade-redeploy` tags are rebuilt when there are changes in openshift/jenkins. By using these tags instead, we can keep our Jenkins insance more up-to-date. The `scheduled-upgrade-redeploy` tag will even automatically redeploy Jenkins when new changes are detected. This has been working in the production RHCOS pipeline for a while now.
https://docs.redhat.com/en/documentation/openshift_container_platform/4.16/html/jenkins/important-changes-to-openshift-jenkins-images#customizing-the-jenkins-image-stream-tag_important-changes-to-openshift-jenkins-images

manifests: use `scheduled-upgrade` as source ImageStream tag

---

config.yaml
next-devel/badge.json
next-devel/status.json

Enabling next-devel for the Fedora 41 release process.
See: https://github.com/coreos/fedora-coreos-tracker/issues/1695

config: enable next-devel 2024-09

---

config.yaml

We're trying to get more information on the root cause for https://github.com/coreos/fedora-coreos-tracker/issues/1796 and maybe this will help us find a clue.

config: set COSA_TESTISO_DEBUG on non-prod streams for now

---

utils.groovy

Add the new prod jenkins URL and update the namespace of the devel jenkins in the ITUP cluster. Also, remove the old devel jenkins URL as we are now fully ready to use the one in the ITUP cluster.

utils: update URLs in protected jenkins list

---

gc-policy.yaml
jobs/garbage-collection.Jenkinsfile

Update the `gc-policy.yaml` to prune the images and the whole builds itself. There's also a field for `images-kept` which we won't pruning when pruning the artifacts in meta.json's `images` key for each build.

gc-policy.yaml: Add images and builds pruning

---

jobs/garbage-collection.Jenkinsfile

Update `container_env` as empty map to make sure we can run the garbage-collection on streams that we are disabled at the moment like `branched` and `bodhi-updates`

garbage-collection: keep `container_env` as empty map

---

multi-arch-builders/builder-splunk.bu

The repo we are using to build the ITPAAS splunkforwarder container on the RHCOS multi-arch builders is out of date and references a splunkforwarder rpm that no longer exists in the internal repos. By omitting the build step for this container, we can pull in the already built image from ITPAAS that includes a more recent RPM. 
We'll still use `--arch=x86_64` for the sidecar container to ensure proper logging on non x86_64 builders.
See: https://github.com/coreos/fedora-coreos-pipeline/issues/1044

muliti-arch-builders/splunk: only build the splunk sidecar container

---

multi-arch-builders/builder-common.bu

Sometimes when image builds fail they leave behind containers and images in container storage. We weren't accounting for this in our pruning logic so over time these would grow and cause problems.
An snippet of an example of this is on our ppc64le builder where we had some of these old remnants from nearly two years ago and many since then too:
```
$ podman ps --external
CONTAINER ID  IMAGE                                                                                          COMMAND     CREATED         STATUS         PORTS       NAMES
d7cfa165ae4f  registry.fedoraproject.org/fedora:36                                                           buildah     23 months ago   Storage                    fedora-working-container
e04835810e64 …
```

multi-arch-builders: prune external containers/images too

---

jobs/build-cosa.Jenkinsfile
jobs/build-fcos-buildroot.Jenkinsfile
jobs/build-kola-containers.Jenkinsfile
jobs/release.Jenkinsfile

In a recent 4.16 z-stream release, a cri-o backport changed the default seccomp policy to by default block `clone(CLONE_NEW*)` syscalls:
https://github.com/cri-o/cri-o/pull/8514
This affects us in the FCOS pipeline which runs in a cluster that was recently updated. The `podman manifest` commands all AIUI also flow through the default path where it wants to enter a namespace if running rootless even though we don't strictly need root; we're not running containers, just creating manifest lists. Ideally podman would be less eager there.
Anyway, work around this as necessary by running
`cosa push-container-manifest` privileged.
There are two general places where this command is used: in container image build jobs (e.g. `build-cosa`), and in the release job.
Use the multi-arch builders to do …

jobs: run `cosa push-container-manifest` privileged

---

config.yaml
next-devel/badge.json
next-devel/status.json

Now that testing-devel is moving back over to F41 we don't have any differences in testing-devel and next-devel so we'll disable it.

config.yaml: disable next-devel 2024-10-28

---

config.yaml

If I understand correctly this was never used and we can stop generating it.

config: drop hashlist-experimental

---

gc-policy.yaml
jobs/garbage-collection.Jenkinsfile

Let's add the `dry_run` switch to the `build_description` for the garbage collection run. Also, expand the GC to `testing-devel` and `next-devel` for `cloud_uploads`.

Garbage Collection: Update build description and add streams

---

config.yaml
docs/config.yaml
utils.groovy

With https://github.com/coreos/coreos-assembler/pull/3930 we can now build multiple artifacts/platforms in a single OSBuild call. Let's add support here for detecting what artifacts are supported to be built by OSBuild and build them using OSBuild.
We segregate here "experimental" versus "stable" OSbuild built artifacts and add a pipecfg knob for opting into the "experimental" ones being built by OSBuild.

support conditionally building artifacts in an OSBuild stage

---

gc-policy.yaml
jobs/garbage-collection.Jenkinsfile

Rename `cloud-prune` to `coreos-prune` since we updated the script in cosa to `cmd-coreos-prune`. Update params to gc to take containers registry secret. Also, update the `gc-policy.yaml` to start containers pruning.

Add containers Garbage Collection.

---

jenkins/config/seed.yaml
jobs/build-development.Jenkinsfile
jobs/build-mechanical.Jenkinsfile
jobs/cloud-replicate.Jenkinsfile
jobs/fix-build.Jenkinsfile
jobs/garbage-collection.Jenkinsfile
jobs/release.Jenkinsfile

Most of our jobs enable build discard, but not all. Turn it on consistently across the board. Use the established setting of 100 for most of them, except for the garbage-collection and release jobs whose logs have more value.

jobs: consistently discard old builds

---

jobs/garbage-collection.Jenkinsfile

We need `cosa-push-registry-secret` to delete quay containers. Updated it from `oscontainer-push-registry-secret`.

jobs/gc: Change the credential for containers deletion

---

jobs/release.Jenkinsfile

Trigger the garbage collection job during the `release` job for the respective `stream` which will run the pruning job as specified in `gc-policy.yaml`

release: Run garbage collection from release job

---

docs/config.yaml
jobs/build-mechanical.Jenkinsfile
utils.groovy

Changes include: 
- Rework build-mechanical Jenkins Job:
- Change the logic of build-mechanical to continue to build all mechanical streams every 24 hours with the conditions set on the `scheduled: true` knob:
- if any mechanical stream has the knob set, then only trigger those streams
- if no mechanical stream has the knob set, then trigger all mechanical streams 
- This will be used to build the rhel-9.6 and c9s streams in the RHCOS pipeline on a schedule. 
- `scheduled: true` knob:
- used to flag streams that will be built on a schedule using the new `build-scheduled` Jenkins job. Specifically, this knob will be used to build two new RHCOS streams every two days.
- utils.groovy `scheduled_streams` method:
- From a provided list, returns a subset of streams  with the `scheduled: true` …

Rework build-mechanical Jenkins job and add  `scheduled: true` config knob

---

jobs/bump-jenkins-plugins.Jenkinsfile

The `bump-jenkins-plugins` job PR was getting opened against the `'main`' branch of `'coreosbot-releng' - fedora-coreos-pipeline`. We are making changes to open the PR against the `'main'` branch of `'coreos' - fedora-coreos-pipeline`.

jobs/bump-jenkins-plugins: Create PR against fedora-coreos-pipeline main

---

config.yaml

The `kola-openstack` job is passing again, so lets re-enable the job in the pipeline. There must have been some temporary issues with Vexxhost.
See: https://github.com/coreos/fedora-coreos-pipeline/issues/1061
This reverts commit e36f84eff14408070b2498d41b1161f191654f22.

config: re-enable `kola-openstack`

---

jobs/release.Jenkinsfile

Trigger the GC job only if `gc-policy.yaml` exists, which currently applies only to FCOS.

release: Run GC job only if gc-policy.yaml exists

---

jobs/build-mechanical.Jenkinsfile

Adjust the cron schedule trigger to start at 2am UTC every day to run this job at off-peak times. Also, run the scheduled builds serially by waiting for each build to finish before starting the next one.

jobs/build-mechanical: schedule at off-peak and run builds serially

---

jobs/build-mechanical.Jenkinsfile

If a scheduled build fails, the build-mechanical job will fail. Instead of the try/catch block to solve this, use `propagate: false`  instead to build each scheduled stream regardless of the build result.
follow-on to: https://github.com/coreos/fedora-coreos-pipeline/pull/1076

jobs/build-mechanical: use `propagate: false` to wait for build

---

jobs/build-cosa.Jenkinsfile

- Add a trigger for the Cosa build to execute at least twice a week (Mondays and Wednesdays);
- This ensures regular builds even if no PRs, maintaining build continuity during periods of inactivity.

build-cosa: Add scheduled trigger to run weekly on Mondays/Wednesdays

---

HACKING.md

Add a note about needing the the `shard=internal` label added to the Jenkins route to run the RHCOS pipeline in the internal ITUP clusters. It's also necessary to add the .int sub domain to the jenkins URL, specifically `jenkins-<NAMESPACE>.apps.int.<cluster-URL>`.

HACKING.md: Add note about RHCOS pipeline in ITUP clusters

---

docs/aws-region-enable.md

The AWS Account ID details are different for FCOS & RHCOS. The account details are updated for reference.

Update AWS Account ID for FCOS & RHCOS

---

jobs/build.Jenkinsfile

There is a lot of wasted work and leaked dead builds when EARLY_ARCH_JOBS is set. It has also caused downstream problems when someone forgets to unset it and incomplete builds are picked up. Lets turn it off by default and have the user enable when they need the time savings.

jobs/build: set EARLY_ARCH_JOBS to false by default

---

jobs/kola-gcp.Jenkinsfile

In https://github.com/coreos/fedora-coreos-config/pull/3356/ the test was updated and split in two tests, changing the names.

jobs/kola-gcp: update test names

---

jobs/bump-lockfile.Jenkinsfile

We haven't yet switched over the production streams to use OSBuild for the Live ISO/PXE yet, but I think it's time for us to go ahead and switch this job over (since `next` will be on Fedora 42 beta soon, which will be using OSBuild for live*).
While we are here let's just go ahead and build all disks up front, which means less OSBuild invocations to achieve the same result with less effort because we aren't jumping in and out of supermin multiple times.

bump-lockfile: consolidate image building; use OSBuild

---

config.yaml
docs/config.yaml
jobs/release.Jenkinsfile
utils.groovy

In RHCOS we need to publish the oscontainer image to the release repo and also the CI repo. Changing the registry_repo object to be an array instead of a map to allow multiple entries.
Patch best reviwed without whitespace changes

release: allow pushing container images to multipes repositories

---

docs/config.yaml
utils.groovy

As part of https://github.com/openshift/enhancements/pull/1637, we've moved OCP 4.19 to use bootimages with RHEL content only. This means that the bootimages built with OCP content will never be used in practice.
Add a `skip_disk_images` knob to disable building them.
We still generate the QEMU image for kola tests to run and because they're useful to debug, but we drop everything else. (Actually, we could also not generate the QEMU image either and sanity-check the OCI image with `kola run --oscontainer`, but that requires more rewiring.)
We don't generate live media since I don't think the test coverage from that is meaningfully different enough from the RHEL-only variants given that the additional OCP packages are unrelated.

config: add `streams[].skip_disk_images`

---

docs/aws-region-enable.md

When a new aws-region is added in RHCOS, the tenantegress is required to be updated. The process to update the tenantegress is added for reference.

Update the TenantEgress on adding aws regions in RHCOS

---

config.yaml
next-devel/badge.json
next-devel/status.json

F42 beta is GO! This is part of
https://github.com/coreos/fedora-coreos-tracker/issues/1851

config: enable next-devel 2025-03

---

docs/config.yaml
jobs/build-node-image.Jenkinsfile
utils.groovy

- As part of openshift/os#799, we'll want to build the "OCP node" image as a layered image on top of the RHCOS base image.
- Create a separete job where we build it and push to the registry

jobs: Add build-node-image.Jenkinsfile 

---

config.yaml

I have a sneaking suspicion that this is actually causing some of our ppc64le testiso tests to be more flaky. Let's just drop it for now.

config: drop COSA_TESTISO_DEBUG env var

---

jobs/build-development.Jenkinsfile
jobs/build-mechanical.Jenkinsfile
jobs/bump-lockfile.Jenkinsfile
jobs/bump-lockfiles.Jenkinsfile

Over time I'm thinking the build on every push to the git repo is a bit heavy. Often times the changes will be insignificant to warrant building, testing, and pushing all that we do. On the other hand, if there is a change we want we can easily click a button and start a build if we don't want to wait.
This commit switches the development streams to build daily similarly to the mechanical ones (i.e. rawhide). It also changes the timing of the build-mechanical and bump-lockfiles jobs and adds a stage to the bump-lockfile job to trigger a build once it has pushed.
The timings are chosen based on:
- bump-lockfiles at 04:00 UTC
- The bodhi/pungi updates composes seem to run around 0:00 UTC and finish within an hour or two. This gives some extra time so we hopefully trigger a bump-lockfile …

jobs/build-development: make development streams build daily

---

multi-arch-builders/builder-splunk.bu

The 2015 IT Root CA cert is no longer available and is causing the RHCOS multi-arch builders to fail to provision. Let's remove it from the butane config since the 2022 cert is sufficient.

multi-arch-builders/splunk: remove outdated RH Root CA Cert

---

config.yaml

Part of https://github.com/coreos/fedora-coreos-tracker/issues/1874

config: add hetzner for x86_64 and aarch64

---

jobs/kola-aws.Jenkinsfile
jobs/kola-azure.Jenkinsfile
jobs/kola-gcp.Jenkinsfile
jobs/kola-openstack.Jenkinsfile

jobs/kola: lock kola cloud jobs to avoid race condition
There were an issue recently where kola-aws and kola-gcp were
killed in the fetch metadata step because they started
at the same time. This aims to block cloud jobs since
the buildfetch doesn't take long. It shouldn't be too disruptive
to do this across all jobs that buildfetch at the beginning.
See: https://github.com/coreos/fedora-coreos-pipeline/issues/1079

jobs/build: lock buildfetch to avoid simultaneous jobs race condition

---

jobs/build-node-image.Jenkinsfile

I think it's useful when a new job comes up to start with notifying Slack on success and only later downgrading to on failure only if warranted.
This gives us more insight into how often it runs, whether a rerun passes, or a patch to fix a recent failure worked, etc. And just in general time to evaluate whether that information is useful to us.

jobs/build-node-image: send Slack message on success too

---

jobs/build-node-image.Jenkinsfile

Got an alert from a scanner that thought those lines contained secrets. Mark as `notsecret` to pacify it.

jobs/build-node-image: add `notsecret` tag to yumrepos secret line

---

docs/config.yaml
jobs/build-node-image.Jenkinsfile
jobs/release.Jenkinsfile

We want the ability to trigger build-node-image from the release job
instead of the latter being cron triggered. That way we reduce the
chance of having compose skew when in pre-GA state, and we get fresh
node images soon after the base image is updated.
I had initially made the mechanism more generic, but meh, it didn't seem
worth the complexity. We can always generalize it if another "follow-up
trigger" case shows up.

jobs/release: support triggering build-node-image

---

jobs/build.Jenkinsfile

The build-arch job is already at 300 and we just lost a built because the signing of the OSTree commit took an hour. Sigh..

build: adjust timeout to 300m

---

jobs/build-node-image.Jenkinsfile
utils.groovy

- Add a tag field for the staging repo in the node image: We're currently using the same repo for both production and staging, which causes the manifest to be updated in devel tests what makes it unreliable for production builds.

jobs/build-node-image: Add a tag field for the staging repo

---

config.yaml

F42 GA is GO for next Tuesday so we'll go ahead and enable more artifacts for OSBuild building for those streams.

config: enable osbuild_experimental for testing/testing-devel

---

docs/config.yaml
jobs/build-node-image.Jenkinsfile
utils.groovy

Some ART tooling does not support OCI manifests yet, so allow creating the manifests in v2s2 support.
This is already supported by COSA so it's just
passing the correct flag and tie it to a knob.
Defaults to false.

jobs:build-node-image: support publishing v2s2 manifests

---

config.yaml

Since https://github.com/coreos/coreos-assembler/pull/4074 most platforms have now been switched to default to osbuild for image building. Let's drop `osbuild_experimental: true` from all streams except for `rawhide` where the next round of experimental osbuild platforms should land first.
Here, we also add it to `stable` stream just in case we do the next build of `stable` (i.e. the first F42 build) with the same COSA that we used for the first F42 `testing` build, which wouldn't have the changed defaults in it.

config: drop osbuild_experimental from most streams

---

config.yaml

We're going to spin a new testing and we're going to use a tagged version of COSA to do it so let's re-enable osbuild_experimental for the testing stream in the config.
See https://github.com/coreos/fedora-coreos-streams/issues/1058#issuecomment-2824575349

config: enable osbuild_experimental for testing again

---

jobs/kola-upgrade.Jenkinsfile

F35 and F36 based FCOS starting points started to fail once we rebased COSA to F42 (and thus update edk2-ovmf).
See https://github.com/coreos/fedora-coreos-tracker/issues/1452#issuecomment-2835130860

jobs/kola-upgrade: adjust secureboot start version to F37+

---

jobs/bump-lockfile.Jenkinsfile

The build job is already at 300, adjust timeout here to the same value.

bump-lockfile: sync timeout with recent change to build.Jenkinsfile

---

utils.groovy

Instead of relying on the tag of the base image, first grab the manifest digest than pass that value to the builders.
This will avoid reusing stale images that may be present in the local containers storage when building.
Continuation of: https://github.com/coreos/fedora-coreos-pipeline/pull/1137

jobs/nodeimage: use the base image digest for FROM

---

docs/config.yaml
libcloud.groovy

Expand the replicate to clouds functionality to build AWS Windows License Included (winli) images for streams that support it before replicating AMIs to other regions. `cosa aws-replicate` will now replicate both traditional AMIs and aws-winli AMIs if present in the metadata.
See: https://github.com/coreos/coreos-assembler/pull/4069
Also add a `winli` knob to the pipeline config clouds.aws section to only build winli images for specific streams.

libcloud: build and replicate aws-winli images for supported streams

---

jobs/build-node-image.Jenkinsfile

Use the same emojis as for the build job and use the Slack syntax for them. Also use the currentBuild.description which has the emojis in the message.

Fix the emojis for the build-node-image job

---

jobs/build-node-image.Jenkinsfile

The build status emoji (e.g. ✨, 🔥) is currently at the end of the Slack message. Move it to appear at the beginning of the message to match format used by the other jobs.

jobs/build-node-image: move emoji to start of message to match other jobs

---

config.yaml

The defaults in COSA is now to build for all OSBuild platforms we support so we can drop these settings.

config: drop remaining osbuild_experimental=true entries

---

HACKING.md
deploy
manifests/jenkins-images.yaml
manifests/jenkins-s2i.yaml
manifests/jenkins-with-cert.yaml
manifests/jenkins.yaml

Added jenkins-stg-agent-base.yaml to work around limitations in the Staging environment.  Also updated documentation to note the unreliability of the Staging registry and instructed users to use their own agent image.

Switch Jenkins image tracking to registry tag due to Samples Operator… … deprecation

---

jobs/kola-azure.Jenkinsfile

The command to `create-gallery-image` was added in a previous commit`[1]` and is missing the `\` to make it a multi-line command causing the the job in the FCOS pipeline to fail. Let's fix that here so we can unblock the FCOS pipeline.
`[1]`: https://github.com/coreos/fedora-coreos-pipeline/commit/f8cf2bb42ac4a8d9ab9c8d9743bd16132c7b735b

jobs/kola-azure: add missing `\` to create-gallery-image command

---

config.yaml
jobs/kola-azure.Jenkinsfile

Azure doesn't allow dashes (-) in gallery names so the gallery name is updated to not include them. Also, set the gallery name on image creation which should have been done in a previous commit.
See: https://github.com/coreos/fedora-coreos-pipeline/pull/1153

jobs/kola-azure: update testing gallery name and vm size for tests

---

jobs/build-node-image.Jenkinsfile

This will fix a small UX issue in the release controller: it will add working links for our images to the openshift/os commit they were built from, just like the other images.
See also https://github.com/coreos/coreos-assembler/pull/4124 which this requires.

jobs/build-node-image: use `--add-openshift-build-labels`

---

config.yaml
jobs/kola-azure.Jenkinsfile

Begin building aarch64 gallery images in Azure and run all kola test on them. The feature for overriding the instance type per test does not account for architecture, and the `platforms.azure.nvme` test uses a hard-coded x86_64 instance type, so it's denylisted for aarch64.

kola-azure: start building and testing aarch64 images

---

manifests/jenkins.yaml

This file is little different from other projects in our sphere which were using DeploymentConfig and recently migrated to Deployment. It's using the JCasC plugin to make Jenkins deployments easier. Changes include modifications of :
* `API Version and Kind`
* `Selector Structure`
* `Strategy Configuration`
* `Triggers Modification`
See: https://github.com/coreos/fedora-coreos-pipeline/issues/1090

manifests/jenkins: Migrate from DeploymentConfig to Deployment

---

jenkins/controller/plugins.txt

Apparently Blue Ocean Jenkins view is deprecated. There is a new "Pipeline Graph View" plugin that is recommended instead. The pipeline-graph-view version `419.v946ff4a_49e1c `is compatible with our current jenkins version.
Ref: https://github.com/jenkinsci/dark-theme-plugin/issues/89#issuecomment-2939077690

Add pipeline-graph-view plugin

---

docs/config.yaml
jobs/build-node-image.Jenkinsfile

Adds an option to skip the Brew upload stage when building the Node image. Useful for test builds where publishing to the Brew repository is not needed.

 feat(build-node-image): add option to skip brew upload stage 

---

multi-arch-builders/builder-common.bu

We've seen some weird cases where pruning images fails because some containers were using images so let's just try to prune containers first.

multi-arch-builders/builder-common: prune containers first

---

config.yaml

We're still working out a little bit what the best format is for the uploaded disk images in https://github.com/coreos/fedora-coreos-tracker/issues/1652

config: limit proxmoxve to `testing/stable` for now

---

config.yaml

We are moving to a new datacenter and don't have a ppc64le builder set up there yet. This will aid in the migration.

config: disable ppc64le architecture for now

---

config.yaml
utils.groovy

We've moved the FCOS pipeline to a new cluster, so we need to update the
list of protected jenkinses to mark this cluster as the official one.
We also have access to the ppc64le builder from the new cluster, so we can
add ppc64le back into the list of additional arches.

utils: add new FCOS jenkins to protected jenkinses

---

utils.groovy

The Fedora datacenter move is complete now so we can use the main URL again.

utils: revert to the main URL for prod FCOS jenkins

---

jobs/build-node-image.Jenkinsfile

Like some of our other jobs, all the heavy lifting is done in dedicated builders so we can be more conservative here. The default request is 2 (which adds up to 3 with the jnlp container, which... we could probably cut that down to a quarter).

jobs/build-node-image: only request 1 CPU

---

config.yaml

We've decided to keep with the .xz compression for now so
we can just promote this to stable.
https://github.com/coreos/fedora-coreos-tracker/issues/1652#issuecomment-3057966216

config: promote proxmoxve to stable

---

jobs/build-node-image.Jenkinsfile
utils.groovy

The skopeo command expects Go-style architecture names like `amd64` and `arm64`. Introduce a map to handle both `x86_64` and `aarch64` translations.

jobs/build-node-image: fix skopeo arch mapping for aarch64

---

jobs/build-nvidia-bfb.Jenkinsfile

This job is for a proof-of-concept downstream effort to build `BFB` files to boot on NVIDIA BlueField DPU hardware [1]. It leverages the `cosa import` flow to pull a customized RHCOS container and build boot media from it.
This job was initially copied and based on the build-arch job since this platform is `aarch64` only.
[1] https://docs.nvidia.com/networking/display/bluefielddpuosv450/deploying+bluefield+software+using+bfb+from+host

Add build-nvidia-bfb job

---

jobs/build-arch.Jenkinsfile

In the build-with-buildah workflow `cosa fetch` doesn't do anything so we need to add the `--autolock=VERSION` argument to the `cosa build` call.

jobs/build-arch: add --autolock to the `cosa build` call

---

jobs/build-arch.Jenkinsfile

It turns out the underlying code will autolock anyway even without --autolock if it detects the right conditions so this change didn't actually do anything. The reason for the inconsistent behavior I was seeing that caused me to implement this change was fixed by https://github.com/coreos/fedora-coreos-config/pull/3705
The other reason to revert this is older COSA (i.e. 4.14 and older) don't recognize this option at all.
This reverts commit 0e1c9742351ec83e1c9978a4cec209997f06c75e.

Revert "jobs/build-arch: add --autolock to the `cosa build` call"

---

jobs/fix-build.Jenkinsfile

This should have been done as part of 71bbc5e

jobs/fix-build: skip ostree import for F43+

---

docs/config.yaml
jobs/build.Jenkinsfile

Adds support for a no_upload flag in the config to skip S3 uploads. If both the config and pipeline specify the flag, the pipeline value takes precedence.

feat(build): add no_upload config knob

---

jobs/release.Jenkinsfile

Fixes b4df2de ("jobs/release: sign OCI images").

jobs/release: fix variable name passed to `cosa sign --oci`

---

config.yaml
next-devel/badge.json
next-devel/status.json

We are ready to have `next` differ from `testing`. We are doing a migration to container signing [1] for `next` only for now and then immediately after we'll be switching over `next` to F43 content because the F43 beta release is ready to go next week.
[1] https://github.com/coreos/fedora-coreos-tracker/issues/2029

config: enable next-devel 2025-09

---

jobs/build.Jenkinsfile
jobs/kola-upgrade.Jenkinsfile

The release job is the one that pushes (and signs) containers. If we want our kola-upgrade test to be more realistic it makes sense to have it run after the containers have been pushed so we can test pulling from the registry and also signature verification.
Here we make the kola-upgrade job wait until the release job is done before starting the upgrade tests. For the production builds this won't really have any effect because we don't autorun the release job, but that's OK.

Add locking to make kola-upgrade jobs run after release job.

---

jobs/release.Jenkinsfile

The argument to `resource:` is just a string. Fixes 3051996

jobs/release: fix lock specificiation

---

config.yaml

This was useful to get started but nowadays this is enabled by the src config itself so there's no need for this.

config.yaml: remove COSA_BUILD_WITH_BUILDAH

---

jobs/build-cosa.Jenkinsfile

The build-cosa job is being OOMKilled during its initializiation steps. Increase the memory of the cosaPod to 1024Mi to provide more headroom.

jobs/build-cosa: increase cosaPod memory allocation to 1014Mi

---

jobs/release.Jenkinsfile

In 3051996 we added a second level of locking on a per-arch basis. However if the release job is started only for 1 architecture, using `1..-1` results in an index out of bounds as the inital array is one. Use a remove in place operation instead.

release: fix the lock for releases containing 1 arch

---

jobs/build-arch.Jenkinsfile
jobs/build.Jenkinsfile
jobs/kola-upgrade.Jenkinsfile

Unlike the build and build-arch jobs we need to still have compat here for older releases < 42 where no oci-images entry in the release metadata existed. i.e. we want to start the upgrade test from those older versions so we need to have compat here for that case.
Fixes 2becf34

kola-upgrade: fix architecture check for older releases

---

libcloud.groovy

This code was supposed to be removed in an earlier change`[1]`. Removing it now fixes the cloud-replicate job, which is failing due to the undeclared variable.
`[1]`: https://github.com/coreos/fedora-coreos-pipeline/pull/1217

libcloud.groovy: drop outdated cleanup step
